Repository ubccr/xdmod, pull requests merged in 2018-03, with the labels that each got.

#447 Update release date
  CHANGELOG.md
  docs/upgrade.md
  html/about/release_notes/xdmod.html
  open_xdmod/modules/xdmod/xdmod.spec.in
Labels: release prep

#451 Update supported versions table
  docs/support.md
Labels: documentation, release prep

#401 Allow SELECT * FROM DUAL
  classes/ETL/DbModel/Join.php
Labels: ETL, enhancement

#399 Enable batch aggregation by default
  classes/ETL/Aggregator/AggregatorOptions.php
  classes/ETL/Aggregator/pdoAggregator.php
Labels: ETL, enhancement

#402 Show warnings when executing LOAD DATA INFILE
  classes/ETL/Ingestor/pdoIngestor.php
  open_xdmod/modules/xdmod/component_tests/lib/ETL/IngestorTest.php
Labels: ETL, enhancement

#420 Add a TRACE log level
  classes/CCR/Log.php
  composer.json
  composer.lock
  db/data/mod_logger.sql
  db/migrations/7.5.0-8.0.0/mod_logger.sql
  docs/software-requirements.md
  open_xdmod/modules/xdmod/tests/lib/LogTest.php
  open_xdmod/modules/xdmod/xdmod.spec.in
Labels: enhancement

#459 Display SQL warnings returned from single database ingest
  classes/ETL/Ingestor/pdoIngestor.php
  open_xdmod/modules/xdmod/component_tests/lib/ETL/IngestorTest.php
Labels: ETL, data quality, enhancement

#458 Fix display of duration label on chart import to Metric Explorer
  html/gui/js/modules/Summary.js
  html/gui/js/modules/Usage.js
Labels: bug

#460 Update the js etl library to support specifying table aliases
  etl/js/lib/schema.js
Labels: ETL, enhancement

#462 Do not translate 0 to the empty string during ETL
  classes/DB/PDODBMultiIngestor.php
  classes/ETL/Ingestor/pdoIngestor.php
Labels: ETL, data quality

#461 Add post-merge tasks to Configuration class
  classes/ETL/Configuration/Configuration.php
Labels: ETL, enhancement

#471 Fix misspellings of "hierarchy" and ingest-xdmod typo in 7.5 hierarchy.md
  docs/hierarchy.md
Labels: documentation

#469 Fix misspellings of "hierarchy" and ingest-xdmod typo in 6.6 hierarchy.md
  docs/hierarchy.md
Labels: documentation

#470 Fix misspellings of "hierarchy" and ingest-xdmod typo in 7.0 hierarchy.md
  docs/hierarchy.md
Labels: documentation

#473 Fix misspellings of "hierarchy" and ingest-xdmod typo in 7.1 hierarchy.md
  docs/hierarchy.md
Labels: documentation

#474 Fix misspellings of "hierarchy" and ingest-xdmod typo in 6.5 hierarchy.md
  docs/hierarchy.md
Labels: documentation

#349 Improve data ingestion and aggregation speed
  bin/xdmod-ingestor
  classes/DB/Aggregators/JobTimeGenerator.php
  classes/DB/Aggregators/JobTimeseriesAggregator.php
  classes/DB/Aggregators/ProcessorBucketGenerator.php
  classes/DB/TimePeriodGenerators/TimePeriodGenerator.php
  classes/DataWarehouse/Query/Jobs/GroupBys/GroupByJobTime.php
  classes/DataWarehouse/Query/Jobs/GroupBys/GroupByNodeCount.php
  classes/DataWarehouse/Query/Jobs/GroupBys/GroupByProvider.php
  classes/DataWarehouse/Query/Jobs/GroupBys/GroupByQueue.php
  classes/DataWarehouse/Query/Jobs/GroupBys/GroupByResource.php
  classes/DataWarehouse/Query/Jobs/Statistics/ActiveResourceCountStatistic.php
  classes/DataWarehouse/Query/Jobs/Statistics/AverageProcessorCountStatistic.php
  classes/DataWarehouse/Query/Jobs/Statistics/AverageWallHoursStatistic.php
  classes/DataWarehouse/Query/Jobs/Statistics/JobCountStatistic.php
  classes/DataWarehouse/Query/Jobs/Statistics/JobSizeWeightedByCPUHours.php
  classes/DataWarehouse/Query/Jobs/Statistics/MaxProcessorCountStatistic.php
  classes/DataWarehouse/Query/Jobs/Statistics/MinProcessorCountStatistic.php
  classes/DataWarehouse/Query/Jobs/Statistics/NodeUtilizationStatistic.php
  classes/DataWarehouse/Query/Jobs/Statistics/NormalizedAverageProcessorCountStatistic.php
  classes/DataWarehouse/Query/Jobs/Statistics/SEMAverageCPUHoursStatistic.php
  classes/DataWarehouse/Query/Jobs/Statistics/SEMAverageNodeHoursStatistic.php
  classes/DataWarehouse/Query/Jobs/Statistics/SEMAverageProcessorCountStatistic.php
  classes/DataWarehouse/Query/Jobs/Statistics/SEMAverageWallHoursStatistic.php
  classes/DataWarehouse/Query/Jobs/Statistics/UtilizationStatistic.php
  classes/OpenXdmod/DataWarehouseInitializer.php
  classes/OpenXdmod/Ingestor/Hpcdb/Accounts.php
  classes/OpenXdmod/Ingestor/Hpcdb/AllocationBreakdowns.php
  classes/OpenXdmod/Ingestor/Hpcdb/Allocations.php
  classes/OpenXdmod/Ingestor/Hpcdb/AllocationsOnResources.php
  classes/OpenXdmod/Ingestor/Hpcdb/FieldOfScience.php
  classes/OpenXdmod/Ingestor/Hpcdb/FieldOfScienceHierarchy.php
  classes/OpenXdmod/Ingestor/Hpcdb/JobHosts.php
  classes/OpenXdmod/Ingestor/Hpcdb/Jobs.php
  classes/OpenXdmod/Ingestor/Hpcdb/NodeCount.php
  classes/OpenXdmod/Ingestor/Hpcdb/Organizations.php
  classes/OpenXdmod/Ingestor/Hpcdb/PIPeople.php
  classes/OpenXdmod/Ingestor/Hpcdb/People.php
  classes/OpenXdmod/Ingestor/Hpcdb/PeopleUnderPI.php
  classes/OpenXdmod/Ingestor/Hpcdb/PrincipalInvestigators.php
  classes/OpenXdmod/Ingestor/Hpcdb/Queues.php
  classes/OpenXdmod/Ingestor/Hpcdb/Requests.php
  classes/OpenXdmod/Ingestor/Hpcdb/ResourceAllocated.php
  classes/OpenXdmod/Ingestor/Hpcdb/ResourceSpecs.php
  classes/OpenXdmod/Ingestor/Hpcdb/ResourceTypes.php
  classes/OpenXdmod/Ingestor/Hpcdb/Resources.php
  classes/OpenXdmod/Ingestor/Hpcdb/ServiceProvider.php
  classes/OpenXdmod/Ingestor/Hpcdb/SystemAccounts.php
  classes/OpenXdmod/Migration/Version750To800/DatabasesMigration.php
  classes/OpenXdmod/Setup/DatabaseSetup.php
  classes/XDAdmin.php
  configuration/etl/etl.d/hpcdb-modw.json
  configuration/etl/etl_tables.d/hpcdb-modw/jobfact_hpc_aggregation.json
  db/migrations/7.5.0-8.0.0/modw_aggregates.sql
  db/schema/modw.sql
  docs/ingestor.md
  open_xdmod/modules/xdmod/integration_tests/scripts/bootstrap.sh
  open_xdmod/modules/xdmod/regression_tests/lib/Controllers/UsageExplorerTest.php
Labels: ETL, enhancement

#475 Fixes for hpcdb-modw conversion
  configuration/etl/etl.d/hpcdb-modw.json
  configuration/etl/etl_tables.d/hpcdb-modw/jobhosts.json
  configuration/etl/etl_tables.d/hpcdb-modw/system-account.json
  configuration/etl/etl_tables.d/xdmod/field-of-science.json
  configuration/etl/etl_tables.d/xdmod/job-tasks.json
Labels: bug

#476 Hpcdb modw fixes v2
  bin/xdmod-ingestor
  classes/OpenXdmod/Migration/Version750To800/DatabasesMigration.php
  configuration/etl/etl_tables.d/hpcdb-modw/job_record_hpc.json
  configuration/etl/etl_tables.d/xdmod/system-account.json
  db/migrations/7.5.0-8.0.0/modw.sql
Labels: bug

#417 Acl config sync
  bin/acl-config
Labels: ACL, data quality

#477 Improve XSEDE ACL tests
  open_xdmod/modules/xdmod/component_tests/README.md
  open_xdmod/modules/xdmod/component_tests/lib/BaseTest.php
  open_xdmod/modules/xdmod/component_tests/lib/ETL/IngestorTest.php
  open_xdmod/modules/xdmod/component_tests/lib/QueryTest.php
  open_xdmod/modules/xdmod/component_tests/lib/Roles/CenterStaffRoleTest.php
  open_xdmod/modules/xdmod/component_tests/lib/SlurmHelperTest.php
  open_xdmod/modules/xdmod/component_tests/lib/XDUserTest.php
  open_xdmod/modules/xdmod/component_tests/runtests.sh
  open_xdmod/modules/xdmod/integration_tests/lib/TestHarness/TestFiles.php
Labels: ACL, documentation, enhancement, tests

#445 Remove overly complicated aOptions::applyBasePath()
  classes/ETL/Maintenance/ExecuteSql.php
  classes/ETL/Maintenance/ManageTables.php
  classes/ETL/Maintenance/VerifyDatabase.php
  classes/ETL/aAction.php
  classes/ETL/aOptions.php
Labels: ETL, code cleanup

#480 Improve control of SQL warning logging
  classes/ETL/Aggregator/aAggregator.php
  classes/ETL/Ingestor/IngestorOptions.php
  classes/ETL/Ingestor/pdoIngestor.php
  classes/ETL/aRdbmsDestinationAction.php
  open_xdmod/modules/xdmod/component_tests/lib/ETL/IngestorTest.php
Labels: ETL, enhancement

#481 Cleanup some ETL json files
  configuration/etl/etl_tables.d/hpcdb-modw/account.json
  configuration/etl/etl_tables.d/hpcdb-modw/allocation-breakdown.json
  configuration/etl/etl_tables.d/hpcdb-modw/allocation-on-resource.json
  configuration/etl/etl_tables.d/hpcdb-modw/allocation.json
  configuration/etl/etl_tables.d/hpcdb-modw/field-of-science-hierarchy.json
  configuration/etl/etl_tables.d/hpcdb-modw/field-of-science.json
  configuration/etl/etl_tables.d/hpcdb-modw/host.json
  configuration/etl/etl_tables.d/hpcdb-modw/job_record_hpc.json
  configuration/etl/etl_tables.d/hpcdb-modw/jobfact_hpc_aggregation.json
  configuration/etl/etl_tables.d/hpcdb-modw/jobhosts.json
  configuration/etl/etl_tables.d/hpcdb-modw/min-max-date.json
  configuration/etl/etl_tables.d/hpcdb-modw/node-count.json
  configuration/etl/etl_tables.d/hpcdb-modw/organization.json
  configuration/etl/etl_tables.d/hpcdb-modw/people-under-pi.json
  configuration/etl/etl_tables.d/hpcdb-modw/person.json
  configuration/etl/etl_tables.d/hpcdb-modw/piperson.json
  configuration/etl/etl_tables.d/hpcdb-modw/principal-investigator.json
  configuration/etl/etl_tables.d/hpcdb-modw/queue.json
  configuration/etl/etl_tables.d/hpcdb-modw/request.json
  configuration/etl/etl_tables.d/hpcdb-modw/resource-allocated.json
  configuration/etl/etl_tables.d/hpcdb-modw/resource-fact.json
  configuration/etl/etl_tables.d/hpcdb-modw/resource-spec.json
  configuration/etl/etl_tables.d/hpcdb-modw/resource-type.json
  configuration/etl/etl_tables.d/hpcdb-modw/service-provider.json
  configuration/etl/etl_tables.d/hpcdb-modw/system-account.json
  configuration/etl/etl_tables.d/xdmod/account.json
  configuration/etl/etl_tables.d/xdmod/allocation-breakdown.json
  configuration/etl/etl_tables.d/xdmod/allocation-on-resource.json
  configuration/etl/etl_tables.d/xdmod/allocation.json
  configuration/etl/etl_tables.d/xdmod/error-descriptions.json
  configuration/etl/etl_tables.d/xdmod/field-of-science-hierarchy.json
  configuration/etl/etl_tables.d/xdmod/field-of-science.json
  configuration/etl/etl_tables.d/xdmod/hosts.json
  configuration/etl/etl_tables.d/xdmod/job-records.json
  configuration/etl/etl_tables.d/xdmod/job-tasks.json
  configuration/etl/etl_tables.d/xdmod/job-times.json
  configuration/etl/etl_tables.d/xdmod/jobfact_by_.json
  configuration/etl/etl_tables.d/xdmod/jobhosts.json
  configuration/etl/etl_tables.d/xdmod/min-max-date.json
  configuration/etl/etl_tables.d/xdmod/node-count.json
  configuration/etl/etl_tables.d/xdmod/organization.json
  configuration/etl/etl_tables.d/xdmod/people-under-pi.json
  configuration/etl/etl_tables.d/xdmod/person.json
  configuration/etl/etl_tables.d/xdmod/piperson.json
  configuration/etl/etl_tables.d/xdmod/principal-investigator.json
  configuration/etl/etl_tables.d/xdmod/processor-buckets.json
  configuration/etl/etl_tables.d/xdmod/queue.json
  configuration/etl/etl_tables.d/xdmod/request.json
  configuration/etl/etl_tables.d/xdmod/resource-allocated.json
  configuration/etl/etl_tables.d/xdmod/resource-fact.json
  configuration/etl/etl_tables.d/xdmod/resource-specs.json
  configuration/etl/etl_tables.d/xdmod/resource-type.json
  configuration/etl/etl_tables.d/xdmod/service-provider.json
  configuration/etl/etl_tables.d/xdmod/staging-jobhosts.json
  configuration/etl/etl_tables.d/xdmod/system-account.json
Labels: code cleanup

#483 Add Open XDMoD citation information
  docs/index.md
Labels: documentation

#484 Add Open XDMoD citation information for 7.5
  docs/index.md
Labels: documentation

#486 Add filtered codes to SQL warning message
  classes/ETL/aRdbmsDestinationAction.php
Labels: ETL

#487 Set modw Schema version to 8 on new installs
  db/data/modw.sql
Labels: code cleanup, compatibility update

#404 Update Filters in Metric Explorer in a group instead of when each individual row is selected
  html/gui/js/AddDataPanel.js
  html/gui/js/modules/metric_explorer/MetricExplorer.js
  open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/metricExplorer.js
  open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/metricExplorer.page.js
Labels: UI, enhancement

#490 default etl config file for ease of use
  bin/acl-config
  bin/xdmod-ingestor
  classes/OpenXdmod/Migration/Version750To800/DatabasesMigration.php
  classes/OpenXdmod/Setup/AclEtl.php
  classes/OpenXdmod/Setup/AclImport.php
  classes/OpenXdmod/Setup/DatabaseSetup.php
  docs/storage.md
  tools/etl/dump_database_table_definition.sh
  tools/etl/etl_action_state_mgr.php
  tools/etl/etl_overseer.php
  tools/etl/etl_table_manager.php
Labels: code cleanup, enhancement

#491 update dump database tables script
  tools/etl/dump_database_table_definition.sh
Labels: code cleanup, compatibility update

#493 Fix doc typo chmod -> chown
  docs/install-source.md
Labels: documentation

#492 Add support for mapping column names between tables
  tools/dev/verify_table_data.php
Labels: ETL, data quality

#494 Schema changes required for federation module
  bin/xdmod-ingestor
  classes/CCR/DB/MySQLHelper.php
  classes/OpenXdmod/Shared/DatabaseHelper.php
  configuration/etl/etl.d/hpcdb-modw.json
  configuration/etl/etl_pipelines.d/jobs-xdw.json
  configuration/etl/etl_tables.d/hpcdb-modw/account.json
  configuration/etl/etl_tables.d/hpcdb-modw/allocation-breakdown.json
  configuration/etl/etl_tables.d/hpcdb-modw/allocation.json
  configuration/etl/etl_tables.d/hpcdb-modw/job_record_hpc.json
  configuration/etl/etl_tables.d/hpcdb-modw/organization.json
  configuration/etl/etl_tables.d/hpcdb-modw/person.json
  configuration/etl/etl_tables.d/hpcdb-modw/queue.json
  configuration/etl/etl_tables.d/hpcdb-modw/request.json
  configuration/etl/etl_tables.d/hpcdb-modw/resource-fact.json
  configuration/etl/etl_tables.d/hpcdb-modw/system-account.json
  configuration/etl/etl_tables.d/jobs/jobfact_hpc_aggregation.json-
  configuration/etl/etl_tables.d/xdmod/account.json
  configuration/etl/etl_tables.d/xdmod/allocation-breakdown.json
  configuration/etl/etl_tables.d/xdmod/allocation.json
  configuration/etl/etl_tables.d/xdmod/federation-blades.json
  configuration/etl/etl_tables.d/xdmod/hosts.json
  configuration/etl/etl_tables.d/xdmod/job-records.json
  configuration/etl/etl_tables.d/xdmod/job-tasks.json
  configuration/etl/etl_tables.d/xdmod/organization.json
  configuration/etl/etl_tables.d/xdmod/person.json
  configuration/etl/etl_tables.d/xdmod/queue.json
  configuration/etl/etl_tables.d/xdmod/request.json
  configuration/etl/etl_tables.d/xdmod/resource-allocated.json
  configuration/etl/etl_tables.d/xdmod/resource-fact.json
  configuration/etl/etl_tables.d/xdmod/system-account.json
  db/migrations/7.5.0-8.0.0/modw.sql
  open_xdmod/modules/xdmod/integration_tests/scripts/bootstrap.sh
Labels: code cleanup, enhancement

#424 Handle single-point timeseries plotting bug in our highcharts wrappers.
  classes/DataWarehouse/Access/Usage.php
  classes/DataWarehouse/Visualization/HighChart2.php
  classes/DataWarehouse/Visualization/HighChartTimeseries2.php
Labels: bug

#497 Add option to show columns that differ when comparing tables
  tools/dev/verify_table_data.php
Labels: data quality
