Repository ubccr/xdmod, pull requests merged in 2018-05, with the labels that each got.

#522 Update maths
  bin/xdmod-upgrade
  classes/DB/Aggregator.php
  classes/DataWarehouse/Query/Jobs/Statistics/AverageCPUHoursStatistic.php
  classes/DataWarehouse/Query/Jobs/Statistics/AverageNodeHoursStatistic.php
  classes/DataWarehouse/Query/Jobs/Statistics/AverageWaitHoursStatistic.php
  classes/DataWarehouse/Query/Jobs/Statistics/AverageWallHoursStatistic.php
  classes/DataWarehouse/Query/Jobs/Statistics/NodeUtilizationStatistic.php
  classes/DataWarehouse/Query/Jobs/Statistics/RateOfUsagePercentageStatistic.php
  classes/DataWarehouse/Query/Jobs/Statistics/SEMAverageCPUHoursStatistic.php
  classes/DataWarehouse/Query/Jobs/Statistics/SEMAverageNodeHoursStatistic.php
  classes/DataWarehouse/Query/Jobs/Statistics/SEMAverageProcessorCountStatistic.php
  classes/DataWarehouse/Query/Jobs/Statistics/SEMAverageWaitHoursStatistic.php
  classes/DataWarehouse/Query/Jobs/Statistics/SEMAverageWallHoursStatistic.php
  classes/DataWarehouse/Query/Jobs/Statistics/TotalCPUHoursStatistic.php
  classes/DataWarehouse/Query/Jobs/Statistics/TotalNodeHoursStatistic.php
  classes/DataWarehouse/Query/Jobs/Statistics/TotalWaitHoursStatistic.php
  classes/DataWarehouse/Query/Jobs/Statistics/TotalWallHoursStatistic.php
  classes/DataWarehouse/Query/Jobs/Statistics/UtilizationStatistic.php
  classes/OpenXdmod/Migration/Version750To800/DatabasesMigration.php
  configuration/etl/etl_macros.d/statistic_ratio_as_datatype_case.sql
  configuration/etl/etl_macros.d/statistic_ratio_case.sql
  open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/metricExplorer.js
  open_xdmod/modules/xdmod/integration_tests/lib/Controllers/UsageExplorerTest.php
  open_xdmod/modules/xdmod/integration_tests/scripts/xdmod-upgrade.tcl
  open_xdmod/modules/xdmod/regression_tests/lib/Controllers/UsageChartsTest.php
  open_xdmod/modules/xdmod/regression_tests/lib/Controllers/UsageExplorerTest.php
Labels: bug, code cleanup, enhancement

#532 Add support for ETL variables on command line and in config files.
  classes/ETL/Aggregator/aAggregator.php
  classes/ETL/Aggregator/pdoAggregator.php
  classes/ETL/Configuration/Configuration.php
  classes/ETL/Configuration/EtlConfiguration.php
  classes/ETL/Configuration/JsonReferenceTransformer.php
  classes/ETL/DbModel/AggregationTable.php
  classes/ETL/Ingestor/RestIngestor.php
  classes/ETL/Ingestor/StructuredFileIngestor.php
  classes/ETL/Ingestor/aIngestor.php
  classes/ETL/Ingestor/pdoIngestor.php
  classes/ETL/Loggable.php
  classes/ETL/Maintenance/ExecuteSql.php
  classes/ETL/Maintenance/VerifyDatabase.php
  classes/ETL/Utilities.php
  classes/ETL/VariableStore.php
  classes/ETL/aAction.php
  open_xdmod/modules/xdmod/tests/lib/ETL/Configuration/ConfigurationTest.php
  open_xdmod/modules/xdmod/tests/lib/ETL/Configuration/EtlConfigurationTest.php
  open_xdmod/modules/xdmod/tests/lib/ETL/VariableStore/VariableStoreTest.php
  tools/etl/etl_overseer.php
Labels: ETL

#536 Various minor bugfixes
  classes/ETL/Aggregator/pdoAggregator.php
  classes/ETL/DbModel/Entity.php
  classes/ETL/Ingestor/RestIngestor.php
  tools/etl/etl_overseer.php
Labels: ETL, bug

#511 Add Group by Job Wait Time
  classes/DataWarehouse/Query/Jobs/GroupBys/GroupByJobWaitTime.php
  classes/OpenXdmod/Migration/Version750To800/DatabasesMigration.php
  configuration/datawarehouse.json
  configuration/etl/etl_action_defs.d/jobs/hpc-aggregation.json
  configuration/etl/etl_action_defs.d/jobs/xdw/job-wait-times.json
  configuration/etl/etl_data.d/jobs/xdw/job-wait-times.json
  configuration/etl/etl_pipelines.d/jobs-xdw.json
  configuration/etl/etl_tables.d/jobs/xdw/job-wait-times.json
  configuration/etl/etl_tables.d/jobs/xdw/jobfact_by_.json
  configuration/roles.json
  open_xdmod/modules/xdmod/integration_tests/lib/Controllers/UserAdminTest.php
  open_xdmod/modules/xdmod/regression_tests/lib/Controllers/UsageExplorerTest.php
  open_xdmod/modules/xdmod/tests/lib/Xdmod/ConfigTest.php
Labels: enhancement

#537 Fix bad cut-and-paste
  classes/ETL/Maintenance/VerifyDatabase.php
Labels: bug

#538 Add pipeline name verification in EtlOverseer::verifySections()
  classes/ETL/EtlOverseer.php
  tools/etl/etl_overseer.php
Labels: ETL

#539 Stop using proc_open for calling etl, instead invoke directly
  classes/OpenXdmod/Setup/DatabaseSetup.php
Labels: bug, code cleanup

#531 Add foreign key constraints to ETL
  classes/ETL/DbModel/ForeignKeyConstraint.php
  classes/ETL/DbModel/Table.php
  open_xdmod/modules/xdmod/tests/lib/ETL/DbModel/DbModelTest.php
Labels: ETL, enhancement

#549 Allow net write timeout and chunk size as ETL variables
  classes/ETL/Ingestor/pdoIngestor.php
  classes/ETL/aOptions.php
Labels: ETL

#556 Preparation for 7.5.1 release
  CHANGELOG.md
  bin/xdmod-upgrade
  classes/OpenXdmod/Migration/Version750To751/ConfigFilesMigration.php
  classes/OpenXdmod/Migration/Version750To751/DatabasesMigration.php
  configuration/portal_settings.ini
  html/about/release_notes/xdmod.html
  open_xdmod/modules/xdmod/build.json
  open_xdmod/modules/xdmod/xdmod.spec.in
Labels: bug

#562 Fix calendar quarter calculation
  html/.eslintrc.json
  html/js_classes/DateUtilities.js
Labels: bug
