Repository ubccr/xdmod, pull requests merged in 2018-12, with the labels that each got.

#740 Fix refesh button for Metric Explorer
  html/gui/js/DurationToolbar.js
  html/gui/js/modules/metric_explorer/MetricExplorer.js
Labels: bug

#716 Add new functionality to Usage chart requests
  classes/DataWarehouse/Access/Usage.php
  open_xdmod/modules/xdmod/integration_tests/lib/Controllers/UsageExplorerTest.php
Labels: enhancement

#749 Make logrotate.d file not override global settings
  configuration/logrotate.conf
Labels: bug, enhancement

#750 Asynchronous loading of Usage tab thumbnail charts
  classes/DataWarehouse/Access/Usage.php
  html/gui/js/modules/Usage.js
Labels: enhancement

#739 Add cloud data to xdmod-shredder and xdmod-ingestor
  bin/xdmod-ingestor
  bin/xdmod-shredder
  classes/ETL/Utilities.php
  classes/OpenXdmod/DataWarehouseInitializer.php
  classes/OpenXdmod/Shredder/Genericcloud.php
  classes/OpenXdmod/Shredder/Openstack.php
  classes/OpenXdmod/Shredder/aCloud.php
  configuration/etl/etl.d/jobs_cloud_eucalyptus.json
  configuration/etl/etl.d/organizations.json
  configuration/etl/etl.d/resource_types.json
  open_xdmod/modules/xdmod/integration_tests/scripts/bootstrap.sh
  open_xdmod/modules/xdmod/tests/lib/OpenXdmod/Tests/Shredder/GenericcloudShredderTest.php
  open_xdmod/modules/xdmod/tests/lib/OpenXdmod/Tests/Shredder/OpenstackShredderTest.php
Labels: ETL, cloud

#756 Explicitly cast potentiall nulls to array for array_merge()
  classes/ETL/EtlOverseer.php
Labels: ETL, bug
