Repository ubccr/xdmod, pull requests merged in 2018-09, with the labels that each got.

#663 Fix SSO redirects
  classes/Authentication/SAML/XDSamlAuthentication.php
  classes/Rest/Controllers/AuthenticationControllerProvider.php
  html/gui/general/login.php
  html/gui/js/CCR.js
  html/index.php
  open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/SSOLogin.js
Labels: bug

#666 Move resource ingestion actions to separate pipeline
  configuration/etl/etl.d/ingest_resources.json
  configuration/etl/etl.d/jobs_cloud_common.json
  open_xdmod/modules/xdmod/integration_tests/scripts/bootstrap.sh
Labels: ETL, bug

#669 Fix typo in Eucalyptus Cloud action
  configuration/etl/etl_action_defs.d/cloud_eucalyptus/staging_event.json
Labels: bug

#673 Improve storage documentation
  docs/_includes/menu.md
  docs/storage.md
Labels: documentation

#672 Hardening Password Reset Process
  classes/OpenXdmod/Migration/Version751To800/ConfigFilesMigration.php
  classes/OpenXdmod/Setup/GeneralSetup.php
  classes/XDUser.php
  composer.json
  composer.lock
  configuration/constants.php
  configuration/portal_settings.ini
  html/controllers/user_admin/create_user.php
  html/controllers/user_admin/pass_reset.php
  html/controllers/user_auth/pass_reset.php
  html/password_reset.php
  open_xdmod/modules/xdmod/component_tests/lib/RIDTest.php
  templates/portal_settings.template
Labels: bug, code cleanup, security update

#679 Removed internal things that shouldnt be part of public release
  configuration/etl/etl_sql.d/cloud_eucalyptus/post_ingest_updates.sql
Labels: code cleanup

#680 Fix for user organization not populating
  html/controllers/user_admin/enum_institutions.php
Labels: bug, internal dashboard

#681 Updating the person organization route to accept negative numbers
  classes/Rest/Controllers/PersonControllerProvider.php
Labels: bug, internal dashboard

#683 adding correct schema file for ingesting eucalyptus raw volume information
  configuration/etl/etl.d/jobs_cloud_eucalyptus.json
  configuration/etl/etl_schemas.d/cloud/volume.schema.json
Labels: ETL, bug

#677 Fix premature end bug in etl
  etl/js/lib/dataset_processor.js
Labels: bug

#690 Fix Storage Top-Level Hierarchy Group By
  classes/DataWarehouse/Query/Storage/GroupBys/GroupByNSFDirectorate.php
Labels: bug
