Repository ubccr/xdmod, pull requests merged in 2018-02, with the labels that each got.

#370 Add `--duplicates` to list of `sacct` options
  bin/xdmod-slurm-helper
  docs/resource-manager-slurm.md
Labels: bug, documentation, enhancement

#361 Improve error message when start_day_id and/or end_day_id not present
  classes/ETL/Aggregator/pdoAggregator.php
Labels: ETL

#381 Add test for SQL parser
  classes/ETL/Loggable.php
  classes/ETL/aRdbmsDestinationAction.php
  open_xdmod/modules/xdmod/tests/lib/ETL/SqlParser/SqlParserTest.php
Labels: ETL

#382 Etl/remove warning
  classes/ETL/aAction.php
Labels: ETL

#389 Make show_guide lines button work again.
  classes/DataWarehouse/Access/Usage.php
Labels: bug

#387 Fix incorrect data filtering
  classes/DataWarehouse/Data/SimpleTimeseriesDataset.php
  classes/DataWarehouse/Query/Query.php
  open_xdmod/modules/xdmod/integration_tests/lib/Controllers/UsageExplorerTest.php
Labels: bug

#355 Update RPM spec file, add xdmod user/group
  configuration/cron.conf
  docs/configuration.md
  docs/install-source.md
  docs/upgrade.md
  open_xdmod/modules/xdmod/xdmod.spec.in
Labels: enhancement

#425 Update slurm helper script
  bin/xdmod-slurm-helper
Labels: enhancement

#375 Remove ldif
  classes/LDIF.php
  html/internal_dashboard/controllers/controller.php
  html/internal_dashboard/css/management.css
  html/internal_dashboard/js/CurrentUsers.js
  html/internal_dashboard/js/dashboard.js
Labels: internal dashboard

#434 Disable selection of federated type in new user dialog
  html/internal_dashboard/js/admin_panel/SectionExistingUsers.js
  html/internal_dashboard/js/admin_panel/SectionNewUser.js
Labels: bug, internal dashboard

#431 Only change series legend colour if the series has a legend
  classes/DataWarehouse/Visualization/HighChart2.php
Labels: bug

#427 Revert change to legend item menu location
  html/gui/js/modules/metric_explorer/MetricExplorer.js
Labels: bug

#437 Change DELETE FROM to TRUNCATE TABLE in filter generation
  classes/DB/FilterListBuilder.php
Labels: ETL, enhancement

#438 Update release notes and publications
  html/about/publications.html
  html/about/release_notes/xdmod.html
  html/about/team.html
Labels: documentation

#440 Flush data file before calling LOAD DATA INFILE
  classes/ETL/Ingestor/pdoIngestor.php
Labels: ETL, bug

#442 Update changelog 7.1 and 7.5
  CHANGELOG.md
Labels: documentation
