Repository ubccr/xdmod, pull requests merged in 2019-08, with the labels that each got.

#1002 Remove unnecessary code from Analytic Chart Panel
  html/gui/js/modules/job_viewer/AnalyticChartPanel.js
  html/gui/js/modules/job_viewer/JobPanel.js
Labels: maintenance / code quality

#1001 add notes about our docker usage and cleanup
  html/gui/general/or.png
  tests/ci/Docker/README.md
  tools/dev/format-slurm/.eslintrc.json
  tools/dev/format-slurm/README.md
  tools/dev/format-slurm/package.json
  tools/dev/format-slurm/parse.js
Labels: maintenance / code quality

#1007 Increase size of system username column
  configuration/etl/etl_tables.d/cloud_openstack/raw_event.json
  configuration/etl/etl_tables.d/common/hpcdb/system-accounts.json
  configuration/etl/etl_tables.d/jobs/xdw/system-account.json
  configuration/etl/etl_tables.d/storage/staging/usage.json
Labels: Category:General, data quality

#1003 Fix display bugs in the error message for the job viewer analytics.
  html/gui/js/modules/job_viewer/AnalyticChartPanel.js
Labels: Category:Job Viewer, bug

#985 Updating the message and button text of the popup message asking a person if they want to see the new user tour
  html/gui/js/modules/NoviceUser.js
Labels: Category:User Dashboard

#1005 Updates to Help Tips
  html/gui/js/Portlet.js
  html/gui/js/modules/HelpTip.js
Labels: Category:User Dashboard, new feature

#998 Update the default location of CS saved charts portlet.
  configuration/roles.d/summary.json
Labels: Category:User Dashboard, autodoc:ignore

#988 Add a view chart json button for developers
  html/gui/css/viewer.css
  html/gui/images/file_extension_bin.png
  html/gui/js/modules/metric_explorer/MetricExplorer.js
Labels: Category:Metric Explorer, Category:User Dashboard, new feature

#1009 update changelog links to PRs release notes do not have associa…
  CHANGELOG.md
  html/about/release_notes/xdmod.html
Labels: autodoc:ignore, release prep

#1016 Improve xdmod-ingestor documentation
  docs/ingestor.md
Labels: Category:General, documentation
