Repository ubccr/xdmod, pull requests merged in 2019-10, with the labels that each got.

#1065 update error handling
  bin/acl-config
  html/gui/js/modules/metric_explorer/MetricExplorer.js
Labels: Category:ACL, Category:Metric Explorer, enhancement

#1107 Update list of slurm job states
  classes/OpenXdmod/Shredder/Slurm.php
  docs/resource-manager-slurm.md
Labels: Category:ETL, bug

#1108 Ensure resourcetypes table is correctly populated.
  classes/OpenXdmod/DataWarehouseInitializer.php
  configuration/etl/etl.d/staging.json
  configuration/etl/etl.d/xdmod-migration-8_1_2-8_5_0.json
  configuration/etl/etl_sql.d/cloud_openstack/unknown_resource_type.sql
  tests/ci/validate.sh
Labels: bug

#1112 update integration
  .sonarcloud.properties
  shippable.yml
  sonar-project.properties
Labels: Category:Infrastructure, autodoc:ignore, qa / testing

#1111 update release notes and changelogs
  CHANGELOG.md
  html/about/release_notes/xdmod.html
  open_xdmod/modules/xdmod/xdmod.spec.in
Labels: autodoc:ignore, release prep

#1113 Remove beta label from storage realm
  docs/_data/toc.yml
  docs/storage.md
Labels: Category:General, autodoc:ignore, documentation, release prep

#1114 Update upgrade and support documentation
  docs/configuration.md
  docs/support.md
  docs/upgrade.md
Labels: Category:General, autodoc:ignore, documentation, release prep

#1120 Store warehouse export retention value as string
  classes/DataWarehouse/Export/QueryHandler.php
  configuration/portal_settings.ini
  templates/portal_settings.template
Labels: Category:Data Warehouse Export, autodoc:ignore, bug

#1121 Update release date
  CHANGELOG.md
  docs/support.md
  html/about/release_notes/xdmod.html
  open_xdmod/modules/xdmod/xdmod.spec.in
Labels: autodoc:ignore, release prep

#1122 Version sync 8.5 -> 8.6
  CHANGELOG.md
  bin/acl-config
  bin/xdmod-ingestor
  bin/xdmod-update-resource-specs
  classes/DataWarehouse/Export/QueryHandler.php
  classes/OpenXdmod/DataWarehouseInitializer.php
  configuration/etl/etl.d/staging.json
  configuration/etl/etl_sql.d/cloud_openstack/unknown_resource_type.sql
  configuration/portal_settings.ini
  docs/_data/toc.yml
  docs/configuration.md
  docs/storage.md
  docs/support.md
  docs/upgrade.md
  html/about/release_notes/xdmod.html
  html/controllers/ui_data/summary3.php
  html/gui/js/modules/job_viewer/SearchPanel.js
  open_xdmod/modules/xdmod/xdmod.spec.in
  templates/portal_settings.template
  tests/ci/validate.sh
Labels: autodoc:ignore, version sync

#1123 Update docker image and related changes
  Dockerfile
  bin/xdmod-upgrade
  classes/OpenXdmod/Migration/Version812To850/ConfigFilesMigration.php
  classes/OpenXdmod/Migration/Version812To860/ConfigFilesMigration.php
  classes/OpenXdmod/Migration/Version812To860/DatabasesMigration.php
  classes/OpenXdmod/Migration/Version850To860/ConfigFilesMigration.php
  configuration/etl/etl.d/xdmod-migration-8_1_2-8_6_0.json
  configuration/etl/etl.d/xdmod-migration-8_5_0-8_6_0.json
  tests/ci/Docker/Dockerfile
  tests/ci/Docker/Dockerfile.centos7:xdmod-base
  tests/ci/Docker/assets/copy-caches.sh
  tests/ci/Docker/assets/vimrc
  tests/ci/scripts/xdmod-upgrade-jobs.tcl
  tests/ci/scripts/xdmod-upgrade.tcl
Labels: autodoc:ignore, experiment, qa / testing

#1124 Revert changes to roadmap in #1031 now that trello fixed their…
  classes/OpenXdmod/Migration/Version850To900/ConfigFilesMigration.php
  configuration/portal_settings.ini
  tests/ui/test/specs/xdmod/about.page.js
Labels: Category:General

#1128 remove file that is no longer needed
  classes/OpenSSL.php
Labels: autodoc:ignore, maintenance / code quality

#1130 Fix configuration settings for configuration class.
  classes/OpenXdmod/DataWarehouseInitializer.php
Labels: Category:General, bug

#1132 Release preparations for 8.5.1
  .editorconfig
  CHANGELOG.md
  bin/xdmod-upgrade
  classes/OpenXdmod/Migration/Version850To851/ConfigFilesMigration.php
  configuration/portal_settings.ini
  docs/_config.yml
  docs/upgrade.md
  html/about/release_notes/xdmod.html
  open_xdmod/modules/xdmod/build.json
  open_xdmod/modules/xdmod/xdmod.spec.in
Labels: autodoc:ignore, release prep

#1135 Version sync 8.5 -> 8.6
  .editorconfig
  CHANGELOG.md
  bin/xdmod-upgrade
  classes/OpenXdmod/DataWarehouseInitializer.php
  classes/OpenXdmod/Migration/Version850To851/ConfigFilesMigration.php
  classes/OpenXdmod/Migration/Version851To860/ConfigFilesMigration.php
  docs/_config.yml
  docs/upgrade.md
  html/about/release_notes/xdmod.html
  open_xdmod/modules/xdmod/xdmod.spec.in
Labels: autodoc:ignore, version sync

#1138 Version sync 8.6 -> 9.0
  .editorconfig
  CHANGELOG.md
  Dockerfile
  bin/xdmod-upgrade
  classes/OpenXdmod/DataWarehouseInitializer.php
  classes/OpenXdmod/Migration/Version850To851/ConfigFilesMigration.php
  classes/OpenXdmod/Migration/Version851To900/ConfigFilesMigration.php
  docs/_config.yml
  docs/upgrade.md
  html/about/release_notes/xdmod.html
  open_xdmod/modules/xdmod/xdmod.spec.in
  tests/ci/Docker/Dockerfile
Labels: autodoc:ignore, version sync
