Repository ubccr/xdmod, pull requests merged in 2019-04, with the labels that each got.

#881 Processor Buckets documentation update
  configuration/processor_buckets.json
  docs/configuration.md
  open_xdmod/modules/xdmod/build.json
Labels: Category:ETL, documentation

#882 Improve storage aggregation
  bin/xdmod-ingestor
  classes/OpenXdmod/DataWarehouseInitializer.php
  configuration/etl/etl_action_defs.d/storage/xdw/storagefact.aggregation.json
  docs/ingestor.md
  docs/shredder.md
  docs/storage.md
  open_xdmod/modules/xdmod/integration_tests/scripts/bootstrap.sh
  open_xdmod/modules/xdmod/regression_tests/post_ingest_test.sh
  tests/artifacts/xdmod-test-artifacts/xdmod/referencedata/storage_upgrade/recex/data-2019-01-06.json
  tests/artifacts/xdmod-test-artifacts/xdmod/referencedata/storage_upgrade/torx/projects-2019-01-06.json
  tests/artifacts/xdmod-test-artifacts/xdmod/referencedata/storage_upgrade/torx/scratch-2019-01-06.json
Labels: Category:ETL, Category:Storage, documentation, enhancement

#888 Updated release notes for 8.1
  CHANGELOG.md
  html/about/release_notes/xdmod.html
  open_xdmod/modules/xdmod/xdmod.spec.in
Labels: autodoc:ignore, documentation

#891 Update upgrade guide for 8.1.0
  docs/upgrade.md
Labels: Category:General, autodoc:ignore, documentation, release prep

#892 Remove legacy files
  configuration/etl/etl.d/xdmod-migration-7_5_1-8_0_0.json
Labels: Category:ETL, autodoc:ignore, maintenance / code quality, release prep

#894 Update SAML ocs to be a bit more clear
  docs/simpleSAMLphp.md
Labels: autodoc:ignore, documentation

#898 Update dates for release
  CHANGELOG.md
  docs/support.md
  html/about/release_notes/xdmod.html
  open_xdmod/modules/xdmod/xdmod.spec.in
Labels: autodoc:ignore, release prep

#899 Update to 8.5 and 8.1 based shippable
  Dockerfile
  bin/xdmod-upgrade
  classes/OpenXdmod/Migration/Version800To810/ConfigFilesMigration.php
  classes/OpenXdmod/Migration/Version800To810/DatabasesMigration.php
  configuration/portal_settings.ini
  open_xdmod/modules/xdmod/automated_tests/test/specs/xdmod/reportGenerator.page.js
  open_xdmod/modules/xdmod/build.json
  open_xdmod/modules/xdmod/integration_tests/email-subject-test.sh
  open_xdmod/modules/xdmod/integration_tests/scripts/bootstrap.sh
  open_xdmod/modules/xdmod/integration_tests/scripts/xdmod-upgrade-add-cloud-resource.tcl
  open_xdmod/modules/xdmod/integration_tests/scripts/xdmod-upgrade-add-storage-resources.tcl
  open_xdmod/modules/xdmod/tests/lib/OpenXdmod/Tests/Migration/Version800To810/DatabasesMigrationTest.php
  open_xdmod/modules/xdmod/xdmod.spec.in
  shippable.yml
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/images/expected.json
  tests/ci/scripts/create_xdmod_users.php
Labels: autodoc:ignore

#900 Add Show raw data support for the Jobs Realm
  classes/DataWarehouse/Query/Jobs/JobDataset.php
  classes/DataWarehouse/Query/Jobs/JobMetadata.php
  classes/DataWarehouse/Query/Jobs/RawData.php
  classes/OpenXdmod/Migration/Version810To850/DatabasesMigration.php
  configuration/etl/etl.d/xdmod-migration-8_1_0-8_5_0.json
  configuration/etl/etl_action_defs.d/jobs/hpc-aggregation-day.json
  configuration/etl/etl_action_defs.d/jobs/xdw/jobfact_by_day_joblist.json
  configuration/etl/etl_pipelines.d/jobs-xdw.json
  configuration/etl/etl_tables.d/jobs/xdw/jobfact_by_day.json
  configuration/etl/etl_tables.d/jobs/xdw/jobfact_by_day_joblist.json
  configuration/rawstatistics.d/20_jobs.json
  configuration/roles.json
  open_xdmod/modules/xdmod/build.json
  open_xdmod/modules/xdmod/integration_tests/lib/Rest/JobViewerTest.php
  open_xdmod/modules/xdmod/integration_tests/scripts/xdmod-upgrade.tcl
  tests/artifacts/xdmod-test-artifacts/xdmod/user_admin/output/get_tabs-admin.json
  tests/artifacts/xdmod-test-artifacts/xdmod/user_admin/output/get_tabs-centerdirector.json
  tests/artifacts/xdmod-test-artifacts/xdmod/user_admin/output/get_tabs-centerstaff.json
  tests/artifacts/xdmod-test-artifacts/xdmod/user_admin/output/get_tabs-normaluser.json
  tests/artifacts/xdmod-test-artifacts/xdmod/user_admin/output/get_tabs-principal.json
  tests/artifacts/xdmod-test-artifacts/xdmod/user_admin/output/get_tabs-test.cd.one-center.json
  tests/artifacts/xdmod-test-artifacts/xdmod/user_admin/output/get_tabs-test.cs.one-center.json
  tests/artifacts/xdmod-test-artifacts/xdmod/user_admin/output/get_tabs-test.normal-user.json
  tests/artifacts/xdmod-test-artifacts/xdmod/user_admin/output/get_tabs-test.pi.json
  tests/artifacts/xdmod-test-artifacts/xdmod/user_admin/output/get_tabs-test.usr_dev.json
  tests/artifacts/xdmod-test-artifacts/xdmod/user_admin/output/get_tabs-test.usr_mgr.json
  tests/artifacts/xdmod-test-artifacts/xdmod/user_admin/output/get_tabs-test.usr_mgr_dev.json
Labels: Category:Job Viewer
