Repository ubccr/xdmod, pull requests merged in 2019-09, with the labels that each got.

#1019 Help Menu - Remove YouTube, Add icon to Tour
  html/gui/css/viewer.css
  html/gui/images/edit_path_16.png
  html/gui/images/youtube_16.png
  html/gui/js/CCR.js
  tests/ui/test/specs/xdmod/mainToolbar.page.js
Labels: Category:General

#1020 Add data warehouse export documentation
  docs/_data/toc.yml
  docs/dw-export.md
Labels: Category:Data Warehouse Export, autodoc:ignore, documentation

#1023 Fix sso login test diff path
  tests/ci/bootstrap.sh
Labels: Category:General, autodoc:ignore, bug

#1015 JobPortlet: Ensure missing CPU data is displayed correctly
  html/gui/css/JobComponent.css
  html/gui/js/modules/dashboard/JobComponent.js
Labels: Category:User Dashboard, autodoc:ignore

#1029 Add file locking to Data Warehouse Export script
  background_scripts/batch_export_manager.php
Labels: Category:Data Warehouse Export, autodoc:ignore, enhancement

#1030 Remove data files for deleted export requests
  classes/DataWarehouse/Export/BatchProcessor.php
  classes/DataWarehouse/Export/FileManager.php
  classes/DataWarehouse/Export/QueryHandler.php
Labels: Category:Data Warehouse Export, autodoc:ignore, bug

#1038 Update profile editor for renamed rest interface.
  html/gui/js/profile_editor/ProfileEditor.js
Labels: autodoc:ignore

#1042 Update dashboard chart display algorithm
  classes/Rest/Controllers/DashboardControllerProvider.php
  configuration/roles.d/dashboard.json
  docs/dashboard.md
Labels: Category:User Dashboard, autodoc:ignore

#1044 Add help images for core dashboard components
  configuration/assets.json
  html/gui/css/ChartComponent.css
  html/gui/images/help/chart-component.svg
  html/gui/images/help/chartsreports-component.svg
  html/gui/images/help/job-component.svg
  html/gui/images/help/job-multi-component.svg
  html/gui/js/Portlet.js
  html/gui/js/modules/dashboard/ChartComponent.js
  html/gui/js/modules/dashboard/JobComponent.js
  html/gui/js/modules/dashboard/SavedChartsReportsComponent.js
Labels: autodoc:ignore

#1046 Fix metric explorer metric and dimension display bug.
  html/gui/js/CCR.js
Labels: Category:Metric Explorer, bug

#1053 Fix Usage UI Regression
  html/gui/js/CCR.js
  html/gui/js/modules/Usage.js
Labels: autodoc:ignore

#1047 Add ability to hide realm from the metric catalog
  classes/DataWarehouse.php
  html/controllers/metric_explorer/get_dw_descripter.php
Labels: Category:User Dashboard

#1061 Check for alternate timezone field
  classes/DataWarehouse/Data/RawDataset.php
Labels: Category:Job Viewer, autodoc:ignore, bug

#1063 Data warehouse export tests and bug fix
  classes/DataWarehouse/Export/BatchProcessor.php
  classes/DataWarehouse/Export/FileManager.php
  tests/artifacts/xdmod/component/export/file_manager/input/export-request-ids.json
  tests/artifacts/xdmod/component/export/file_manager/input/export-requests.json
  tests/artifacts/xdmod/component/export/file_manager/output/1.csv
  tests/artifacts/xdmod/component/export/file_manager/output/2.json
  tests/artifacts/xdmod/unit/data_warehouse/export/file_writer/csv/write_records.json
  tests/artifacts/xdmod/unit/data_warehouse/export/file_writer/factory/create_file_writer.json
  tests/artifacts/xdmod/unit/data_warehouse/export/file_writer/json/write_records.json
  tests/artifacts/xdmod/unit/data_warehouse/export/file_writer/null/write_records.json
  tests/component/lib/Export/BatchProcessTest.php
  tests/component/lib/Export/FileManagerTest.php
  tests/integration/lib/Rest/WarehouseExportControllerTest.php
  tests/unit/lib/DataWarehouse/Export/CsvFileWriterTest.php
  tests/unit/lib/DataWarehouse/Export/FileWriterFactoryTest.php
  tests/unit/lib/DataWarehouse/Export/JsonFileWriterTest.php
  tests/unit/lib/DataWarehouse/Export/NullFileWriterTest.php
Labels: Category:Data Warehouse Export, autodoc:ignore, bug, qa / testing

#1066 Document required file name extension
  docs/storage.md
Labels: Category:Storage, autodoc:ignore, documentation

#1068 Fixing an infinite loop when discarding user changes
  html/internal_dashboard/js/admin_panel/SectionExistingUsers.js
  tests/ui/test/specs/xdmod/internalDashboard.js
  tests/ui/test/specs/xdmod/internalDashboard.page.js
Labels: Category:Internal Dashboard, bug

#1073 Ensure Jobs realm data access class provides required fields
  classes/DataWarehouse/Query/Jobs/RawData.php
  tests/integration/lib/Rest/JobViewerTest.php
Labels: Category:User Dashboard, autodoc:ignore, bug

#1072 Replace previous year with 1 year
  configuration/roles.d/dashboard.json
  html/gui/js/modules/dashboard/ReportThumbnailsComponent.js
Labels: autodoc:ignore, bug

#1075 Move where
  configuration/etl/etl_action_defs.d/xdb/report-template-charts.json
  configuration/etl/etl_action_defs.d/xdb/report-templates.json
Labels: autodoc:ignore, bug
