Repository ubccr/xdmod, pull requests merged in 2019-03, with the labels that each got.

#838 Prevent null usernames being added when ingestion cloud data
  configuration/etl/etl_action_defs.d/cloud_generic/union_user_pi_resource.json
  configuration/etl/etl_action_defs.d/cloud_openstack/union_user_pi_resource.json
Labels: bug, cloud

#844 removing event_id from the event table primary key
  configuration/etl/etl_tables.d/cloud_common/event.json
Labels: bug, cloud

#845 Changing where staging action gets user id from for cloud data
  configuration/etl/etl.d/jobs_cloud_generic.json
  configuration/etl/etl.d/jobs_cloud_openstack.json
  configuration/etl/etl_action_defs.d/cloud_generic/staging_event.json
  configuration/etl/etl_action_defs.d/cloud_openstack/staging_event.json
Labels: bug, cloud

#847 Updating linker.php
  composer.json
  composer.lock
  configuration/linker.json
  configuration/linker.php
Labels: bug

#818 Update config read order
  background_scripts/update_check.php
  bin/acl-config
  bin/xdmod-admin
  bin/xdmod-setup
  classes/Configuration/Configuration.php
  classes/Configuration/XdmodConfiguration.php
  classes/DB/FilterListBuilder.php
  classes/DataWarehouse.php
  classes/DataWarehouse/Query/Query.php
  classes/DataWarehouse/Query/TimeAggregationUnit.php
  classes/DataWarehouse/QueryBuilder.php
  classes/Models/Services/Parameters.php
  classes/OpenXdmod/Assets.php
  classes/OpenXdmod/Setup/MainMenu.php
  classes/OpenXdmod/Shredder.php
  classes/Rest/Controllers/WarehouseControllerProvider.php
  classes/Rest/XdmodApplicationFactory.php
  classes/User/Roles.php
  configuration/linker.php
  configuration/rawstatistics.json
  html/index.php
  html/internal_dashboard/controllers/dashboard/get_menu.php
  html/internal_dashboard/controllers/summary/get_config.php
  html/internal_dashboard/controllers/summary/get_portlets.php
  open_xdmod/modules/xdmod/tests/lib/ETL/Configuration/EtlConfigurationTest.php
  tests/artifacts/xdmod-test-artifacts/xdmod/configuration/input/read_order.json
  tests/artifacts/xdmod-test-artifacts/xdmod/configuration/input/roles.d/read_order/0.json
  tests/artifacts/xdmod-test-artifacts/xdmod/configuration/input/roles.d/read_order/a.json
  tests/artifacts/xdmod-test-artifacts/xdmod/configuration/input/roles.d/read_order/z.json
  tests/artifacts/xdmod-test-artifacts/xdmod/configuration/input/xdmod_config.json
  tests/artifacts/xdmod-test-artifacts/xdmod/configuration/output/roles-read_order.json
Labels: enhancement

#849 Addressing problem found by @jtpalmer
  composer.json
  configuration/linker.json
Labels: bug

#852 Fix regression from #818
  classes/Rest/Controllers/WarehouseControllerProvider.php
Labels: bug

#860 Change cloud person username fields to be not null
  configuration/etl/etl_tables.d/cloud_generic/staging_event.json
  configuration/etl/etl_tables.d/cloud_openstack/staging_event.json
Labels: bug, cloud

#773 Remove Roles Classes
  classes/User/AuthenticatedRole.php
  classes/User/Roles/CenterDirectorRole.php
  classes/User/Roles/CenterStaffRole.php
  classes/User/Roles/DeveloperRole.php
  classes/User/Roles/ManagerRole.php
  classes/User/Roles/PrincipalInvestigatorRole.php
  classes/User/Roles/PublicRole.php
  classes/User/Roles/UserRole.php
  open_xdmod/modules/xdmod/component_tests/lib/Roles/CenterDirectorRoleTest.php
  open_xdmod/modules/xdmod/component_tests/lib/Roles/CenterStaffRoleTest.php
  open_xdmod/modules/xdmod/component_tests/lib/XDUserTest.php
  tests/artifacts/xdmod-test-artifacts/xdmod/acls/output/center_director_get_active_center.json
  tests/artifacts/xdmod-test-artifacts/xdmod/acls/output/center_director_get_identifier.json
  tests/artifacts/xdmod-test-artifacts/xdmod/roles/input/get_active_center.json
  tests/artifacts/xdmod-test-artifacts/xdmod/roles/output/get_identifer_absolute.json
Labels: code cleanup

#799 Remove `UserRoles` Usage
  classes/XDStatistics.php
  classes/XDUser.php
  configuration/etl/etl.d/xdb.json
  configuration/etl/etl_sql.d/acls/xdmod/create_public_user.sql
  configuration/etl/etl_sql.d/acls/xdmod/user_acls.sql
  configuration/etl/etl_tables.d/xdb/user-roles.json
  html/internal_dashboard/controllers/controller.php
  open_xdmod/modules/xdmod/integration_tests/lib/Controllers/UserAdminTest.php
Labels: code cleanup

#801 Remove `Roles` Usage
  bin/acl-config
  classes/XDReportManager.php
  classes/XDUser.php
  configuration/etl/etl.d/acls-import.json
  configuration/etl/etl.d/acls-xdmod-management.json
  configuration/etl/etl_action_defs.d/acls/report-template-acls-staging.json
  configuration/etl/etl_action_defs.d/acls/report-template-acls.json
  configuration/etl/etl_data.d/acls/report-template-acls-staging.json
  configuration/etl/etl_tables.d/acls/report-template-acls-staging.json
  configuration/etl/etl_tables.d/acls/report_template_acls.json
  libraries/roles.php
  open_xdmod/modules/xdmod/component_tests/lib/XDUserTest.php
  tests/artifacts/xdmod-test-artifacts/xdmod-xsede/acls/input/enum_center_director_sites.json
  tests/artifacts/xdmod-test-artifacts/xdmod-xsede/acls/input/enum_center_staff_sites.json
  tests/artifacts/xdmod-test-artifacts/xdmod-xsede/acls/input/get_primary_organization.json
  tests/artifacts/xdmod-test-artifacts/xdmod-xsede/acls/input/set_organization_valid.json
  tests/artifacts/xdmod-test-artifacts/xdmod-xsede/acls/output/enum_center_director_sites-Public User.json
  tests/artifacts/xdmod-test-artifacts/xdmod-xsede/acls/output/enum_center_director_sites-centerdirector.json
  tests/artifacts/xdmod-test-artifacts/xdmod-xsede/acls/output/enum_center_director_sites-centerstaff.json
  tests/artifacts/xdmod-test-artifacts/xdmod-xsede/acls/output/enum_center_director_sites-normaluser.json
  tests/artifacts/xdmod-test-artifacts/xdmod-xsede/acls/output/enum_center_director_sites-principal.json
  tests/artifacts/xdmod-test-artifacts/xdmod-xsede/acls/output/enum_center_staff_sites-Public User.json
  tests/artifacts/xdmod-test-artifacts/xdmod-xsede/acls/output/enum_center_staff_sites-centerdirector.json
  tests/artifacts/xdmod-test-artifacts/xdmod-xsede/acls/output/enum_center_staff_sites-centerstaff.json
  tests/artifacts/xdmod-test-artifacts/xdmod-xsede/acls/output/enum_center_staff_sites-normaluser.json
  tests/artifacts/xdmod-test-artifacts/xdmod-xsede/acls/output/enum_center_staff_sites-principal.json
  tests/artifacts/xdmod-test-artifacts/xdmod-xsede/acls/output/get_organization_collection-Public User.json
  tests/artifacts/xdmod-test-artifacts/xdmod-xsede/acls/output/get_organization_collection-centerdirector.json
  tests/artifacts/xdmod-test-artifacts/xdmod-xsede/acls/output/get_organization_collection-centerstaff.json
  tests/artifacts/xdmod-test-artifacts/xdmod-xsede/acls/output/get_organization_collection-normaluser.json
  tests/artifacts/xdmod-test-artifacts/xdmod-xsede/acls/output/get_organization_collection-principal.json
  tests/artifacts/xdmod-test-artifacts/xdmod-xsede/acls/output/get_primary_organization-Public User.json
  tests/artifacts/xdmod-test-artifacts/xdmod-xsede/acls/output/get_primary_organization-centerstaff.json
  tests/artifacts/xdmod-test-artifacts/xdmod-xsede/acls/output/get_primary_organization-normaluser.json
  tests/artifacts/xdmod-test-artifacts/xdmod-xsede/acls/output/get_primary_organization-principal.json
  tests/artifacts/xdmod-test-artifacts/xdmod-xsede/roles/input/get_active_center.json
Labels: code cleanup

#861 Change order columns in autoincrement keys for cloud tables
  classes/OpenXdmod/Shredder/aCloud.php
  configuration/etl/etl_action_defs.d/cloud_common/initialize_unknown_dimension_values.json
  configuration/etl/etl_tables.d/cloud_common/account.json
  configuration/etl/etl_tables.d/cloud_common/asset.json
  configuration/etl/etl_tables.d/cloud_common/avail_zone.json
  configuration/etl/etl_tables.d/cloud_common/host.json
  configuration/etl/etl_tables.d/cloud_common/image.json
  configuration/etl/etl_tables.d/cloud_common/instance.json
  configuration/etl/etl_tables.d/cloud_common/instance_type.json
  configuration/etl/etl_tables.d/cloud_common/region.json
  open_xdmod/modules/xdmod/integration_tests/lib/Controllers/UsageExplorerTest.php
Labels: cloud

#864 Ignore having no XDMoD rpms to remove in bootstrap on fresh install
  open_xdmod/modules/xdmod/integration_tests/scripts/bootstrap.sh
Labels: bug

#863 Update GroupBys In Cloud Aggregate Table
  configuration/etl/etl_action_defs.d/cloud_common/cloud_metrics_aggregation.json
  configuration/etl/etl_tables.d/cloud_common/cloudfact_by_.json
Labels: bug

#865 Remove unused fields from cloud fact tables
  configuration/etl/etl_action_defs.d/cloud_common/cloud_metrics_aggregation.json
  configuration/etl/etl_action_defs.d/cloud_common/cloud_transient.json
  configuration/etl/etl_tables.d/cloud_common/cloud_transient.json
  configuration/etl/etl_tables.d/cloud_common/cloudfact_by_.json
Labels: bug

#866 Change staging table to use 1 as unknown id instead of -1
  configuration/etl/etl_action_defs.d/cloud_generic/instance.json
  configuration/etl/etl_action_defs.d/cloud_generic/staging_event.json
  configuration/etl/etl_action_defs.d/cloud_openstack/instance.json
  configuration/etl/etl_action_defs.d/cloud_openstack/staging_event.json
  configuration/etl/etl_tables.d/cloud_common/account.json
  configuration/etl/etl_tables.d/cloud_common/instance.json
  configuration/etl/etl_tables.d/cloud_generic/staging_event.json
  configuration/etl/etl_tables.d/cloud_openstack/staging_event.json
Labels: cloud

#867 Run usage charts regression tests
  open_xdmod/modules/xdmod/regression_tests/runtests.sh
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/images/expected.json
Labels: bug, qa, tests

#868 removing table definitions and references for tables that are not used
  configuration/etl/etl.d/jobs_cloud_common.json
  configuration/etl/etl_action_defs.d/cloud_common/initialize_unknown_dimension_values.json
  configuration/etl/etl_tables.d/cloud_common/avail_zone.json
  configuration/etl/etl_tables.d/cloud_common/cloud_resource_metadata.json
  configuration/etl/etl_tables.d/cloud_common/job_record_event.json
  configuration/etl/etl_tables.d/cloud_common/region.json
Labels: cloud, code cleanup

#869 Rename "cloud_events_transient" table
  configuration/etl/etl.d/cloud_state_machine.json
  configuration/etl/etl_action_defs.d/cloud_common/cloud_metrics_aggregation.json
  configuration/etl/etl_action_defs.d/cloud_common/session_records.json
  configuration/etl/etl_tables.d/cloud_common/session_records.json
  tests/artifacts/xdmod-test-artifacts/xdmod/etlv2/configuration/input/etl_8.0.0.d/cloud_state_test_config.json
Labels: code cleanup

#874 Adding cloud raw tables to cloud manage tables action
  configuration/etl/etl.d/jobs_cloud_common.json
Labels: bug, cloud

#872 Add email subject prefix
  classes/CCR/MailWrapper.php
  classes/OpenXdmod/Migration/Version800To810/ConfigFilesMigration.php
  configuration/portal_settings.ini
  open_xdmod/modules/xdmod/integration_tests/email-subject-test.sh
  open_xdmod/modules/xdmod/integration_tests/runtests.sh
  templates/portal_settings.template
Labels: enhancement

#870 allow for timing to be recorded and fix up runtests
  open_xdmod/modules/xdmod/regression_tests/lib/Controllers/UsageExplorerTest.php
  open_xdmod/modules/xdmod/regression_tests/runtests.sh
Labels: code cleanup, data quality, tests

#873 Add Federated to About
  html/about/federated.php
  html/about/images/federated-diagram-1.gif
  html/gui/js/modules/About.js
Labels: documentation

#876 Update broken url and change wording of supported software
  docs/faq.md
Labels: Category:General, documentation

#879 Fix invalid comparison
  classes/OpenXdmod/Setup/ResourcesSetup.php
Labels: Category:General, autodoc:ignore, bug

#877 Timestamps for Session Records are now non-nullable
  configuration/etl/etl_tables.d/cloud_common/session_records.json
Labels: Category:Cloud, bug

#875 Updated Cloud Documentation for 8.1 Release
  docs/cloud.md
  docs/ingestor.md
  docs/shredder.md
Labels: Category:Cloud, documentation
