Repository ubccr/xdmod, pull requests merged in 2019-02, with the labels that each got.

#793 Throw Exception if lockfile could not be obtained
  classes/ETL/LockFile.php
Labels: bug

#795 Update Indices
  configuration/etl/etl_tables.d/jobs/xdw/resource-fact.json
Labels: ETL, bug

#802 Explictly check for stdClass in variable initializer
  classes/ETL/VariableStore.php
Labels: bug

#803 add some summary charts for the cloud realm
  templates/roles.d/cloud.json
Labels: enhancement

#789 Configuration Code - Consolidation
  bin/acl-config
  classes/Configuration/Configuration.php
  classes/Configuration/ModuleConfiguration.php
  classes/Configuration/ModuleTransformer.php
  classes/Configuration/XdmodConfiguration.php
  open_xdmod/modules/xdmod/tests/lib/ETL/Configuration/EtlConfigurationTest.php
  tests/artifacts/xdmod-test-artifacts/xdmod/configuration/input/datawarehouse.json
  tests/artifacts/xdmod-test-artifacts/xdmod/configuration/input/module_configuration.json
  tests/artifacts/xdmod-test-artifacts/xdmod/configuration/input/multi_extends.json
  tests/artifacts/xdmod-test-artifacts/xdmod/configuration/input/roles-multi_extends_chain.json
  tests/artifacts/xdmod-test-artifacts/xdmod/configuration/input/roles.d/module_configuration/cloud.json
  tests/artifacts/xdmod-test-artifacts/xdmod/configuration/input/roles.d/module_configuration/new_module.json
  tests/artifacts/xdmod-test-artifacts/xdmod/configuration/input/roles.d/multi_extends_chain/cloud.json
  tests/artifacts/xdmod-test-artifacts/xdmod/configuration/input/roles.d/xdmod_config/cloud.json
  tests/artifacts/xdmod-test-artifacts/xdmod/configuration/input/roles.json
  tests/artifacts/xdmod-test-artifacts/xdmod/configuration/input/xdmod_config.json
  tests/artifacts/xdmod-test-artifacts/xdmod/configuration/output/module_config_roles-new_module.json
  tests/artifacts/xdmod-test-artifacts/xdmod/configuration/output/module_config_roles-xdmod.json
  tests/artifacts/xdmod-test-artifacts/xdmod/configuration/output/roles-multi_extends_chain.json
  tests/artifacts/xdmod-test-artifacts/xdmod/configuration/output/xdmod_config_datawarehouse.json
  tests/artifacts/xdmod-test-artifacts/xdmod/configuration/output/xdmod_config_roles.json
  tests/artifacts/xdmod-test-artifacts/xdmod/configuration/output/xdmod_config_roles.json.json
Labels: code cleanup, enhancement

#804 Update with some of the options that are avalbile
  bin/xdmod-ingestor
Labels: documentation, enhancement

#807 Improve resiliency of ETLv2 manage tables
  classes/ETL/DbModel/Column.php
  classes/ETL/DbModel/Entity.php
  classes/ETL/DbModel/Index.php
  classes/ETL/DbModel/NamedEntity.php
  classes/ETL/DbModel/Query.php
  classes/ETL/DbModel/SchemaEntity.php
  classes/ETL/DbModel/Table.php
  classes/ETL/DbModel/Trigger.php
  classes/ETL/Maintenance/ManageTables.php
  classes/ETL/VariableStore.php
  classes/ETL/aAction.php
  open_xdmod/modules/xdmod/component_tests/lib/ETL/BaseEtlTest.php
  open_xdmod/modules/xdmod/component_tests/lib/ETL/DbModel/DbModelTest.php
  open_xdmod/modules/xdmod/tests/lib/ETL/DbModel/DbModelTest.php
  tests/artifacts/xdmod-test-artifacts/xdmod/etlv2/configuration/input/etl_8.0.0.d/db_model_test.json
  tests/artifacts/xdmod-test-artifacts/xdmod/etlv2/configuration/input/etl_tables_8.0.0.d/db_model_baseline_table.json
  tests/artifacts/xdmod-test-artifacts/xdmod/etlv2/configuration/input/etl_tables_8.0.0.d/db_model_normalize_table_definitions.json
  tests/artifacts/xdmod-test-artifacts/xdmod/etlv2/configuration/input/etl_tables_8.0.0.d/db_model_test_1.json
  tests/artifacts/xdmod-test-artifacts/xdmod/etlv2/configuration/input/etl_tables_8.0.0.d/db_model_test_2.json
  tests/artifacts/xdmod-test-artifacts/xdmod/etlv2/configuration/input/etl_tables_8.0.0.d/db_model_test_3.json
  tests/artifacts/xdmod-test-artifacts/xdmod/etlv2/configuration/input/etl_tables_8.0.0.d/db_model_test_4.json
  tests/artifacts/xdmod-test-artifacts/xdmod/etlv2/configuration/output/create_table.json
  tests/artifacts/xdmod-test-artifacts/xdmod/etlv2/configuration/output/modify_table.json
  tests/artifacts/xdmod-test-artifacts/xdmod/etlv2/configuration/output/normalized_table_definition.json
  tests/artifacts/xdmod-test-artifacts/xdmod/etlv2/configuration/output/rename_and_reorder_table_column.json
  tests/artifacts/xdmod-test-artifacts/xdmod/etlv2/configuration/output/reorder_table_columns.json
  tests/artifacts/xdmod-test-artifacts/xdmod/etlv2/dbmodel/output/alter_table_manually-charset.sql
  tests/artifacts/xdmod-test-artifacts/xdmod/etlv2/dbmodel/output/resourceallocationfact_by.aggregation.sql
  tests/artifacts/xdmod-test-artifacts/xdmod/etlv2/dbmodel/output/table_def-charset.sql
Labels: ETL, enhancement

#810 Fix path to exception in TimeAggregationUnit::factory
  classes/DataWarehouse/Query/TimeAggregationUnit.php
  open_xdmod/modules/xdmod/tests/lib/DataWarehouse/Query/TimeAggregationUnitTest.php
Labels: bug

#812 Test artifact cleanup
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/configuration/cloud_avg_disk_reserved/aggregate-Day-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/configuration/cloud_avg_disk_reserved/aggregate-Month-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/configuration/cloud_avg_disk_reserved/aggregate-Quarter-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/configuration/cloud_avg_disk_reserved/aggregate-Year-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/configuration/cloud_avg_disk_reserved/timeseries-Day-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/configuration/cloud_avg_disk_reserved/timeseries-Month-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/configuration/cloud_avg_disk_reserved/timeseries-Quarter-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/configuration/cloud_avg_disk_reserved/timeseries-Year-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/none/cloud_avg_disk_reserved/aggregate-Day-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/none/cloud_avg_disk_reserved/aggregate-Month-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/none/cloud_avg_disk_reserved/aggregate-Quarter-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/none/cloud_avg_disk_reserved/aggregate-Year-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/none/cloud_avg_disk_reserved/timeseries-Day-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/none/cloud_avg_disk_reserved/timeseries-Month-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/none/cloud_avg_disk_reserved/timeseries-Quarter-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/none/cloud_avg_disk_reserved/timeseries-Year-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/project/cloud_avg_disk_reserved/aggregate-Day-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/project/cloud_avg_disk_reserved/aggregate-Month-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/project/cloud_avg_disk_reserved/aggregate-Quarter-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/project/cloud_avg_disk_reserved/aggregate-Year-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/project/cloud_avg_disk_reserved/timeseries-Day-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/project/cloud_avg_disk_reserved/timeseries-Month-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/project/cloud_avg_disk_reserved/timeseries-Quarter-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/project/cloud_avg_disk_reserved/timeseries-Year-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/resource/cloud_avg_disk_reserved/aggregate-Day-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/resource/cloud_avg_disk_reserved/aggregate-Month-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/resource/cloud_avg_disk_reserved/aggregate-Quarter-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/resource/cloud_avg_disk_reserved/aggregate-Year-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/resource/cloud_avg_disk_reserved/timeseries-Day-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/resource/cloud_avg_disk_reserved/timeseries-Month-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/resource/cloud_avg_disk_reserved/timeseries-Quarter-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/resource/cloud_avg_disk_reserved/timeseries-Year-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/submission_venue/cloud_avg_disk_reserved/aggregate-Day-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/submission_venue/cloud_avg_disk_reserved/aggregate-Month-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/submission_venue/cloud_avg_disk_reserved/aggregate-Quarter-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/submission_venue/cloud_avg_disk_reserved/aggregate-Year-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/submission_venue/cloud_avg_disk_reserved/timeseries-Day-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/submission_venue/cloud_avg_disk_reserved/timeseries-Month-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/submission_venue/cloud_avg_disk_reserved/timeseries-Quarter-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/submission_venue/cloud_avg_disk_reserved/timeseries-Year-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/vm_size/cloud_avg_disk_reserved/aggregate-Day-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/vm_size/cloud_avg_disk_reserved/aggregate-Month-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/vm_size/cloud_avg_disk_reserved/aggregate-Quarter-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/vm_size/cloud_avg_disk_reserved/aggregate-Year-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/vm_size/cloud_avg_disk_reserved/timeseries-Day-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/vm_size/cloud_avg_disk_reserved/timeseries-Month-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/vm_size/cloud_avg_disk_reserved/timeseries-Quarter-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/vm_size/cloud_avg_disk_reserved/timeseries-Year-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/vm_size_memory/cloud_avg_disk_reserved/aggregate-Day-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/vm_size_memory/cloud_avg_disk_reserved/aggregate-Month-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/vm_size_memory/cloud_avg_disk_reserved/aggregate-Quarter-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/vm_size_memory/cloud_avg_disk_reserved/aggregate-Year-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/vm_size_memory/cloud_avg_disk_reserved/timeseries-Day-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/vm_size_memory/cloud_avg_disk_reserved/timeseries-Month-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/vm_size_memory/cloud_avg_disk_reserved/timeseries-Quarter-reference.csv
  tests/artifacts/xdmod-test-artifacts/xdmod/regression/current/expected/reference/Cloud/vm_size_memory/cloud_avg_disk_reserved/timeseries-Year-reference.csv
Labels: code cleanup, data quality

#806 Replace `Config` Usage w/ `XdmodConfiguration`
  background_scripts/update_check.php
  bin/acl-config
  bin/xdmod-admin
  bin/xdmod-import-csv
  bin/xdmod-setup
  bin/xdmod-update-resource-specs
  classes/Configuration/Configuration.php
  classes/Configuration/XdmodConfiguration.php
  classes/DB/FilterListBuilder.php
  classes/DataWarehouse.php
  classes/DataWarehouse/Query/Query.php
  classes/DataWarehouse/Query/TimeAggregationUnit.php
  classes/DataWarehouse/QueryBuilder.php
  classes/ETL/DataEndpoint/aStructuredFile.php
  classes/Models/Services/Acls.php
  classes/Models/Services/Parameters.php
  classes/OpenXdmod/Assets.php
  classes/OpenXdmod/Migration/ConfigFilesMigration.php
  classes/OpenXdmod/Migration/Migration.php
  classes/OpenXdmod/Migration/Version350To450/ConfigFilesMigration.php
  classes/OpenXdmod/Migration/Version452To500/ConfigFilesMigration.php
  classes/OpenXdmod/Migration/Version550To560/ConfigFilesMigration.php
  classes/OpenXdmod/Migration/Version560To600/ConfigFilesMigration.php
  classes/OpenXdmod/Migration/Version701To750/ConfigFilesMigration.php
  classes/OpenXdmod/Setup/MainMenu.php
  classes/OpenXdmod/Shredder.php
  classes/Rest/Controllers/WarehouseControllerProvider.php
  classes/Rest/XdmodApplicationFactory.php
  classes/User/Roles.php
  configuration/linker.php
  configuration/rawstatistics.json
  html/index.php
  html/internal_dashboard/controllers/dashboard/get_menu.php
  html/internal_dashboard/controllers/summary/get_config.php
  html/internal_dashboard/controllers/summary/get_portlets.php
  open_xdmod/modules/xdmod/integration_tests/lib/Controllers/UsageExplorerTest.php
Labels: code cleanup

#811 Update cloud realm to not throw away event precision
  classes/OpenXdmod/Migration/Version800To810/DatabasesMigration.php
  configuration/etl/etl_action_defs.d/cloud_common/cloud_transient.json
  configuration/etl/etl_action_defs.d/cloud_generic/staging_event.json
  configuration/etl/etl_action_defs.d/cloud_generic/volume.json
  configuration/etl/etl_action_defs.d/cloud_openstack/raw_cloud_job_logs.json
  configuration/etl/etl_action_defs.d/cloud_openstack/staging_event.json
  configuration/etl/etl_action_defs.d/cloud_openstack/volume.json
  configuration/etl/etl_tables.d/cloud_common/asset.json
  configuration/etl/etl_tables.d/cloud_common/event.json
  configuration/etl/etl_tables.d/cloud_common/event_reconstructed.json
  configuration/etl/etl_tables.d/cloud_common/instance_type.json
  configuration/etl/etl_tables.d/cloud_generic/raw_event.json
  configuration/etl/etl_tables.d/cloud_generic/raw_instance_type.json
  configuration/etl/etl_tables.d/cloud_generic/raw_volume.json
  configuration/etl/etl_tables.d/cloud_generic/staging_event.json
  configuration/etl/etl_tables.d/cloud_openstack/raw_event.json
  configuration/etl/etl_tables.d/cloud_openstack/raw_instance_type.json
  configuration/etl/etl_tables.d/cloud_openstack/raw_volume.json
  configuration/etl/etl_tables.d/cloud_openstack/staging_event.json
  db/migrations/8.0.0-8.1.0/modw_cloud.sql
  open_xdmod/modules/xdmod/integration_tests/scripts/xdmod-upgrade.tcl
Labels: bug, data quality

#809 Move string format functions to XDMoD.utils.format namespace
  html/gui/js/CCR.js
  html/gui/js/modules/job_viewer/JobViewer.js
  html/unit_tests/index.html
  html/unit_tests/spec/JobViewerSpec.js
  html/unit_tests/spec/XDMoDFormatSpec.js
Labels: bug, code cleanup, enhancement

#805 Deterministic reconstruction with no non-lifecycle events
  classes/ETL/Ingestor/CloudStateReconstructorTransformIngestor.php
  open_xdmod/modules/xdmod/component_tests/lib/ETL/CloudStateReconstructorTransformIngestorTest.php
Labels: bug, cloud

#819 Add proper namespace
  classes/ETL/Maintenance/VerifyDatabase.php
Labels: bug

#760 Remove UserRoleParameters Usage
  classes/Models/Services/Centers.php
  classes/User/Roles/CenterDirectorRole.php
  classes/User/Roles/CenterStaffRole.php
  classes/XDUser.php
  configuration/etl/etl.d/xdb.json
  configuration/etl/etl_sql.d/acls/xdmod/clear_orphan_parameter_records.sql
  configuration/etl/etl_sql.d/acls/xdmod/user_acl_group_by_parameters.sql
  configuration/etl/etl_tables.d/xdb/user-role-parameters.json
  html/controllers/user_admin/create_user.php
  html/controllers/user_admin/update_user.php
  open_xdmod/modules/xdmod/component_tests/lib/BaseTest.php
  open_xdmod/modules/xdmod/component_tests/lib/XDUserTest.php
  tests/artifacts/xdmod-test-artifacts/xdmod/acls/input/enum_center_director_sites.json
  tests/artifacts/xdmod-test-artifacts/xdmod/acls/input/enum_center_staff_sites.json
  tests/artifacts/xdmod-test-artifacts/xdmod/acls/input/get_primary_organization.json
  tests/artifacts/xdmod-test-artifacts/xdmod/acls/input/set_organization_valid.json
  tests/artifacts/xdmod-test-artifacts/xdmod/acls/output/enum_center_director_sites-Public User.json
  tests/artifacts/xdmod-test-artifacts/xdmod/acls/output/enum_center_director_sites-centerdirector.json
  tests/artifacts/xdmod-test-artifacts/xdmod/acls/output/enum_center_director_sites-centerstaff.json
  tests/artifacts/xdmod-test-artifacts/xdmod/acls/output/enum_center_director_sites-normaluser.json
  tests/artifacts/xdmod-test-artifacts/xdmod/acls/output/enum_center_director_sites-principal.json
  tests/artifacts/xdmod-test-artifacts/xdmod/acls/output/enum_center_staff_sites-Public User.json
  tests/artifacts/xdmod-test-artifacts/xdmod/acls/output/enum_center_staff_sites-centerdirector.json
  tests/artifacts/xdmod-test-artifacts/xdmod/acls/output/enum_center_staff_sites-centerstaff.json
  tests/artifacts/xdmod-test-artifacts/xdmod/acls/output/enum_center_staff_sites-normaluser.json
  tests/artifacts/xdmod-test-artifacts/xdmod/acls/output/enum_center_staff_sites-principal.json
  tests/artifacts/xdmod-test-artifacts/xdmod/acls/output/get_organization_collection-Public User.json
  tests/artifacts/xdmod-test-artifacts/xdmod/acls/output/get_organization_collection-centerdirector.json
  tests/artifacts/xdmod-test-artifacts/xdmod/acls/output/get_organization_collection-centerstaff.json
  tests/artifacts/xdmod-test-artifacts/xdmod/acls/output/get_organization_collection-normaluser.json
  tests/artifacts/xdmod-test-artifacts/xdmod/acls/output/get_organization_collection-principal.json
  tests/artifacts/xdmod-test-artifacts/xdmod/acls/output/get_primary_organization-Public User.json
  tests/artifacts/xdmod-test-artifacts/xdmod/acls/output/get_primary_organization-centerdirector.json
  tests/artifacts/xdmod-test-artifacts/xdmod/acls/output/get_primary_organization-centerstaff.json
  tests/artifacts/xdmod-test-artifacts/xdmod/acls/output/get_primary_organization-normaluser.json
  tests/artifacts/xdmod-test-artifacts/xdmod/acls/output/get_primary_organization-principal.json
  tests/artifacts/xdmod-test-artifacts/xdmod/roles/input/get_active_center.json
Labels: code cleanup
