Repository ubccr/xdmod, pull requests merged in 2019-07, with the labels that each got.

#930 Novice User Interface - Summary Statistics Portlet
  classes/DataWarehouse/Query/Query.php
  classes/Rest/Controllers/BaseControllerProvider.php
  classes/Rest/Controllers/SummaryControllerProvider.php
  configuration/roles.d/statistics_format.json
  configuration/roles.d/summary.json
  configuration/roles.json
  html/gui/js/modules/summary/SummaryStatisticsPortlet.js
  open_xdmod/modules/xdmod/build.json
  tests/artifacts/xdmod/rest/input/get_statistics.json
  tests/artifacts/xdmod/rest/output/get_statistics-cd.json
  tests/artifacts/xdmod/rest/output/get_statistics-cs.json
  tests/artifacts/xdmod/rest/output/get_statistics-pi.json
  tests/artifacts/xdmod/rest/output/get_statistics-pub.json
  tests/artifacts/xdmod/rest/output/get_statistics-usr.json
  tests/artifacts/xdmod/rest/output/get_statistics_end_date_invalid-pub.json
  tests/artifacts/xdmod/rest/output/get_statistics_no_end_date-pub.json
  tests/artifacts/xdmod/rest/output/get_statistics_no_start_date-pub.json
  tests/artifacts/xdmod/rest/output/get_statistics_no_start_end_date-pub.json
  tests/artifacts/xdmod/rest/output/get_statistics_start_date_after_end-pub.json
  tests/artifacts/xdmod/rest/output/get_statistics_start_date_invalid-pub.json
  tests/integration/lib/Rest/SummaryControllerProviderTest.php
Labels: Category:Novice User

#973 Improve error message for ETL action
  classes/ETL/Configuration/EtlConfiguration.php
Labels: Category:ETL, autodoc:ignore

#972 Improve processor buckets documentation
  docs/configuration.md
Labels: Category:General, documentation

#968 Add recent charts and reports portlet
  classes/Rest/Controllers/SummaryControllerProvider.php
  classes/XDReportManager.php
  configuration/assets.json
  configuration/etl/etl.d/xdmod-migration-8_1_2-8_5_0.json
  configuration/etl/etl_tables.d/xdb/reports.json
  html/gui/js/modules/ReportGenerator.js
  html/gui/js/modules/summary/RecentChartsReportsPortlet.js
  html/gui/js/report_builder/ReportsOverview.js
Labels: Category:Novice User

#977 Increase robustness for tests
  tests/ui/test/specs/xdmod/metricExplorer.page.js
Labels: autodoc:ignore, qa / testing

#971 Adding New User Help Tour and functionality to reset if a user has seen a tour or not
  classes/Rest/Controllers/AdminControllerProvider.php
  classes/Rest/Controllers/SummaryControllerProvider.php
  configuration/rest.d/admin.json
  html/gui/js/CCR.js
  html/gui/js/modules/NoviceUser.js
  html/internal_dashboard/js/admin_panel/SectionExistingUsers.js
Labels: Category:Novice User, new feature

#970 Don't migrate the aggregate table.
  configuration/etl/etl.d/xdmod-migration-8_1_2-8_5_0.json
Labels: Category:Job Viewer, autodoc:ignore

#967 Add report thumbnails portlet
  classes/ReportTemplates/GenericReportTemplate.php
  classes/Rest/Controllers/SummaryControllerProvider.php
  classes/XDReportManager.php
  configuration/assets.json
  configuration/etl/etl.d/xdmod-migration-8_1_2-8_5_0.json
  configuration/etl/etl_action_defs.d/xdb/report-template-charts-staging.json
  configuration/etl/etl_action_defs.d/xdb/report-template-charts.json
  configuration/etl/etl_action_defs.d/xdb/report-templates-staging.json
  configuration/etl/etl_action_defs.d/xdb/report-templates.json
  configuration/etl/etl_data.d/acls/report-template-acls-staging.json
  configuration/etl/etl_data.d/xdb/report-template-charts.json
  configuration/etl/etl_data.d/xdb/report-templates.json
  configuration/etl/etl_tables.d/xdb/report-template-charts-staging.json
  configuration/etl/etl_tables.d/xdb/report-templates-staging.json
  html/controllers/report_builder/send_report.php
  html/gui/css/ReportThumbnailsPortlet.css
  html/gui/js/modules/summary/ReportThumbnailsPortlet.js
  html/highchart_template.html
  tests/artifacts/xdmod/report_builder/output/cd_enum_templates.json
  tests/artifacts/xdmod/report_builder/output/cs_enum_templates.json
  tests/artifacts/xdmod/ui/output/reportGenerator.json
  tests/integration/lib/Rest/ReportThumbnailsTest.php
  tests/ui/test/specs/xdmod/reportGenerator.js
  tests/ui/test/specs/xdmod/reportGenerator.page.js
Labels: Category:Novice User

#976 Add JobPortlet
  configuration/assets.json
  html/gui/css/SummaryTab.css
  html/gui/images/new_tab.gif
  html/gui/js/modules/summary/JobPortlet.js
Labels: Category:Novice User

#995 fixing new user tour so duplicate tours are not made when the summary tab is refreshed
  html/gui/js/modules/NoviceUser.js
Labels: Category:Novice User, bug
