Repository ubccr/xdmod, pull requests merged in 2019-06, with the labels that each got.

#953 Fixing timing issues in Metric Explorer UI Tests
  tests/ui/test/specs/xdmod/metricExplorer.page.js
Labels: Category:General, qa / testing

#959 Update Travis YML to explicitly use Ubuntu 14.04
  .travis.yml
Labels: qa / testing

#952 Enable APCu cache for Configuration objects
  classes/CCR/Loggable.php
  classes/Configuration/Configuration.php
  classes/Configuration/ModuleConfiguration.php
  classes/Configuration/XdmodConfiguration.php
  classes/Configuration/iConfiguration.php
  classes/ETL/Configuration/EtlConfiguration.php
  classes/ETL/DbModel/Column.php
  docs/software-requirements.md
  open_xdmod/modules/xdmod/xdmod.spec.in
  tests/unit/lib/ETL/Configuration/ConfigurationTest.php
Labels: bug, new feature

#957 Update mysql dependency
  etl/js/package.json
Labels: maintenance / code quality

#958 Fix job Viewer lookup for multi-day jobs
  classes/DataWarehouse/Query/Jobs/JobMetadata.php
  configuration/etl/etl_tables.d/jobs/xdw/jobfact_by_day_joblist.json
Labels: Category:Job Viewer, autodoc:ignore, bug

#963 Improve mechanism to invalidate cached objects
  classes/Configuration/Configuration.php
  tests/unit/lib/ETL/Configuration/ConfigurationTest.php
Labels: Category:General, autodoc:ignore, bug

#943 Novice User Interface - Center Report Card: Support
  classes/DataWarehouse/Access/MetricExplorer.php
  classes/Rest/Controllers/SummaryControllerProvider.php
  classes/XDUser.php
  html/gui/js/Viewer.js
  html/internal_dashboard/index.php
Labels: Category:Novice User

#956 Remove unused parameters to Timeseries and Aggregate query classes
  classes/DataWarehouse/Access/MetricExplorer.php
  classes/DataWarehouse/Data/ComplexDataset.php
  classes/DataWarehouse/Data/SimpleTimeseriesDataset.php
  classes/DataWarehouse/Query/Cloud/Aggregate.php
  classes/DataWarehouse/Query/Cloud/Timeseries.php
  classes/DataWarehouse/Query/Jobs/Aggregate.php
  classes/DataWarehouse/Query/Jobs/Raw.php
  classes/DataWarehouse/Query/Jobs/RawData.php
  classes/DataWarehouse/Query/Jobs/Timeseries.php
  classes/DataWarehouse/Query/Query.php
  classes/DataWarehouse/Query/RawQuery.php
  classes/DataWarehouse/Query/Storage/Aggregate.php
  classes/DataWarehouse/Query/Storage/Timeseries.php
  classes/DataWarehouse/Query/Timeseries.php
  classes/DataWarehouse/Visualization/HighChartTimeseries2.php
  classes/Models/Services/Acls.php
  classes/Rest/Controllers/WarehouseControllerProvider.php
  classes/User/Elements/QueryDescripter.php
  html/controllers/metric_explorer/get_dw_descripter.php
  html/controllers/metric_explorer/get_rawdata.php
  html/controllers/ui_data/summary3.php
  tests/component/lib/AclsTest.php
Labels: maintenance / code quality

#962 Add guided user tours
  html/gui/css/helptour.css
  html/gui/js/Portlet.js
  html/gui/js/modules/HelpTip.js
  html/gui/js/modules/HelpTipTour.js
  html/index.php
Labels: Category:Novice User, new feature

#969 Initial set of interface specifications
  classes/DataWarehouse/Realm/iGroupBy.php
  classes/DataWarehouse/Realm/iRealm.php
  classes/DataWarehouse/Realm/iStatistic.php
Labels: Category:Infrastructure, maintenance / code quality
