Repository ubccr/xdmod, pull requests merged in 2020-02, with the labels that each got.

#1226 Revert excessive use of class constants
  classes/DataWarehouse/Export/BatchProcessor.php
  classes/DataWarehouse/Export/FileManager.php
  classes/DataWarehouse/Export/FileWriter/FileWriterFactory.php
  classes/DataWarehouse/Export/QueryHandler.php
  classes/Rest/Controllers/WarehouseExportControllerProvider.php
Labels: autodoc:ignore, enhancement

#1225 Fixing ben's typos
  tests/ci/Docker/README.md
Labels: autodoc:ignore, documentation

#1227 Improve ingestor option error checking
  bin/xdmod-ingestor
Labels: Category:General, enhancement

#1228 Adding table name to remove ambiguity from group by statement
  configuration/etl/etl_action_defs.d/cloud_generic/instance.json
Labels: Category:Cloud, bug

#1224 return user supplied jobname in search
  classes/DataWarehouse/Query/Jobs/RawData.php
Labels: OpenOnDemand, enhancement

#1229 Remove old migration files
  configuration/etl/etl_action_defs.d/migrations/7.5.1-8.0.0/hpcdb/schema-version-history.json
  configuration/etl/etl_action_defs.d/migrations/7.5.1-8.0.0/shredder/schema-version-history.json
  configuration/etl/etl_action_defs.d/migrations/7.5.1-8.0.0/xdw/schema-version-history.json
  configuration/etl/etl_data.d/migrations/7.5.1-8.0.0/hpcdb/schema-version-history.json
  configuration/etl/etl_data.d/migrations/7.5.1-8.0.0/shredder/schema-version-history.json
  configuration/etl/etl_data.d/migrations/7.5.1-8.0.0/xdw/schema-version-history.json
  configuration/etl/etl_sql.d/migrations/7.5.1-8.0.0/hpcdb/truncate-email-addresses.sql
Labels: autodoc:ignore, maintenance / code quality

#1230 update trello tests to work
  tests/ui/test/specs/xdmod/about.page.js
Labels: autodoc:ignore, qa / testing

#1231 Improve job viewer test assertions
  tests/integration/lib/Rest/JobViewerTest.php
Labels: autodoc:ignore, maintenance / code quality, qa / testing

#1233 Update report_template_acls.json
  configuration/etl/etl_tables.d/acls/report_template_acls.json
Labels: autodoc:ignore, bug

#1234 Remove `cloudfact_by_.json` from migration definition file list
  configuration/etl/etl.d/xdmod-migration-8_5_1-9_0_0.json
Labels: Category:ETL, autodoc:ignore, bug

#1236 Update regression tests documentation
  tests/regression/README.md
Labels: Category:General, autodoc:ignore, documentation

#1237 Add additional ETL DB Model error checking
  classes/ETL/DbModel/ForeignKeyConstraint.php
  classes/ETL/DbModel/Index.php
  tests/unit/lib/ETL/DbModel/DbModelTest.php
Labels: Category:ETL

#1219 Add input validation to report generator controller endpoints.
  classes/DataWarehouse/Access/ReportGenerator.php
  html/controllers/report_builder/download_report.php
  html/controllers/report_builder/save_report.php
  html/controllers/report_builder/send_report.php
  html/report_image_renderer.php
  tests/unit/lib/DataWarehouse/Access/ReportGeneratorTest.php
Labels: Category:Report Generator, bug
