Repository ubccr/xdmod, pull requests merged in 2020-10, with the labels that each got.

#1454 Only show the New User Tour Dialog once per session.
  html/gui/js/modules/Dashboard.js
Labels: bug

#1457 Add support for terabyte suffix in SGE/UGE logs
  classes/OpenXdmod/Shredder/Sge.php
  tests/artifacts/xdmod/unit/shredder/sge/input/accounting-logs.log
  tests/artifacts/xdmod/unit/shredder/sge/output/accounting-logs.json
Labels: Category:ETL, enhancement

#1459 Improve batch data export tests
  tests/component/lib/Export/BatchProcessTest.php
Labels: Category:Data Warehouse Export, autodoc:ignore

#1420 Change the file load character set override to be configurable.
  classes/DB/PDODBMultiIngestor.php
Labels: autodoc:ignore, bug

#1419 Update the report generator regex to allow XSEDE compliance reports.
  classes/DataWarehouse/Access/ReportGenerator.php
  tests/unit/lib/DataWarehouse/Access/ReportGeneratorTest.php
Labels: autodoc:ignore, bug
