Repository ubccr/xdmod, pull requests merged in 2020-11, with the labels that each got.

#1460 Increase maximum queue name length
  configuration/etl/etl.d/xdmod-migration-9_0_0-9_5_0.json
  configuration/etl/etl_tables.d/jobs/xdw/job-records.json
  configuration/etl/etl_tables.d/jobs/xdw/jobfact_by_.json
  configuration/etl/etl_tables.d/jobs/xdw/jobfact_by_day.json
  configuration/etl/etl_tables.d/jobs/xdw/queue.json
Labels: Category:ETL, enhancement

#1462 Removing Unused Code
  classes/DB/PDODBIngestor.php
Labels: Category:Infrastructure, maintenance / code quality

#1463 A dirty dirty attempt at migrating our Travis tests
  .travis.yml
  shippable.yml
  tests/ci/scripts/qa-test-setup.sh
Labels: Category:Infrastructure, experiment, qa / testing

#1455 Update SSO to pull the configured SP's IdP metadata directly
  classes/Authentication/SAML/XDSamlAuthentication.php
Labels: Category:General, bug
