Repository ubccr/xdmod, pull requests merged in 2020-09, with the labels that each got.

#1437 Use absolute path when running acl-config
  classes/OpenXdmod/Migration/AclConfigMigration.php
  classes/OpenXdmod/Setup/AclConfig.php
  classes/OpenXdmod/Setup/DatabaseSetup.php
  configuration/constants.php
  open_xdmod/build_scripts/templates/install.template
Labels: Category:ACL, enhancement

#1438 Update the directory that ui/runtests.sh runs from
  tests/ui/runtests.sh
Labels: Category:Infrastructure, maintenance / code quality

#1441 Update and add GroupBy categories
  configuration/datawarehouse.d/ref/group-by-common.json
Labels: Category:Job Viewer, bug

#1440 Make tests more robust
  tests/ui/test/specs/xdmod/internalDashboard.js
  tests/ui/test/specs/xdmod/reportGenerator.page.js
Labels: autodoc:ignore, qa / testing

#1444 Replace APC function with APCu function
  classes/Configuration/Configuration.php
Labels: Category:General, autodoc:ignore, maintenance / code quality

#1442 Fix call to non-existent method
  classes/Configuration/Configuration.php
Labels: Category:General, autodoc:ignore, bug

#1446 Fix institution loading during manual user creation
  html/gui/js/TGUserDropDown.js
  html/internal_dashboard/js/admin_panel/SectionExistingUsers.js
Labels: Category:Internal Dashboard, bug

#1447 Updating ubccr/simplesamlphp-module-authoidcoauth2 to 1.1.0
  composer.json
  composer.lock
Labels: Category:Infrastructure, autodoc:ignore

#1448 Change raw statistics variable substitution format
  classes/DataWarehouse/Data/RawStatisticsConfiguration.php
  configuration/rawstatistics.d/20_jobs.json
Labels: Category:General, enhancement

#1434 Remove unnecessary report font code
  classes/DataWarehouse/Access/ReportGenerator.php
  classes/ReportTemplates/GenericReportTemplate.php
  classes/ReportTemplates/ParameterizedReportTemplate.php
  classes/XDReportManager.php
  configuration/etl/etl.d/xdmod-migration-9_0_0-9_5_0.json
  configuration/etl/etl_data.d/xdb/report-templates.json
  configuration/etl/etl_tables.d/xdb/report-templates.json
  configuration/etl/etl_tables.d/xdb/reports.json
  html/controllers/report_builder/save_report.php
  html/gui/js/report_builder/ReportCreator.js
  html/gui/js/report_builder/ReportsOverview.js
  reporting/jasper_builder/ReportBuilder.sh
  reporting/jasper_builder/template_1up.jrxml
  reporting/jasper_builder/template_2up.jrxml
  tests/artifacts/xdmod/report_builder/input/create_report.json
Labels: Category:Report Generator, autodoc:ignore, maintenance / code quality

#1439 Remove Google chrome from docker
  Dockerfile
  tests/artifacts/xdmod/regression/images/expected.json
  tests/ci/Docker/Dockerfile
  tests/ci/Docker/Dockerfile.centos7:xdmod-base
  tests/ci/Docker/assets/google-chrome.repo
  tests/ui/package.json
  tests/ui/readme.md
  tests/ui/wdio.conf.js
Labels: autodoc:ignore

#1449 Add additional raw statistics features
  etl/js/lib/etl_profile.js
Labels: Category:Job Viewer, autodoc:ignore, enhancement

#1451 Add data export logs to administrative dashboard
  configuration/internal_dashboard.json
Labels: Category:Internal Dashboard, enhancement

#1450 Fix login dialog sign in button rendering on Google Chrome 85+
  html/gui/css/LoginPrompt.css
Labels: bug
