Repository ubccr/xdmod, pull requests merged in 2020-08, with the labels that each got.

#1406 Fix typos
  docs/cloud.md
Labels: Category:Cloud, autodoc:ignore, documentation

#1407 Add table to migration
  configuration/etl/etl.d/xdmod-migration-8_5_1-9_0_0.json
Labels: Category:Cloud, Category:ETL, autodoc:ignore, bug

#1408 Update cloud re-ingest example commands
  docs/cloud.md
Labels: Category:Cloud, autodoc:ignore, documentation

#1412 Update cloud documentation with information for cloud utilization
  docs/cloud.md
Labels: Category:Cloud, autodoc:ignore, documentation

#1409 Rearrange MySQL configuration documentation
  docs/configuration.md
  docs/faq.md
  docs/software-requirements.md
  docs/troubleshooting.md
  docs/upgrade.md
Labels: Category:General, autodoc:ignore, documentation

#1410 Remove database guide
  docs/_data/toc.yml
  docs/configuration.md
  docs/databases.md
Labels: Category:General, autodoc:ignore, documentation

#1415 Add more upgrade notes
  docs/upgrade.md
Labels: Category:General, autodoc:ignore, release prep

#1414 Release notes for 9.0.0
  CHANGELOG.md
  docs/support.md
  html/about/release_notes/xdmod.html
  open_xdmod/modules/xdmod/xdmod.spec.in
Labels: Category:General, autodoc:ignore, documentation, release prep

#1417 Update release date
  CHANGELOG.md
  docs/support.md
  html/about/release_notes/xdmod.html
  open_xdmod/modules/xdmod/xdmod.spec.in
Labels: Category:General, autodoc:ignore, release prep

#1395 Add documentation for the dashboard.
  docs/_data/toc.yml
  docs/configuration.md
  docs/dashboard-devel.md
  docs/dashboard.md
Labels: documentation

#1140 Miscellaneous Docker enhancements
  Dockerfile
  tests/ci/Docker/Dockerfile
  tests/ci/Docker/Dockerfile.centos7:xdmod-base
  tests/ci/Docker/README.md
  tests/ci/Docker/assets/copy-caches.sh
  tests/ci/samlSetup.sh
  tests/ui/package.json
  tests/ui/runtests.sh
  tests/ui/test/specs/xdmod/reportGenerator.page.js
  tests/ui/wdio.conf.js
Labels: enhancement, experiment

#1422 Initial XDMoD 9.5 change
  Dockerfile
  bin/xdmod-upgrade
  classes/OpenXdmod/Migration/Version851To900/ConfigFilesMigration.php
  classes/OpenXdmod/Migration/Version851To900/DatabaseMigration.php
  classes/OpenXdmod/Migration/Version900To950/ConfigFilesMigration.php
  configuration/etl/etl.d/xdmod-migration-8_5_1-9_0_0.json
  configuration/etl/etl.d/xdmod-migration-9_0_0-9_5_0.json
  configuration/etl/etl_sql.d/migrations/8.5.1-9.0.0/jobs-gpu/hpcdb_jobs-to-job_tasks.sql
  configuration/etl/etl_sql.d/migrations/8.5.1-9.0.0/jobs-gpu/shredded_job-to-staging_job.sql
  configuration/etl/etl_sql.d/migrations/8.5.1-9.0.0/jobs-gpu/shredded_job_pbs-to-shredded_job.sql
  configuration/etl/etl_sql.d/migrations/8.5.1-9.0.0/jobs-gpu/shredded_job_slurm-to-shredded_job.sql
  configuration/etl/etl_sql.d/migrations/8.5.1-9.0.0/jobs-gpu/staging_job-to-hpcdb_jobs.sql
  configuration/etl/etl_sql.d/migrations/8.5.1-9.0.0/logger/alter-log-table.sql
  configuration/etl/etl_sql.d/migrations/8.5.1-9.0.0/role-table-cleanup.sql
  configuration/etl/etl_sql.d/migrations/8.5.1-9.0.0/shredder/alter-job-slurm.sql
  configuration/etl/etl_sql.d/migrations/cloud-migration-8-5-1_9-0-0.sql
  configuration/portal_settings.ini
  docs/_config.yml
  docs/upgrade.md
  open_xdmod/modules/xdmod/build.json
  tests/ci/Docker/Dockerfile
  tests/ci/Docker/Dockerfile.centos7:xdmod-base
  tests/ci/bootstrap.sh
  tests/ci/scripts/xdmod-upgrade-cloud.tcl
  tests/ci/scripts/xdmod-upgrade-jobs.tcl
  tests/ci/scripts/xdmod-upgrade.tcl
Labels: autodoc:ignore

#1413 Switch to Chromium instead of PhantomJS to generate chart export images.
  bin/xdmod-check-config
  classes/OpenXdmod/Migration/Version900To950/ConfigFilesMigration.php
  classes/OpenXdmod/Setup/GeneralSetup.php
  configuration/portal_settings.ini
  docs/software-requirements.md
  docs/upgrade.md
  html/highchart_template.html
  libraries/charting.php
  libraries/phantomjs.php
  libraries/phantomjs/.eslintrc.json
  libraries/phantomjs/generate_highchart.js
  open_xdmod/modules/xdmod/xdmod.spec.in
  templates/portal_settings.template
  tests/artifacts/xdmod/regression/images/expected.json
  tests/ci/Docker/assets/copy-caches.sh
  tests/ci/README.md
  tests/ci/scripts/xdmod-setup-start.tcl
  tests/ci/scripts/xdmod-upgrade.tcl
Labels: Category:Infrastructure, dependencies, maintenance / code quality

#1425 Populate PDF MetaData with more than a filename
  classes/DataWarehouse/Access/Common.php
  classes/DataWarehouse/Access/MetricExplorer.php
  classes/DataWarehouse/Access/Usage.php
Labels: Category:General, enhancement

#1424 Replace ghostscript with exiftool
  docs/software-requirements.md
  docs/upgrade.md
  libraries/charting.php
  open_xdmod/modules/xdmod/xdmod.spec.in
Labels: Category:Infrastructure, dependencies

#1418 Removing references to acl-config's recover mode
  bin/acl-config
  docs/faq.md
Labels: documentation

#1430 Verifying User Query Count to address TrustedCI feedback
  classes/Rest/Utilities/Authentication.php
  classes/XDUser.php
Labels: maintenance / code quality

#1431 Restore node utilization statistics
  configuration/datawarehouse.d/include/Jobs-node-util-agg.sql
  configuration/datawarehouse.d/include/Jobs-node-util-time.sql
  docs/howto-node-utilization.md
Labels: Category:Metric Explorer, enhancement

#1432 Remove unused report and chart template tables
  configuration/etl/etl.d/xdmod-migration-9_0_0-9_5_0.json
  configuration/etl/etl_action_defs.d/xdb/report-template-charts-staging.json
  configuration/etl/etl_action_defs.d/xdb/report-templates-staging.json
  configuration/etl/etl_sql.d/migrations/9.0.0-9.5.0/moddb/drop-report-and-chart-staging-tables.sql
  configuration/etl/etl_tables.d/xdb/report-template-charts-staging.json
  configuration/etl/etl_tables.d/xdb/report-templates-staging.json
Labels: Category:General, autodoc:ignore, maintenance / code quality

#1433 Remove ETL action using ReportTemplatesStaging
  configuration/etl/etl_action_defs.d/xdb/report-template-charts.json
  configuration/etl/etl_action_defs.d/xdb/report-templates.json
Labels: Category:General, autodoc:ignore, maintenance / code quality

#1401 Add -c/--cluster flag to xdmod-slurm-helper
  bin/xdmod-slurm-helper
Labels: Category:ETL, enhancement, new feature

#1435 Fix chart layout and timeframe radio button crowding
  html/gui/css/viewer.css
Labels: Category:Report Generator, bug

#1436 Fix checkbox CSS syntax
  html/gui/css/viewer.css
Labels: Category:General, maintenance / code quality
