Repository ubccr/xdmod, pull requests merged in 2020-06, with the labels that each got.

#1325 Update PhantomJS unit tests
  html/unit_tests/index.html
  html/unit_tests/phantom.js
Labels: Category:Infrastructure, qa / testing

#1326 Remove php-mcrypt requirement
  bin/xdmod-check-config
  docs/software-requirements.md
  open_xdmod/modules/xdmod/xdmod.spec.in
  tests/ci/bootstrap.sh
Labels: Category:General, maintenance / code quality

#1327 Update xdmod-check-config script
  bin/xdmod-check-config
Labels: Category:General

#1328 Change default log directory permissions
  open_xdmod/build_scripts/templates/install.template
  open_xdmod/modules/xdmod/xdmod.spec.in
Labels: Category:General

#1329 Remove old database migrations
  db/migrations/3.5.0-4.5.0/mod_hpcdb.sql
  db/migrations/3.5.0-4.5.0/mod_logger.sql
  db/migrations/3.5.0-4.5.0/mod_shredder.sql
  db/migrations/3.5.0-4.5.0/moddb.sql
  db/migrations/3.5.0-4.5.0/modw.sql
  db/migrations/4.5.2-5.0.0/mod_hpcdb.sql
  db/migrations/4.5.2-5.0.0/mod_shredder.sql
  db/migrations/4.5.2-5.0.0/moddb.sql
  db/migrations/4.5.2-5.0.0/modw.sql
  db/migrations/5.0.0-5.5.0/mod_hpcdb.sql
  db/migrations/5.0.0-5.5.0/mod_shredder.sql
  db/migrations/5.0.0-5.5.0/modw.sql
  db/migrations/5.5.0-5.6.0/mod_logger.sql
  db/migrations/5.5.0-5.6.0/mod_shredder.sql
  db/migrations/5.5.0-5.6.0/moddb.sql
  db/migrations/5.5.0-5.6.0/modw.sql
  db/migrations/5.6.0-6.0.0/mod_shredder.sql
  db/migrations/5.6.0-6.0.0/moddb.sql
  db/migrations/5.6.0-6.0.0/modw.sql
  db/migrations/6.0.0-6.5.0/mod_hpcdb.sql
  db/migrations/6.0.0-6.5.0/mod_shredder.sql
  db/migrations/6.5.0-6.6.0/moddb.sql
  db/migrations/6.5.0-6.6.0/modw.sql
  db/migrations/6.6.0-7.0.0/moddb.sql
  db/migrations/7.0.1-7.5.0/moddb.sql
  db/migrations/7.5.1-8.0.0/mod_logger.sql
  db/migrations/7.5.1-8.0.0/moddb.sql
  db/migrations/7.5.1-8.0.0/modw.sql
  db/migrations/7.5.1-8.0.0/modw_aggregates.sql
  db/migrations/8.0.0-8.1.0/modw.sql
Labels: Category:General, maintenance / code quality

#1330 Add index to log table
  configuration/etl/etl.d/xdmod-migration-8_5_1-9_0_0.json
  configuration/etl/etl_sql.d/migrations/8.5.1-9.0.0/logger/alter-log-table.sql
  db/schema/mod_logger.sql
  docs/upgrade.md
Labels: Category:Internal Dashboard, enhancement

#1331 Update source installation log directory notes
  docs/install-source.md
Labels: Category:General, enhancement

#1332 Add DISTINCT to Jobs realm JobDataset query
  classes/DataWarehouse/Query/Jobs/JobDataset.php
Labels: Category:Job Viewer, bug

#1333 Change default log file permissions
  classes/CCR/Log.php
Labels: Category:General, enhancement

#1338 Refactor Query class to allow DISTINCT queries
  classes/DataWarehouse/Query/Jobs/JobDataset.php
  classes/DataWarehouse/Query/Jobs/RawData.php
  classes/DataWarehouse/Query/Query.php
Labels: Category:General, autodoc:ignore, maintenance / code quality

#1342 consistient log levels
  classes/OpenXdmod/DataWarehouseInitializer.php
Labels: maintenance / code quality

#1344 Remove bug that causes stop events to create sessions
  classes/ETL/Ingestor/CloudStateReconstructorTransformIngestor.php
  classes/OpenXdmod/Migration/Version851To900/DatabaseMigration.php
  tests/artifacts/xdmod/referencedata/openstack_error_sessions/2018-04-18T00:00:00_2018-04-18T23:59:59.json
  tests/artifacts/xdmod/regression/chartFilterTests.json
  tests/ci/bootstrap.sh
Labels: Category:Cloud, bug

#1346 Refactor job shredder tests
  tests/artifacts/xdmod/unit/shredder/lsf/input/accounting-logs.log
  tests/artifacts/xdmod/unit/shredder/lsf/output/accounting-logs.json
  tests/artifacts/xdmod/unit/shredder/pbs/input/accounting-logs.log
  tests/artifacts/xdmod/unit/shredder/pbs/output/accounting-logs.json
  tests/artifacts/xdmod/unit/shredder/sge/input/accounting-logs.log
  tests/artifacts/xdmod/unit/shredder/sge/output/accounting-logs.json
  tests/artifacts/xdmod/unit/shredder/uge/input/accounting-logs.log
  tests/artifacts/xdmod/unit/shredder/uge/output/accounting-logs.json
  tests/unit/lib/OpenXdmod/Tests/Shredder/JobShredderBaseTestCase.php
  tests/unit/lib/OpenXdmod/Tests/Shredder/LsfShredderTest.php
  tests/unit/lib/OpenXdmod/Tests/Shredder/PbsShredderTest.php
  tests/unit/lib/OpenXdmod/Tests/Shredder/SgeShredderTest.php
  tests/unit/lib/OpenXdmod/Tests/Shredder/ShredderTest.php
  tests/unit/lib/OpenXdmod/Tests/Shredder/SlurmShredderTest.php
  tests/unit/lib/OpenXdmod/Tests/Shredder/UgeShredderTest.php
Labels: Category:General, autodoc:ignore, maintenance / code quality, qa / testing

#1345 Update GPU count migration
  classes/OpenXdmod/Migration/Version851To900/DatabaseMigration.php
  classes/OpenXdmod/Shredder/Slurm.php
  classes/Xdmod/SlurmResourceParser.php
  tests/unit/lib/OpenXdmod/Tests/SlurmResourceParserTest.php
Labels: Category:General, autodoc:ignore, enhancement

#1343 Raw stats SUPREMM refactoring
  etl/js/lib/etl_profile.js
Labels: Category:Data Warehouse Export, enhancement

#1349 Fix bugs in definition of job fact tables.
  configuration/etl/etl_tables.d/jobs/xdw/jobfact_by_.json
  configuration/etl/etl_tables.d/jobs/xdw/jobfact_by_day.json
Labels: bug

#1088 Make the Shredder ignore empty lines
  classes/OpenXdmod/Shredder.php
Labels: Category:ETL, bug

#1301 Add support for multiple groupby definition files in js etl.
  etl/js/lib/etl_profile.js
  etl/js/package.json
Labels: Category:Infrastructure, enhancement

#1351 CORS changes needed for OpenOnDemand
  classes/DataWarehouse/Query/Jobs/RawData.php
  classes/OpenXdmod/Migration/Version851To900/ConfigFilesMigration.php
  classes/Rest/XdmodApplicationFactory.php
  configuration/portal_settings.ini
  docs/configuration.md
  docs/integrations.md
  docs/simpleSAMLphp.md
  html/gui/general/login.php
  templates/portal_settings.template
Labels: OpenOnDemand

#1352 Fix bugs in definition of cloud fact tables.
  configuration/etl/etl_tables.d/cloud_common/cloudfact_by_.json
Labels: bug

#1353 Add PBS jobs realm GPU data
  classes/OpenXdmod/Migration/Version851To900/DatabaseMigration.php
  classes/OpenXdmod/Shredder/Pbs.php
  classes/Xdmod/PbsResourceParser.php
  configuration/etl/etl.d/xdmod-migration-8_5_1-9_0_0.json
  configuration/etl/etl_sql.d/migrations/8.5.1-9.0.0/jobs-gpu/shredded_job_pbs-to-shredded_job.sql
  configuration/etl/etl_tables.d/jobs/shredder/job-pbs.json
  tests/artifacts/xdmod/unit/pbs-resource-parser/resource-list-nodes-gpu-count.json
  tests/artifacts/xdmod/unit/shredder/pbs/input/accounting-logs.log
  tests/artifacts/xdmod/unit/shredder/pbs/output/accounting-logs.json
  tests/ci/scripts/xdmod-upgrade-jobs.tcl
  tests/ci/scripts/xdmod-upgrade.tcl
  tests/unit/lib/OpenXdmod/Tests/PbsResourceParserTest.php
  tests/unit/lib/OpenXdmod/Tests/Shredder/PbsShredderTest.php
Labels: Category:ETL, enhancement

#1357 Need to catch the right Exception
  classes/Rest/XdmodApplicationFactory.php
Labels: autodoc:ignore

#1355 Add GPU metrics documentation
  docs/_data/toc.yml
  docs/configuration.md
  docs/gpu-metrics.md
Labels: Category:General, documentation

#1358 Fix typos
  docs/dev-contributing.md
Labels: Category:General, documentation

#1359 Update processor buckets documentation
  docs/configuration.md
Labels: Category:General, documentation
