Repository ubccr/xdmod, pull requests merged in 2020-03, with the labels that each got.

#1240 Delete Unused file
  classes/DB/FilterListBuilder.php
  classes/DB/Loggable.php
Labels: autodoc:ignore, maintenance / code quality

#1241 Update report api fitlers to allow the dashboard reports
  classes/DataWarehouse/Access/ReportGenerator.php
  tests/unit/lib/DataWarehouse/Access/ReportGeneratorTest.php
Labels: autodoc:ignore, bug

#1168 Remove unused ReportTemplateACL table
  configuration/etl/etl.d/xdb.json
  configuration/etl/etl_action_defs.d/xdb/report-template-acl.json
  configuration/etl/etl_data.d/xdb/report-template-acl.json
  configuration/etl/etl_tables.d/xdb/report-template-acl.json
  docs/upgrade.md
  tests/ci/validate.sh
Labels: maintenance / code quality

#1243 Make development easier...at least for ben
  composer.json
  composer.lock
Labels: autodoc:ignore

#1246 update deps
  composer.lock
Labels: dependencies

#1232 Remove foreign key constraints from MyISAM table
  configuration/etl/etl_tables.d/cloud_openstack/domain_submission_venue.json
Labels: Category:ETL, bug

#1252 Add referenced schema to foreign key constraints
  classes/ETL/DbModel/ForeignKeyConstraint.php
  classes/ETL/DbModel/Table.php
  tests/artifacts/xdmod/unit/etl/db-model/foreign-key-constraint/alter-table.json
  tests/artifacts/xdmod/unit/etl/db-model/foreign-key-constraint/create-table.json
  tests/artifacts/xdmod/unit/etl/db-model/foreign-key-constraint/verification-failure.json
  tests/artifacts/xdmod/unit/etl/db-model/foreign-key-constraint/verification.json
  tests/unit/lib/ETL/DbModel/DbModelTest.php
  tests/unit/lib/ETL/DbModel/ForeignKeyConstraintTest.php
Labels: Category:ETL, new feature

#1248 Reduce the roundoff error in the Avg of N others calculation.
  classes/DataWarehouse/Data/SimpleTimeseriesDataset.php
  tests/artifacts/xdmod/regression/images/expected.json
Labels: Category:Infrastructure, enhancement, metric

#1249 Update openstack json event schema definition
  configuration/etl/etl_schemas.d/cloud_openstack/event.schema.json
Labels: Category:Cloud, bug

#1259 Check engine during foreign key constraint verification
  classes/ETL/DbModel/Table.php
  tests/artifacts/xdmod/etlv2/dbmodel/input/table_def-charset.json
  tests/artifacts/xdmod/etlv2/dbmodel/input/table_def_2-charset.json
  tests/artifacts/xdmod/etlv2/dbmodel/output/table_def-charset.sql
  tests/artifacts/xdmod/unit/etl/db-model/foreign-key-constraint/verification-failure.json
Labels: Category:ETL, enhancement

#1257 Alter database table model schema change handling
  classes/ETL/DbModel/Table.php
  tests/unit/lib/ETL/DbModel/ForeignKeyConstraintTest.php
  tests/unit/lib/ETL/DbModel/TableTest.php
Labels: Category:ETL, autodoc:ignore, bug

#1265 Change test script shell and set XDMOD_REALMS
  .travis.yml
  tests/integration/runtests.sh
  tests/unit/runtests.sh
Labels: autodoc:ignore, bug

#1266 Adjust ETL database model table schema assignment
  classes/ETL/DbModel/Table.php
  tests/unit/lib/ETL/DbModel/TableTest.php
Labels: Category:ETL, autodoc:ignore, bug

#1267 Update regression test documentation
  tests/regression/README.md
Labels: autodoc:ignore, documentation

#1268 Fix html decoding in Job Viewer -> Edit Search
  classes/Rest/Controllers/WarehouseControllerProvider.php
  html/gui/js/modules/job_viewer/SearchPanel.js
  tests/integration/lib/Rest/JobViewerTest.php
Labels: bug

#1263 Change account, instance and instance_type tables to have single unique auto increment column
  configuration/datawarehouse.d/ref/Cloud-group-bys.json
  configuration/etl/etl.d/xdmod-migration-8_5_1-9_0_0.json
  configuration/etl/etl_sql.d/migrations/cloud-migration-8-5-1_9-0-0.sql
  configuration/etl/etl_tables.d/cloud_common/account.json
  configuration/etl/etl_tables.d/cloud_common/instance.json
  configuration/etl/etl_tables.d/cloud_common/instance_type.json
  tests/artifacts/xdmod/regression/chartFilterTests.json
  tests/integration/lib/Controllers/UsageExplorerTest.php
Labels: Category:Cloud, bug

#1272 changing account, instance and instance_type tables to have global un…
  configuration/etl/etl.d/jobs_cloud_common.json
  configuration/etl/etl_action_defs.d/cloud_common/account.json
  configuration/etl/etl_action_defs.d/cloud_common/initialize_unknown_dimension_values.json
  configuration/etl/etl_action_defs.d/cloud_common/instance.json
  configuration/etl/etl_action_defs.d/cloud_common/instance_type.json
  configuration/etl/etl_data.d/cloud_common/account.json
  configuration/etl/etl_data.d/cloud_common/instance.json
  configuration/etl/etl_data.d/cloud_common/instance_type.json
Labels: Category:Cloud, bug

#1271 Don't analyze tables during jobs aggregation for GPU data migration
  classes/ETL/Utilities.php
  classes/OpenXdmod/Migration/Version851To900/DatabaseMigration.php
Labels: Category:ETL, autodoc:ignore

#1274 Removing code path for cloud project filter that is no longer necessary
  classes/DataWarehouse/Access/Usage.php
Labels: Category:Cloud, maintenance / code quality

#1269 Remove unnecessary redirect in the job viewer rest stack.
  classes/Rest/Controllers/WarehouseControllerProvider.php
Labels: bug
