Repository ubccr/xdmod, pull requests merged in 2020-12, with the labels that each got.

#1464 Add decimal as allowable data type definition.
  etl/js/lib/mysql.js
Labels: autodoc:ignore

#1400 Set the "Show in X tab" label in the Metric Explorer automatically based on whether the dashboard is enabled
  html/gui/js/modules/metric_explorer/MetricExplorer.js
Labels: bug

#1466 Disabling SSLv3 to prevent Poodle Attack
  templates/apache.conf
Labels: Category:General, security

#1467 Update version of ini package
  etl/js/package.json
Labels: bug

#1341 Remove jasper reports and replace with PHPWord/libreoffice
  NOTICE
  README.md
  classes/Reports/ClassicReport.php
  classes/XDReportManager.php
  composer.json
  composer.lock
  configuration/portal_settings.ini
  docs/notices.md
  docs/software-requirements.md
  html/controllers/report_builder/save_report.php
  open_xdmod/build_scripts/templates/install.template
  open_xdmod/modules/xdmod/assets/setup.sh
  open_xdmod/modules/xdmod/build.json
  open_xdmod/modules/xdmod/xdmod.spec.in
  reporting/jasper_builder/Builder.java
  reporting/jasper_builder/MyDataSource.java
  reporting/jasper_builder/MySection.java
  reporting/jasper_builder/README.txt
  reporting/jasper_builder/Report.java
  reporting/jasper_builder/ReportBuilder.sh
  reporting/jasper_builder/ReportSettings.java
  reporting/jasper_builder/Translate.java
  reporting/jasper_builder/XMLToExcel.java
  reporting/jasper_builder/XmlParser.java
  reporting/jasper_builder/template_1up.jrxml
  reporting/jasper_builder/template_2up.jrxml
  templates/portal_settings.template
Labels: Category:Report Generator, maintenance / code quality

#1468 Re-index value returned from getRawDataRealms function
  classes/DataWarehouse/Data/RawStatisticsConfiguration.php
Labels: Category:General, bug

#1471 Updating qa-test-setup to include remote branch for Shippable
  tests/ci/scripts/qa-test-setup.sh
Labels: Category:Infrastructure, autodoc:ignore, bug
