Repository ubccr/xdmod, pull requests merged in 2021-01, with the labels that each got.

#1474 Updated XMS project's authors and team listings
  AUTHORS.md
  html/about/team.html
Labels: documentation

#1476 Remove remaining deprecated html from About tab pages
  html/about/links.html
  html/about/openxd.html
  html/about/supremm.html
  html/about/xdmod.php
Labels: documentation

#1475 Updating QA Setup Script to not explicitly set remote branch for build.sh
  tests/ci/scripts/qa-test-setup.sh
Labels: Category:Infrastructure, autodoc:ignore, qa / testing

#1470 Update About tab with recent Publications and Presentations details
  html/about/presentations.html
  html/about/publications.html
Labels: documentation

#1481 Fix filtered indexes
  classes/DataWarehouse/Access/BatchExport.php
  classes/DataWarehouse/Access/RawData.php
  classes/DataWarehouse/Export/RealmManager.php
Labels: Category:General, bug

#1482 Update listing of XDMoD demos from Autumn 2020
  html/about/presentations.html
Labels: documentation

#1484 Update moddb.module_version table
  bin/acl-config
  configuration/etl/etl_tables.d/acls/module_versions.json
Labels: Category:ACL, bug

#1477 Fix hang in nodejs etl on mysql connection failure.
  etl/js/lib/etl_profile.js
Labels: Category:ETL, bug

#1488 Change top-level exception handling in scripts
  background_scripts/update_check.php
  bin/xdmod-admin
  bin/xdmod-import-csv
  bin/xdmod-ingestor
  bin/xdmod-shredder
  bin/xdmod-slurm-helper
  bin/xdmod-update-resource-specs
  bin/xdmod-upgrade
  tests/artifacts/xdmod/component/slurm_helper/sacct.json
  tests/component/lib/SlurmHelperTest.php
Labels: Category:General, bug
