Repository ubccr/xdmod, pull requests merged in 2021-12, with the labels that each got.

#1572 Convert modw_cloud tables to InnoDB table engine
  classes/OpenXdmod/Migration/Version950To1000/DatabasesMigration.php
  configuration/etl/etl.d/xdmod-migration-9_5_0-10_0_0.json
  configuration/etl/etl_sql.d/migrations/9.5.0-10.0.0/modw_cloud/convert_innodb_aggregate_tables.sql
  configuration/etl/etl_tables.d/cloud_common/account.json
  configuration/etl/etl_tables.d/cloud_common/asset.json
  configuration/etl/etl_tables.d/cloud_common/asset_type.json
  configuration/etl/etl_tables.d/cloud_common/cloud_resource_specs.json
  configuration/etl/etl_tables.d/cloud_common/cloudfact_by_.json
  configuration/etl/etl_tables.d/cloud_common/cloudfact_by_day.json
  configuration/etl/etl_tables.d/cloud_common/domains.json
  configuration/etl/etl_tables.d/cloud_common/event.json
  configuration/etl/etl_tables.d/cloud_common/event_asset.json
  configuration/etl/etl_tables.d/cloud_common/event_reconstructed.json
  configuration/etl/etl_tables.d/cloud_common/event_type.json
  configuration/etl/etl_tables.d/cloud_common/host.json
  configuration/etl/etl_tables.d/cloud_common/image.json
  configuration/etl/etl_tables.d/cloud_common/instance.json
  configuration/etl/etl_tables.d/cloud_common/instance_data.json
  configuration/etl/etl_tables.d/cloud_common/instance_type.json
  configuration/etl/etl_tables.d/cloud_common/memory_buckets.json
  configuration/etl/etl_tables.d/cloud_common/processor_buckets.json
  configuration/etl/etl_tables.d/cloud_common/raw_resource_specs.json
  configuration/etl/etl_tables.d/cloud_common/record_type.json
  configuration/etl/etl_tables.d/cloud_common/resourcespecsfact_by_.json
  configuration/etl/etl_tables.d/cloud_common/session_records.json
  configuration/etl/etl_tables.d/cloud_common/staging_cloud_project_to_pi.json
  configuration/etl/etl_tables.d/cloud_common/staging_resource_specifications.json
  configuration/etl/etl_tables.d/cloud_generic/raw_event.json
  configuration/etl/etl_tables.d/cloud_generic/raw_instance_type.json
  configuration/etl/etl_tables.d/cloud_generic/raw_volume.json
  configuration/etl/etl_tables.d/cloud_generic/staging_event.json
  configuration/etl/etl_tables.d/cloud_openstack/domain_submission_venue.json
  configuration/etl/etl_tables.d/cloud_openstack/domain_submission_venue_staging.json
  configuration/etl/etl_tables.d/cloud_openstack/openstack_event_map.json
  configuration/etl/etl_tables.d/cloud_openstack/raw_event.json
  configuration/etl/etl_tables.d/cloud_openstack/raw_instance_type.json
  configuration/etl/etl_tables.d/cloud_openstack/raw_volume.json
  configuration/etl/etl_tables.d/cloud_openstack/staging_event.json
Labels: enhancement, Category:Cloud

#1531 Update Query Filtering to be based on acls again
  bin/acl-config
  classes/Models/Services/Parameters.php
  classes/XDUser.php
  configuration/etl/etl.d/acls-import.json
  configuration/etl/etl.d/acls-xdmod-management.json
  configuration/etl/etl_sql.d/acls/xdmod/update_user_acl_group_by_parameters.sql
  configuration/etl/etl_tables.d/acls/acl_dimensions.json
  configuration/etl/etl_tables.d/acls/staging/acl_dimensions.json
  tests/artifacts/xdmod/parameters/input/parameters.json
  tests/artifacts/xdmod/parameters/output/centerdirector_cd.json
  tests/artifacts/xdmod/parameters/output/centerdirector_cs.json
  tests/artifacts/xdmod/parameters/output/centerdirector_pi.json
  tests/artifacts/xdmod/parameters/output/centerdirector_pub.json
  tests/artifacts/xdmod/parameters/output/centerdirector_usr.json
  tests/artifacts/xdmod/parameters/output/centerstaff_cd.json
  tests/artifacts/xdmod/parameters/output/centerstaff_cs.json
  tests/artifacts/xdmod/parameters/output/centerstaff_pi.json
  tests/artifacts/xdmod/parameters/output/centerstaff_pub.json
  tests/artifacts/xdmod/parameters/output/centerstaff_usr.json
  tests/artifacts/xdmod/parameters/output/empty.json
  tests/artifacts/xdmod/parameters/output/normaluser_cd.json
  tests/artifacts/xdmod/parameters/output/normaluser_cs.json
  tests/artifacts/xdmod/parameters/output/normaluser_pi.json
  tests/artifacts/xdmod/parameters/output/normaluser_pub.json
  tests/artifacts/xdmod/parameters/output/normaluser_usr.json
  tests/artifacts/xdmod/parameters/output/principal_cd.json
  tests/artifacts/xdmod/parameters/output/principal_cs.json
  tests/artifacts/xdmod/parameters/output/principal_pi.json
  tests/artifacts/xdmod/parameters/output/principal_pub.json
  tests/artifacts/xdmod/parameters/output/principal_usr.json
  tests/artifacts/xdmod/parameters/output/public_user_cd.json
  tests/artifacts/xdmod/parameters/output/public_user_cs.json
  tests/artifacts/xdmod/parameters/output/public_user_pi.json
  tests/artifacts/xdmod/parameters/output/public_user_pub.json
  tests/component/lib/ParametersTest.php
Labels: enhancement, Category:Infrastructure

#1576 Convert tables in mod_logger, mod_hpcdb, and mod_shredder to InnoDB
  configuration/etl/etl.d/xdmod-migration-9_5_0-10_0_0.json
  configuration/etl/etl_sql.d/migrations/9.5.0-10.0.0/mod_logger/convert_to_innodb.sql
  configuration/etl/etl_tables.d/common/hpcdb/schema-version-history.json
  configuration/etl/etl_tables.d/common/shredder/schema-version-history.json
  db/schema/mod_logger.sql
Labels: enhancement, Category:General

#1577 Updating acl_dimension_staging population query
  bin/acl-config
Labels: bug, Category:ACL, autodoc:ignore

#1573 Convert tables in modw database to the innodb table engine
  configuration/etl/etl.d/xdmod-migration-9_5_0-10_0_0.json
  configuration/etl/etl_tables.d/jobs/countable_type.json
  configuration/etl/etl_tables.d/jobs/job_record_type.json
  configuration/etl/etl_tables.d/jobs/job_task_countable.json
  configuration/etl/etl_tables.d/jobs/job_task_type.json
  configuration/etl/etl_tables.d/jobs/meta_job.json
  configuration/etl/etl_tables.d/jobs/meta_job_record.json
  configuration/etl/etl_tables.d/jobs/submission_venue.json
  configuration/etl/etl_tables.d/jobs/unit.json
  configuration/etl/etl_tables.d/jobs/xdw/account.json
  configuration/etl/etl_tables.d/jobs/xdw/allocation-breakdown.json
  configuration/etl/etl_tables.d/jobs/xdw/allocation-on-resource.json
  configuration/etl/etl_tables.d/jobs/xdw/allocation.json
  configuration/etl/etl_tables.d/jobs/xdw/days.json
  configuration/etl/etl_tables.d/jobs/xdw/error-descriptions.json
  configuration/etl/etl_tables.d/jobs/xdw/field-of-science-hierarchy.json
  configuration/etl/etl_tables.d/jobs/xdw/field-of-science.json
  configuration/etl/etl_tables.d/jobs/xdw/gpu-buckets.json
  configuration/etl/etl_tables.d/jobs/xdw/hosts.json
  configuration/etl/etl_tables.d/jobs/xdw/job-records.json
  configuration/etl/etl_tables.d/jobs/xdw/job-tasks.json
  configuration/etl/etl_tables.d/jobs/xdw/job-times.json
  configuration/etl/etl_tables.d/jobs/xdw/job-wait-times.json
  configuration/etl/etl_tables.d/jobs/xdw/jobhosts.json
  configuration/etl/etl_tables.d/jobs/xdw/months.json
  configuration/etl/etl_tables.d/jobs/xdw/organization.json
  configuration/etl/etl_tables.d/jobs/xdw/people-under-pi.json
  configuration/etl/etl_tables.d/jobs/xdw/person.json
  configuration/etl/etl_tables.d/jobs/xdw/piperson.json
  configuration/etl/etl_tables.d/jobs/xdw/principal-investigator.json
  configuration/etl/etl_tables.d/jobs/xdw/processor-buckets.json
  configuration/etl/etl_tables.d/jobs/xdw/quarters.json
  configuration/etl/etl_tables.d/jobs/xdw/queue.json
  configuration/etl/etl_tables.d/jobs/xdw/request.json
  configuration/etl/etl_tables.d/jobs/xdw/resource-fact.json
  configuration/etl/etl_tables.d/jobs/xdw/resource-type.json
  configuration/etl/etl_tables.d/jobs/xdw/schema-version-history.json
  configuration/etl/etl_tables.d/jobs/xdw/service-provider.json
  configuration/etl/etl_tables.d/jobs/xdw/staging-jobhosts.json
  configuration/etl/etl_tables.d/jobs/xdw/system-account.json
  configuration/etl/etl_tables.d/jobs/xdw/years.json
  configuration/etl/etl_tables.d/storage/xdw/mountpoint.json
  configuration/etl/etl_tables.d/storage/xdw/storagefact.json
Labels: enhancement, Category:General

#1559 Move XSEDE-specific code to the XSEDE module.
  classes/Rest/Controllers/SummaryStatisticsControllerProvider.php
  configuration/rest.d/summary_statistics.json
Labels: maintenance / code quality, autodoc:ignore

#1532 Add exportJson function back.
  classes/DataWarehouse/Data/TimeseriesDataset.php
  tests/integration/lib/Controllers/UsageExplorerTest.php
Labels: bug

#1582 Add index to mod_logger.log_table for help with better query planning
  configuration/etl/etl_sql.d/migrations/9.5.0-10.0.0/mod_logger/convert_to_innodb.sql
  db/schema/mod_logger.sql
Labels: enhancement, Category:General

#1586 Add SHOW WARNINGS to StructuredFileIngestor
  classes/ETL/Ingestor/StructuredFileIngestor.php
Labels: bug, Category:ETL

#1585 Convert tables in moddb database to the InnoDB table engine
  configuration/etl/etl.d/xdmod-migration-9_5_0-10_0_0.json
  configuration/etl/etl_tables.d/acls/report-template-acls-staging.json
  configuration/etl/etl_tables.d/xdb/account-requests.json
  configuration/etl/etl_tables.d/xdb/api-keys.json
  configuration/etl/etl_tables.d/xdb/chart-pool.json
  configuration/etl/etl_tables.d/xdb/colors.json
  configuration/etl/etl_tables.d/xdb/exception-email-addresses.json
  configuration/etl/etl_tables.d/xdb/report-template-charts.json
  configuration/etl/etl_tables.d/xdb/report-templates.json
  configuration/etl/etl_tables.d/xdb/reports.json
  configuration/etl/etl_tables.d/xdb/restx509.json
  configuration/etl/etl_tables.d/xdb/schema-version-history.json
  configuration/etl/etl_tables.d/xdb/session-manager.json
  configuration/etl/etl_tables.d/xdb/user-profiles.json
  configuration/etl/etl_tables.d/xdb/user-types.json
  configuration/etl/etl_tables.d/xdb/version-check.json
Labels: enhancement, Category:General

#1590 Remove unused function
  classes/XDUser.php
Labels: maintenance / code quality, autodoc:ignore

#1591 Add missing test output
  tests/artifacts/xdmod/parameters/output/centerdirector_user.json
  tests/artifacts/xdmod/parameters/output/centerstaff_user.json
  tests/artifacts/xdmod/parameters/output/normaluser_user.json
  tests/artifacts/xdmod/parameters/output/principal_user.json
  tests/artifacts/xdmod/parameters/output/public_user_user.json
  tests/component/lib/ParametersTest.php
Labels: maintenance / code quality, autodoc:ignore

#1525 Fix shredder empty line checking
  classes/OpenXdmod/Shredder.php
Labels: bug, Category:ETL

#1593 Replace use of "shredder" ETL config
  configuration/etl/etl.d/xdmod-migration-9_5_0-10_0_0.json
Labels: bug, autodoc:ignore

#1580 Performance improvements to ETLv2 action that loads queues for jobs realm
  configuration/etl/etl_action_defs.d/jobs/xdw/queue.json
Labels: enhancement, Category:ETL

#1578 Update Metric Explorer Controller to include ability to show all possible dimension values.
  classes/DataWarehouse/Access/MetricExplorer.php
  classes/Realm/GroupBy.php
  classes/Realm/iGroupBy.php
Labels: new feature

#1581 Updates to mod_logger tables
  classes/CCR/CCRDBHandler.php
  configuration/etl/etl.d/xdmod-migration-9_5_0-10_0_0.json
  configuration/etl/etl_sql.d/migrations/9.5.0-10.0.0/mod_logger/alter_log_id_seq.sql
  db/data/mod_logger.sql
  db/schema/mod_logger.sql
Labels: bug, autodoc:ignore, Category:Infrastructure

#1588 Updated etl_profile.js to add an extra group_by parameter "show_all_dimension_values".
  etl/js/lib/etl_profile.js
Labels: new feature

#1584 Convert tables in modw_aggregates to InnoDB and add class to manage aggregate tables
  classes/ETL/Maintenance/MaintenanceOptions.php
  classes/ETL/Maintenance/ManageAggregateTables.php
  configuration/etl/etl.d/xdmod-migration-9_5_0-10_0_0.json
  configuration/etl/etl_tables.d/jobs/xdw/jobfact_by_.json
  configuration/etl/etl_tables.d/jobs/xdw/jobfact_by_day.json
  configuration/etl/etl_tables.d/storage/xdw/storagefact.aggregation.json
Labels: enhancement, Category:General

#1579 InnoDB Performance Improvements for ingestion and aggregation
  classes/OpenXdmod/Migration/Version950To1000/DatabasesMigration.php
  configuration/etl/etl.d/xdmod-migration-9_5_0-10_0_0.json
  configuration/etl/etl_tables.d/cloud_common/cloud_resource_specs.json
  configuration/etl/etl_tables.d/jobs/xdw/job-tasks.json
  configuration/etl/etl_tables.d/jobs/xdw/jobfact_by_day.json
  configuration/etl/etl_tables.d/storage/xdw/storagefact.json
Labels: enhancement, Category:General

#1594 Set minimum username length to 2.
  configuration/constants.php
  html/gui/js/CCR.js
Labels: bug

#1595 Fix null QOS ID
  configuration/etl/etl_action_defs.d/jobs/hpcdb/jobs.json
  configuration/etl/etl_action_defs.d/jobs/xdw/job-records-job-tasks.json
Labels: bug, autodoc:ignore

#1596 Replace use of "hpcdb" ETL config
  configuration/etl/etl.d/xdmod-migration-9_5_0-10_0_0.json
Labels: bug, autodoc:ignore

#1597 Adding index to nodecount column
  configuration/etl/etl_tables.d/jobs/hpcdb/jobs.json
Labels: enhancement, Category:ETL, autodoc:ignore

#1592 Fix warnings seen when ingesting cloud or storage files
  classes/OpenXdmod/Migration/Version950To1000/DatabasesMigration.php
  configuration/etl/etl.d/xdmod-migration-9_5_0-10_0_0.json
  configuration/etl/etl_action_defs.d/cloud_common/staging_resource_specifications.json
  configuration/etl/etl_action_defs.d/storage/hpcdb/usage.json
  configuration/etl/etl_tables.d/cloud_common/raw_resource_specs.json
  configuration/etl/etl_tables.d/cloud_openstack/raw_event.json
  configuration/etl/etl_tables.d/storage/staging/usage.json
Labels: enhancement, Category:ETL

#1599 Replace use of "shredder" ETL config
  configuration/etl/etl.d/xdmod-migration-9_5_0-10_0_0.json
Labels: bug, autodoc:ignore
