Repository ubccr/xdmod, pull requests merged in 2021-03, with the labels that each got.

#1499 Circleci project setup
  .circleci/config.yml
  tests/ci/samlSetup.sh
  tests/ui/test/specs/xdmod/SSOLogin.js
  tests/ui/test/specs/xdmod/internalDashboard.js
Labels: Category:Infrastructure, maintenance / code quality

#1503 Improve input validation for download_report controller
  html/controllers/report_builder/download_report.php
  tests/integration/lib/Controllers/ReportBuilderTest.php
Labels: bug

#1506 Add missing attributes when gearing over from Usage to Metric
  html/gui/js/modules/Usage.js
Labels: bug

#1508 Ensure "Don't show me this" checkbox is honoured
  html/gui/js/modules/Dashboard.js
Labels: bug

#1510 Updating file permissions for XDMoD's bin directory
  docs/install-source.md
  open_xdmod/modules/xdmod/xdmod.spec.in
Labels: Category:Infrastructure, security

#1507 Ensure dashboard is updated whenever reports change.
  html/gui/js/report_builder/ReportsOverview.js
Labels: bug

#1511 Changing constraints on cloud resource specifications tables to prevent extra rows
  classes/OpenXdmod/Migration/Version900To950/DatabaseMigration.php
  configuration/etl/etl_tables.d/cloud_common/cloud_resource_specs.json
  configuration/etl/etl_tables.d/cloud_common/staging_resource_specifications.json
Labels: Category:Cloud, bug

#1504 Fix extraneous cloud sessions
  classes/ETL/Aggregator/JobListAggregator.php
  configuration/etl/etl.d/cloud_state_machine.json
  configuration/etl/etl.d/jobs_cloud_common.json
  configuration/etl/etl_sql.d/cloud_common/delete_session_records.sql
Labels: Category:Cloud, bug

#1512 Break cloud migration into two pipelines
  classes/OpenXdmod/Migration/Version900To950/DatabaseMigration.php
  configuration/etl/etl.d/xdmod-migration-9_0_0-9_5_0.json
Labels: Category:Cloud, autodoc:ignore

#1513 Add an index to the modw.jobhosts table to help with queries in the federated module
  configuration/etl/etl_tables.d/jobs/xdw/jobhosts.json
Labels: Category:ETL, autodoc:ignore

#1515 Add walltime_accuracy metric to job summary data.
  classes/DataWarehouse/Query/Jobs/RawData.php
Labels: Category:General, new feature

#1516 Updated the upgrade guide documentation to include information on re-ingesting cloud data due to memory buckets bug fix.
  docs/upgrade.md
Labels: documentation

#1505 Update simple SAML documentation to mention the icon.
  docs/simpleSAMLphp.md
Labels: documentation

#1514 Updating pipelines that get run when ingesting data in generic cloud data format
  classes/OpenXdmod/DataWarehouseInitializer.php
Labels: Category:Cloud

#1509 Create Gateways realm installation instructions
  docs/_data/toc.yml
  docs/gateways-realm.md
Labels: documentation

#1518 Add columns to cloudfact_by_day aggregation
  configuration/etl/etl_action_defs.d/cloud_common/cloud_metrics_aggregation_by_day.json
Labels: Category:Cloud, autodoc:ignore

#1469 Improve robustness of full groupby checking
  classes/ETL/Aggregator/pdoAggregator.php
  classes/ETL/DbModel/Table.php
  configuration/etl/etl_action_defs.d/jobs/hpc-aggregation-day.json
  configuration/etl/etl_action_defs.d/jobs/hpc-aggregation.json
  etl/js/lib/etl_profile.js
  etl/js/lib/etlv2.js
Labels: bug

#1483 Add data endpoint that can parse webserver logs.
  classes/ETL/DataEndpoint/WebServerLogFile.php
  classes/ETL/Ingestor/RegexTransformIngestor.php
  composer.json
  composer.lock
  configuration/resource_types.json
  docs/notices.md
Labels: Category:ETL, enhancement

#1520 Fix SUPReMM data warehouse export regression
  classes/DataWarehouse/Data/BatchDataset.php
  classes/DataWarehouse/Data/RawStatisticsConfiguration.php
  tests/artifacts/xdmod/schema/warehouse-export/GET-realms.schema.json
  tests/integration/lib/Rest/WarehouseExportControllerTest.php
Labels: Category:Data Warehouse Export, bug
