Repository ubccr/xdmod, pull requests merged in 2021-02, with the labels that each got.

#1487 Fix mysql command line defaults file option
  classes/CCR/DB/MySQLHelper.php
Labels: bug

#1492 Fix bug in language definition in main html page.
  html/index.php
Labels: bug

#1493 Updating the logging code to not throw away all class information
  classes/CCR/Logger.php
Labels: Category:Infrastructure, bug

#1495 Fix data encoding in etlv2 pdoIngestor
  classes/ETL/Ingestor/pdoIngestor.php
Labels: Category:ETL, bug

#1496 Removing Dependencies for Jaspersoft
  composer.json
  composer.lock
  composer.scripts.php
Labels: Category:Infrastructure, dependencies

#1489 Move to using custom Ingestor for cloud resource specifications
  classes/ETL/Ingestor/CloudResourceSpecsStateTransformIngestor.php
  configuration/etl/etl.d/cloud_ingest_resource_specs.json
  configuration/etl/etl.d/xdmod-migration-9_0_0-9_5_0.json
  configuration/etl/etl_action_defs.d/cloud_common/resource_specifications_transformer.json
  configuration/etl/etl_tables.d/cloud_common/cloud_resource_specs.json
  tests/artifacts/xdmod/etlv2/configuration/input/etl_action_defs_8.0.0.d/cloud_resource_specs_state.json
  tests/artifacts/xdmod/etlv2/configuration/input/etl_tables_8.0.0.d/cloud_resource_specs.json
  tests/component/lib/ETL/CloudResourceSpecsStateTransformIngestorTest.php
Labels: Category:Cloud, bug

#1500 Add indexes that will help federated module ingest be faster
  configuration/etl/etl_tables.d/jobs/xdw/hosts.json
  configuration/etl/etl_tables.d/jobs/xdw/job-tasks.json
Labels: Category:General, enhancement
