Repository ubccr/xdmod, pull requests merged in 2022-01, with the labels that each got.

#1561 Enabled text selection / copying in Job Viewer Accounting Tab
  html/gui/css/viewer.css
  html/gui/js/modules/job_viewer/JobViewer.js
Labels: enhancement, Category:Job Viewer

#1600 Adding migration pipeline to put dates in cloud resource specs and storage tables into correct format on upgrade
  configuration/etl/etl.d/xdmod-migration-9_5_0-10_0_0.json
  configuration/etl/etl_sql.d/migrations/9.5.0-10.0.0/mod_shredder/update_storage_datetimes.sql
  configuration/etl/etl_sql.d/migrations/9.5.0-10.0.0/modw_cloud/update_cloud_resource_datetimes.sql
  tests/ci/bootstrap.sh
Labels: bug, Category:ETL

#1486 XDMoD - PHP 7.2, MariaDB 10.3 Update
  .circleci/config.yml
  classes/DataWarehouse/Data/TimeseriesDataset.php
  classes/ETL/DbModel/Column.php
  classes/ETL/DbModel/Table.php
  classes/ETL/JsonPointer.php
  classes/ETL/Utilities.php
  classes/Models/Services/Users.php
  open_xdmod/modules/xdmod/xdmod.spec.in
  tests/artifacts/xdmod/regression/images/expected-centos8.json
  tests/component/lib/ETL/BaseEtlTest.php
  tests/integration/lib/Controllers/UsageExplorerTest.php
  tests/integration/lib/Controllers/UserInterfaceTest.php
  tests/integration/lib/Database/ResourceNamesTest.php
  tests/regression/lib/Controllers/UsageChartsTest.php
  tests/regression/lib/TestHarness/RegressionTestHelper.php
  tests/ui/test/specs/xdmod/SSOLogin.js
  tests/ui/test/specs/xdmod/internalDashboard.js
  tests/ui/wdio.conf.js
  tests/unit/lib/ETL/DbModel/DbModelTest.php
Labels: enhancement, experiment, Category:General, dependencies

#1598 Add script to help convert to using innodb-file-per-table mysql setting
  bin/xdmod-convert-innodb-fpt
Labels: new feature, Category:General

#1602 Change table exists checks to use dedicated connections.
  classes/OpenXdmod/Migration/Version950To1000/DatabasesMigration.php
Labels: bug, autodoc:ignore
