Repository ubccr/xdmod, pull requests merged in 2022-05, with the labels that each got.

#1607 CentOS8 / Rocky Linux XDMoD Docker
  .circleci/config.yml
  classes/Rest/Controllers/WarehouseControllerProvider.php
  tests/artifacts/xdmod/regression/images/expected-rocky8.5.json
  tests/ci/Docker/Dockerfile.centos8
  tests/ci/Docker/Dockerfile.centos8.xdmod-base
  tests/ci/Docker/Dockerfile.rocky8
  tests/ci/Docker/Dockerfile.rocky8.xdmod-base
  tests/ci/Docker/assets/google-chrome.repo
  tests/ci/Docker/assets/mysql-server.cnf
  tests/ci/Docker/bin/services
  tests/ci/bootstrap.sh
Labels: maintenance / code quality, Category:Infrastructure

#1629 Update XMS team members list
  AUTHORS.md
  html/about/team.html
Labels: documentation, Category:General

#1628 Adding post data & total elapsed request time
  classes/Rest/XdmodApplicationFactory.php
Labels: new feature, Category:Infrastructure

#1633 Update broken SimpleSAMLphp links
  docs/simpleSAMLphp-ldap.md
  docs/simpleSAMLphp.md
  tests/ci/samlSetup.sh
Labels: documentation, Category:General

#1627 Update NSF award grant numbers
  docs/index.md
  html/gui/js/CCR.js
Labels: documentation, Category:General

#1626 Change REST API documentation page title
  docs/rest.html
Labels: documentation, Category:General, autodoc:ignore

#1625 Add data export REST API documentation
  docs/xdmod-rest-schema.json
Labels: documentation, autodoc:ignore, Category:Data Warehouse Export
