Repository ubccr/xdmod, pull requests merged in 2022-08, with the labels that each got.

#1665 Bypass Login Modal for SSO
  html/gui/js/CCR.js
  html/index.php
Labels: experiment, Category:General

#1669 Update Contact Us button for ACCESS XDMoD
  html/gui/js/CCR.js
  html/index.php
Labels: enhancement

#1668 Update XMS team members
  html/about/team.html
Labels: documentation
