Repository ubccr/xdmod, pull requests merged in 2022-07, with the labels that each got.

#1656 Adding mongodb dependencies to XDMoD
  .circleci/config.yml
  README.md
  composer-el7.json
  composer-el7.lock
  composer-el8.json
  composer-el8.lock
Labels: Category:Infrastructure, dependencies

#1655 Refactor duplicate code
  classes/CCR/DB/MySQLHelper.php
  classes/XDReportManager.php
  libraries/utilities.php
Labels: maintenance / code quality, autodoc:ignore

#1657 Additional php7 updates
  classes/ETL/Ingestor/ExplodeTransformIngestor.php
  classes/Rest/Controllers/WarehouseControllerProvider.php
Labels: bug, maintenance / code quality, Category:Infrastructure
