Repository ubccr/xdmod, pull requests merged in 2022-06, with the labels that each got.

#1644 Update PHP and MariaDB version requirements
  bin/xdmod-check-config
  docs/software-requirements.md
Labels: documentation, autodoc:ignore

#1647 Add CircleCI configuration to ignore gh-pages
  .circleci/config.yml
Labels: qa / testing, autodoc:ignore, Category:Infrastructure

#1637 Remove unused xd_utilities functions
  libraries/utilities.php
Labels: maintenance / code quality, Category:General

#1649 Update presentation links in About tab
  html/about/presentations.html
Labels: bug, Category:General

#1632 Add batch process details to data export documentation
  docs/dw-export.md
Labels: documentation, Category:Data Warehouse Export

#1648 Add configuration option to disable data export
  classes/DataWarehouse/Data/RawStatisticsConfiguration.php
  tests/component/lib/Export/RawStatisticsConfigurationTest.php
Labels: enhancement, Category:Data Warehouse Export

#1638 Update regression test
  tests/regression/lib/Controllers/UsageExplorerJobsTest.php
Labels: qa / testing, autodoc:ignore

#1652 Updating the datasetid float comparison (PHP7.2) (#1612)
  html/controllers/metric_explorer/get_rawdata.php
  html/gui/js/AddDataPanel.js
Labels: bug, Category:Metric Explorer, autodoc:ignore

#1623 Handle Lost connection to MySQL server
  classes/CCR/CCRDBHandler.php
Labels: bug, Category:ETL

#1631 Convert mod_logger schema to ETL managed configuration
  classes/OpenXdmod/Setup/DatabaseSetup.php
  classes/OpenXdmod/Shared/DatabaseHelper.php
  configuration/etl/etl.d/logger.json
  configuration/etl/etl_action_defs.d/logger/log_id_seq.json
  configuration/etl/etl_action_defs.d/logger/log_level.json
  configuration/etl/etl_data.d/logger/log_id_seq.json
  configuration/etl/etl_data.d/logger/log_level.json
  configuration/etl/etl_tables.d/logger/log_id_seq.json
  configuration/etl/etl_tables.d/logger/log_level.json
  configuration/etl/etl_tables.d/logger/log_table.json
  db/data/mod_logger.sql
  db/schema/mod_hpcdb.sql
  db/schema/mod_logger.sql
  db/schema/mod_shredder.sql
  db/schema/moddb.sql
  db/schema/modw.sql
  db/schema/modw_aggregates.sql
  db/schema/modw_filters.sql
  open_xdmod/modules/xdmod/build.json
Labels: enhancement, Category:ETL

#1653 Revert removal of database initialization code
  classes/OpenXdmod/Shared/DatabaseHelper.php
Labels: bug, autodoc:ignore

#1624 Fix rare race condition that causes process to not exit.
  etl/js/lib/dataset_processor.js
Labels: bug

#1635 Prevent MySQL CLI from using user-specific options
  classes/CCR/DB/MySQLHelper.php
Labels: bug, Category:General

#1639 Add support for Altair PBS GPU data
  classes/OpenXdmod/Shredder/Pbs.php
  docs/gpu-metrics.md
  tests/artifacts/xdmod/unit/shredder/pbs/input/accounting-logs.log
  tests/artifacts/xdmod/unit/shredder/pbs/output/accounting-logs.json
Labels: enhancement, Category:ETL

#1630 Add support for Grid Engine GPU data
  classes/OpenXdmod/Shredder/Sge.php
  configuration/etl/etl.d/xdmod-migration-10_0_0-10_5_0.json
  configuration/etl/etl_tables.d/jobs/shredder/job-sge.json
  docs/gpu-metrics.md
  tests/artifacts/xdmod/unit/shredder/uge/input/accounting-logs.log
  tests/artifacts/xdmod/unit/shredder/uge/output/accounting-logs.json
Labels: enhancement, Category:ETL

#1616 Update usage chart data generation
  tests/regression/README.md
  tests/regression/lib/Controllers/UsageChartsTest.php
Labels: bug, qa / testing, autodoc:ignore

#1654 Add missing variable substitutions
  classes/DataWarehouse/Data/RawStatisticsConfiguration.php
  classes/ETL/aAction.php
Labels: bug, Category:ETL
