Repository ubccr/xdmod, pull requests merged in 2022-03, with the labels that each got.

#1614 Update spec file change log and supported versions
  docs/support.md
  open_xdmod/modules/xdmod/xdmod.spec.in
Labels: documentation, autodoc:ignore

#1613 Update change log
  CHANGELOG.md
  html/about/release_notes/xdmod.html
Labels: autodoc:ignore

#1558 Add rest documentation
  docs/_data/toc.yml
  docs/rest.html
  docs/xdmod-rest-schema.json
Labels: documentation, Category:General

#1615 10.5 boilerplate
  .circleci/config.yml
  CHANGELOG.md
  bin/xdmod-upgrade
  classes/OpenXdmod/Migration/Version1000To1050/ConfigFilesMigration.php
  classes/OpenXdmod/Migration/Version1000To1050/DatabasesMigration.php
  classes/OpenXdmod/Migration/Version950To1000/DatabasesMigration.php
  composer.json
  configuration/etl/etl.d/xdmod-migration-10_0_0-10_5_0.json
  configuration/etl/etl.d/xdmod-migration-9_5_0-10_0_0.json
  configuration/etl/etl_sql.d/migrations/9.5.0-10.0.0/drop_schema_version_history.sql
  configuration/etl/etl_sql.d/migrations/9.5.0-10.0.0/mod_logger/alter_log_id_seq.sql
  configuration/etl/etl_sql.d/migrations/9.5.0-10.0.0/mod_logger/convert_to_innodb.sql
  configuration/etl/etl_sql.d/migrations/9.5.0-10.0.0/mod_shredder/alter-shredded_job_slurm.sql
  configuration/etl/etl_sql.d/migrations/9.5.0-10.0.0/mod_shredder/update_storage_datetimes.sql
  configuration/etl/etl_sql.d/migrations/9.5.0-10.0.0/modw_cloud/convert_innodb_aggregate_tables.sql
  configuration/etl/etl_sql.d/migrations/9.5.0-10.0.0/modw_cloud/update_asset_index.sql
  configuration/etl/etl_sql.d/migrations/9.5.0-10.0.0/modw_cloud/update_cloud_resource_datetimes.sql
  configuration/etl/etl_sql.d/migrations/9.5.0-10.0.0/modw_cloud/update_cloud_resource_specs_host.sql
  configuration/etl/etl_sql.d/migrations/9.5.0-10.0.0/modw_cloud/update_event_index.sql
  configuration/etl/etl_sql.d/migrations/9.5.0-10.0.0/modw_cloud/update_image_index.sql
  configuration/portal_settings.ini
  docs/_config.yml
  docs/upgrade.md
  open_xdmod/modules/xdmod/build.json
  tests/artifacts/xdmod/regression/images/expected-centos8.json
  tests/artifacts/xdmod/regression/images/expected.json
  tests/ci/Docker/Dockerfile
  tests/ci/Docker/Dockerfile.centos7:xdmod-base
  tests/ci/bootstrap.sh
  tests/regression/lib/Controllers/UsageChartsTest.php
  tests/ui/package.json
Labels: autodoc:ignore

#1612 Updating the datasetid float comparison (PHP7.2)
  html/controllers/metric_explorer/get_rawdata.php
  html/gui/js/AddDataPanel.js
Labels: bug, Category:Metric Explorer
