Repository ubccr/xdmod, pull requests merged in 2022-02, with the labels that each got.

#1605 Temporary Fix for Centos8 repo change
  tests/ci/bootstrap.sh
Labels: maintenance / code quality, autodoc:ignore, Category:Infrastructure

#1606 Refactor admin dashboard user listing query and add indexes to Users and SessionManager tables
  classes/XDAdmin.php
  configuration/etl/etl.d/xdmod-migration-9_5_0-10_0_0.json
  configuration/etl/etl_tables.d/xdb/session-manager.json
  configuration/etl/etl_tables.d/xdb/users.json
Labels: enhancement, Category:Internal Dashboard

#1608 Drop schema version history tables
  classes/Xdmod/Version.php
  configuration/etl/etl.d/hpcdb.json
  configuration/etl/etl.d/shredder.json
  configuration/etl/etl.d/xdb.json
  configuration/etl/etl.d/xdmod-migration-9_5_0-10_0_0.json
  configuration/etl/etl_action_defs.d/common/hpcdb/schema-version-history.json
  configuration/etl/etl_action_defs.d/common/shredder/schema-version-history.json
  configuration/etl/etl_action_defs.d/jobs/xdw/schema-version-history.json
  configuration/etl/etl_action_defs.d/xdb/schema-version-history.json
  configuration/etl/etl_data.d/common/hpcdb/schema-version-history.json
  configuration/etl/etl_data.d/common/shredder/schema-version-history.json
  configuration/etl/etl_data.d/jobs/xdw/schema-version-history.json
  configuration/etl/etl_data.d/xdb/schema-version-history.json
  configuration/etl/etl_pipelines.d/jobs-xdw.json
  configuration/etl/etl_sql.d/migrations/9.5.0-10.0.0/drop_schema_version_history.sql
  configuration/etl/etl_sql.d/migrations/9.5.0-10.0.0/mod_logger/convert_to_innodb.sql
  configuration/etl/etl_tables.d/common/hpcdb/schema-version-history.json
  configuration/etl/etl_tables.d/common/shredder/schema-version-history.json
  configuration/etl/etl_tables.d/jobs/xdw/schema-version-history.json
  configuration/etl/etl_tables.d/xdb/schema-version-history.json
  db/data/mod_logger.sql
  db/schema/mod_logger.sql
Labels: maintenance / code quality, Category:Infrastructure

#1609 Fix comment removal in ETL SQL execution
  classes/ETL/Maintenance/ExecuteSql.php
Labels: bug, Category:ETL

#1610 Second attempt to fix db timeouts.
  classes/ETL/Maintenance/ExecuteSql.php
Labels: bug

#1611 Innodb documentation updates
  docs/configuration.md
  docs/upgrade.md
Labels: documentation
