Repository ubccr/xdmod, pull requests merged in 2023-05, with the labels that each got.

#1722 Doc updates rocky8
  docs/latest-releases.md
  docs/software-requirements.md
Labels: documentation, Category:General, autodoc:ignore

#1720 Use more meaningful HTTP responses for API token requests.
  classes/Models/Services/Tokens.php
  classes/Rest/Controllers/BaseControllerProvider.php
  classes/Rest/Controllers/UserControllerProvider.php
  docs/xdmod-rest-schema.json
  html/gui/js/profile_editor/ProfileApiToken.js
  tests/artifacts/xdmod/integration/rest/user/api_token/output/crd.json
  tests/artifacts/xdmod/integration/token_auth/output/errors.json
  tests/integration/lib/Controllers/UserControllerProviderTest.php
  tests/integration/lib/TokenAuthTest.php
Labels: javascript, Category: Data Analytics Framework

#1718 Add API token authorization to controllers.
  docs/xdmod-rest-schema.json
  html/controllers/metric_explorer/get_dimension.php
  html/controllers/user_interface/get_charts.php
  tests/artifacts/xdmod/integration/controllers/metric_explorer/input/get_dimensions.json
  tests/artifacts/xdmod/integration/controllers/metric_explorer/input/get_dw_descripter.json
  tests/artifacts/xdmod/integration/controllers/metric_explorer/input/metric_explorer.json
  tests/artifacts/xdmod/integration/controllers/metric_explorer/output/get_dimensions.json
  tests/artifacts/xdmod/integration/controllers/user_interface/input/get_data.json
  tests/artifacts/xdmod/integration/controllers/user_interface/input/user_interface.json
  tests/artifacts/xdmod/integration/controllers/user_interface/output/get_data.json
  tests/integration/lib/Controllers/MetricExplorerTest.php
  tests/integration/lib/Controllers/UsageExplorerTest.php
Labels: Category:Metric Explorer, Category: Data Analytics Framework

#1727 Update reference regressions test results.
  tests/artifacts/xdmod/regression/current/expected/reference/Jobs/jobwalltime/avg_cpu_hours/aggregate-Day-reference.csv
  tests/artifacts/xdmod/regression/current/expected/reference/Jobs/qos/avg_cpu_hours/aggregate-Month-reference.csv
  tests/artifacts/xdmod/regression/current/expected/reference/Jobs/qos/avg_cpu_hours/aggregate-Quarter-reference.csv
  tests/artifacts/xdmod/regression/current/expected/reference/Jobs/qos/avg_cpu_hours/aggregate-Year-reference.csv
  tests/artifacts/xdmod/regression/current/expected/reference/Jobs/queue/expansion_factor/timeseries-Day-reference.csv
Labels: maintenance / code quality, autodoc:ignore

#1721 Create REST endpoints for getting raw data.
  classes/DataWarehouse/Data/BatchDataset.php
  classes/Rest/Controllers/WarehouseControllerProvider.php
  configuration/portal_settings.ini
  docs/xdmod-rest-schema.json
  templates/portal_settings.template
  tests/artifacts/xdmod/integration/rest/warehouse/input/get_raw_data.json
  tests/artifacts/xdmod/integration/rest/warehouse/input/get_raw_data_limit.json
  tests/artifacts/xdmod/integration/rest/warehouse/output/get_raw_data.json
  tests/artifacts/xdmod/integration/rest/warehouse/output/get_raw_data_limit.json
  tests/integration/lib/Rest/WarehouseControllerProviderTest.php
Labels: new feature, Category:Data Warehouse Export, Category: Data Analytics Framework
