Repository ubccr/xdmod, pull requests merged in 2023-01, with the labels that each got.

#1686 Updating link to sign up for mailing list
  docs/index.md
  docs/support.md
Labels: documentation, autodoc:ignore

#1682 Add docs for how to reconstruct Slurm logs from XDMoD
  docs/howto-reconstruct-slurm.md
  docs/howto.md
Labels: documentation

#1687 Update links for XSEDE->ACCESS transition.
  html/about/images/Case_Western_logo.png
  html/about/images/SDSC_logo.jpg
  html/about/images/Tufts_logo.png
  html/about/images/access_logo.png
  html/about/images/indianauniversity_logo.jpg
  html/about/images/xsede_logo.jpg
  html/about/links.html
Labels: maintenance / code quality

#1688 Handle change to output of chromium 109
  libraries/charting.php
Labels: maintenance / code quality

#1453 Remove unused function
  etl/js/config.js
  etl/js/lib/etl_profile.js
Labels: Category:ETL, maintenance / code quality, autodoc:ignore

#1634 Set the yaxis range for charts that show percentage values.
  classes/Rest/Controllers/WarehouseControllerProvider.php
  html/gui/js/modules/job_viewer/ChartPanel.js
Labels: bug, Category:Job Viewer

#1689 Removing the acct.request table
  classes/DataWarehouse.php
Labels: bug, Category:Allocations
