Repository ubccr/xdmod, pull requests merged in 2023-04, with the labels that each got.

#1711 Update version number to 10.0.2
  CHANGELOG.md
  bin/xdmod-upgrade
  classes/OpenXdmod/Migration/Version1001To1002/ConfigFilesMigration.php
  configuration/portal_settings.ini
  docs/_config.yml
  docs/software-requirements.md
  docs/upgrade.md
  html/about/release_notes/xdmod.html
  open_xdmod/modules/xdmod/build.json
  open_xdmod/modules/xdmod/xdmod.spec.in
Labels: version sync, Category:General, autodoc:ignore

#1713 Prevent "undefined offset" error when exporting empty timeseries datasets.
  classes/DataWarehouse/Data/TimeseriesDataset.php
  tests/integration/lib/Controllers/UsageExplorerTest.php
Labels: bug, Category:Data Warehouse Export

#1715 Merge 10.0 changes into 10.5
  .circleci/config.yml
  CHANGELOG.md
  background_scripts/chrome-helper/.eslintrc.json
  background_scripts/chrome-helper/chrome-helper.js
  background_scripts/chrome-helper/package-lock.json
  background_scripts/chrome-helper/package.json
  bin/xdmod-upgrade
  classes/OpenXdmod/Migration/Version1000To1001/ConfigFilesMigration.php
  classes/OpenXdmod/Migration/Version1001To1002/ConfigFilesMigration.php
  classes/OpenXdmod/Migration/Version1002To1050/ConfigFilesMigration.php
  classes/OpenXdmod/Migration/Version1002To1050/DatabasesMigration.php
  configuration/constants.php
  configuration/etl/etl.d/xdmod-migration-10_0_2-10_5_0.json
  docs/_config.yml
  docs/index.md
  docs/latest-releases.md
  docs/software-requirements.md
  docs/support.md
  html/about/release_notes/xdmod.html
  libraries/charting.php
  open_xdmod/build_scripts/templates/install.template
  open_xdmod/modules/xdmod/assets/setup.sh
  open_xdmod/modules/xdmod/xdmod.spec.in
Labels: autodoc:ignore

#1716 Add new paper from Vipin Chaudhary
  html/about/publications.html
Labels: documentation, Category:General, autodoc:ignore

#1719 Include is_null check in RegressionTestHelper when checking json_decoded data
  tests/regression/lib/TestHarness/RegressionTestHelper.php
Labels: bug, Category:General

#1693 Fix formatting of nested lists and update composer versions in `README.md`.
  README.md
Labels: documentation

#1694 Add API token GUI components to "My Profile" window.
  html/gui/css/ProfileEditor.css
  html/gui/js/profile_editor/ProfileApiToken.js
  html/gui/js/profile_editor/ProfileEditor.js
  html/gui/js/profile_editor/ProfileGeneralSettings.js
  html/index.php
Labels: new feature, javascript, Category: Data Analytics Framework

#1700 Fix REST schema documentation errors reported by Swagger Editor.
  docs/xdmod-rest-schema.json
Labels: documentation

#1697 Make "My Profile" window stateless to avoid cutting off content.
  html/gui/js/profile_editor/ProfileEditor.js
Labels: bug, javascript
