Repository ubccr/xdmod, pull requests merged in 2023-10, with the labels that each got.

#1777 Update XDMoD to 11.0
  .circleci/config.yml
  bin/xdmod-upgrade
  classes/OpenXdmod/Migration/Version1000To1001/ConfigFilesMigration.php
  classes/OpenXdmod/Migration/Version1001To1002/ConfigFilesMigration.php
  classes/OpenXdmod/Migration/Version1002To1003/ConfigFilesMigration.php
  classes/OpenXdmod/Migration/Version1003To1050/DatabasesMigration.php
  classes/OpenXdmod/Migration/Version1050To1100/ConfigFilesMigration.php
  composer-el7.json
  composer-el7.lock
  composer.json
  composer.lock
  configuration/etl/etl.d/xdmod-migration-10_0_3-10_5_0.json
  configuration/etl/etl.d/xdmod-migration-10_5_0-11_0_0.json
  configuration/portal_settings.ini
  docs/_config.yml
  open_xdmod/modules/xdmod/build.json
Labels: autodoc:ignore, Category:Infrastructure

#1774 Updating Source Install Instructions
  docs/install-source.md
Labels: Category:General, autodoc:ignore

#1775 Add pearc23 access paper
  html/about/publications.html
Labels: Category:General

#1781 Make `Ctrl-C` interrupt regression test subprocesses.
  tests/regression/runtests.sh
Labels: qa / testing

#1733 Catch PHP command-line errors in CircleCI.
  .circleci/config.yml
  tests/ci/bootstrap.sh
  tests/integration/lib/BaseTest.php
  tests/integration/lib/TokenAuthTest.php
Labels: qa / testing
