Repository ubccr/xdmod, pull requests merged in 2023-03, with the labels that each got.

#1695 API Token Framework
  classes/Models/Services/Tokens.php
  classes/Rest/Controllers/BaseControllerProvider.php
  classes/Rest/Controllers/UserControllerProvider.php
  classes/Rest/Controllers/WarehouseExportControllerProvider.php
  configuration/etl/etl.d/acls-xdmod-management.json
  configuration/etl/etl.d/xdmod-migration-10_0_0-10_5_0.json
  configuration/etl/etl_tables.d/acls/user_tokens.json
  configuration/portal_settings.ini
  docs/xdmod-rest-schema.json
  html/controllers/metric_explorer/get_dw_descripter.php
  templates/portal_settings.template
  tests/artifacts/xdmod/schema/integration/authentication_error.spec.json
  tests/artifacts/xdmod/schema/integration/create_user_token_failure.spec.json
  tests/artifacts/xdmod/schema/integration/create_user_token_success.spec.json
  tests/artifacts/xdmod/schema/integration/get_user_token_failure.spec.json
  tests/artifacts/xdmod/schema/integration/get_user_token_success.spec.json
  tests/artifacts/xdmod/schema/integration/revoke_user_token_failure.spec.json
  tests/artifacts/xdmod/schema/integration/revoke_user_token_success.spec.json
  tests/artifacts/xdmod/schema/integration/session_expired.spec.json
  tests/artifacts/xdmod/user_controller/input/create_api_tokens.json
  tests/artifacts/xdmod/user_controller/input/create_api_tokens_defaults.json
  tests/artifacts/xdmod/user_controller/input/test_endpoint_token_auth.json
  tests/artifacts/xdmod/user_controller/input/test_endpoint_token_auth_defaults.json
  tests/artifacts/xdmod/user_controller/input/test_rest_token_auth_defaults.json
  tests/artifacts/xdmod/user_controller/input/token_auth_defaults.json
  tests/artifacts/xdmod/user_controller/output/get_dw_descripter.json
  tests/artifacts/xdmod/user_controller/output/get_realms.json
  tests/artifacts/xdmod/user_controller/output/token_unauthorized.json
  tests/integration/lib/Controllers/UserControllerProviderTest.php
  tests/integration/lib/TestHarness/TokenHelper.php
  tests/integration/lib/TestHarness/Utilities.php
Labels: new feature, Category: Data Analytics Framework

#1698 Prevent unrendered windows from attempting to sync shadows.
  html/gui/js/CCR.js
Labels: bug, javascript

#1703 Updates for publications, presentations, and team members
  html/about/presentations.html
  html/about/publications.html
  html/about/team.html
Labels: documentation
