Repository ubccr/xdmod, pull requests merged in 2024-03, with the labels that each got.

#1810 Adding OpenID Connect Instructions for SSO
  docs/openidc.md
  docs/simpleSAMLphp.md
Labels: documentation, Category:General

#1809 Updating Rest Logging to include the username
  classes/CCR/Logger.php
  classes/CCR/RequestLogger.php
  classes/Rest/XdmodApplicationFactory.php
  configuration/etl/etl.d/xdmod-migration-10_5_0-11_0_0.json
  configuration/etl/etl_sql.d/migration/cleanup_log_table.sql
Labels: data quality, Category:Infrastructure

#1826 Changing etlv2 endpoint config value used for migration etlv2 actions
  configuration/etl/etl.d/xdmod-migration-10_5_0-11_0_0.json
Labels: autodoc:ignore
