Repository ubccr/xdmod, pull requests merged in 2024-08, with the labels that each got.

#1894 Handle REST exceptions for realms that are not configured to provide raw data.
  classes/Rest/Controllers/WarehouseControllerProvider.php
  tests/integration/lib/Rest/WarehouseControllerProviderTest.php
Labels: bug

#1893 Patch for symfony/http-foundation: CVE-2019-10913
  open_xdmod/modules/xdmod/assets/setup.sh
  open_xdmod/modules/xdmod/assets/symfony_http-foundation_CVE-2019-10913.patch
  open_xdmod/modules/xdmod/build.json
  tests/ci/scripts/qa-test-setup.sh
Labels: Category:General, security

#1895 Refactor REST warehouse raw data realm validation.
  classes/Rest/Controllers/WarehouseControllerProvider.php
  tests/integration/lib/Rest/WarehouseControllerProviderTest.php
Labels: enhancement, Category: Data Analytics Framework, php

#1896 Adding logic to catch invalid datetime values
  classes/Rest/Controllers/BaseControllerProvider.php
  tests/integration/lib/BaseTest.php
Labels: bug, Category:Infrastructure

#1897 Add default value for modw_cloud.instance_type_union table
  classes/OpenXdmod/Migration/Version1050To1100/DatabasesMigration.php
  configuration/etl/etl.d/xdmod-migration-10_5_0-11_0_0.json
  configuration/etl/etl_tables.d/cloud_common/instance_type_union.json
Labels: Category:Cloud

#1901 Add missing user manual updates.
  user_manual_builder/About.rst
  user_manual_builder/Dashboard_Tab.rst
  user_manual_builder/Efficiency.rst
  user_manual_builder/Job_Viewer.rst
  user_manual_builder/Metric_Explorer.rst
  user_manual_builder/media/image112.png
  user_manual_builder/media/image132.png
  user_manual_builder/media/image137.png
Labels: documentation

#1900 Fix `undefined index` during aggregate chart swap axis
  classes/DataWarehouse/Visualization/AggregateChart.php
Labels: bug

#1899 Improve xaxis tick placement for all timeseries plots
  classes/DataWarehouse/Visualization/AggregateChart.php
  classes/DataWarehouse/Visualization/TimeseriesChart.php
  html/gui/js/PlotlyChartWrapper.js
  html/gui/js/libraries/PlotlyUtilities.js
  tests/artifacts/xdmod/regression/images/expected-rocky8.5.json
Labels: enhancement

#1908 Specify `mongodb` version in software requirements
  10.5/software-requirements.md
Labels: documentation

#1909 Upping the release to rc.2
  open_xdmod/modules/xdmod/build.json
Labels: autodoc:ignore, Category:Infrastructure

#1904 Extend support window for 10.5.
  docs/support.md
Labels: documentation

#1906 Extend support window for 10.5.
  10.5/support.md
Labels: documentation

#1905 Extend support window for 10.5.
  docs/support.md
Labels: documentation
