Repository ubccr/xdmod, pull requests merged in 2024-10, with the labels that each got.

#1918 Updating Team Page
  html/about/team.html
Labels: documentation, autodoc:ignore

#1919 Adding Jennifer as Co-Pi
  html/about/team.html
Labels: documentation, autodoc:ignore

#1926 Extend support window for 10.5.
  docs/support.md
Labels: documentation

#1927 Extend support window for 10.5.
  docs/support.md
Labels: documentation

#1925 Update upgrade notes for 11.0.0.
  docs/upgrade.md
Labels: documentation

#1928 Add 11.0 to the support docs.
  docs/support.md
Labels: documentation

#1920 Update changelog and release notes.
  CHANGELOG.md
  html/about/release_notes/xdmod.html
  open_xdmod/modules/xdmod/xdmod.spec.in
Labels: documentation, release prep

#1937 Update version of MongoDB in software requirements docs.
  docs/software-requirements.md
Labels: documentation

#1938 Update version of MongoDB in software requirements docs.
  11.0/software-requirements.md
  sitemap.xml
Labels: documentation
