Repository ubccr/xdmod, pull requests merged in 2024-12, with the labels that each got.

#1887 Disallow range entry box on axis
  html/gui/js/PlotlyChartWrapper.js
Labels: enhancement, Category:Metric Explorer

#1916 Update documentation for charts in user manual
  user_manual_builder/Common_User_Interface_Elements.rst
  user_manual_builder/Metric_Explorer.rst
  user_manual_builder/media/metric_explorer_legend_context_menu.png
  user_manual_builder/media/metric_explorer_reset_zoom.png
  user_manual_builder/media/metric_explorer_xaxis_context_menu.png
  user_manual_builder/media/metric_explorer_yaxis_context_menu.png
  user_manual_builder/media/plot_horizontal_zoom.png
  user_manual_builder/media/plot_vertical_zoom.png
Labels: documentation

#1941 Fix marker opacity of mostly null data series
  classes/DataWarehouse/Visualization/AggregateChart.php
  classes/DataWarehouse/Visualization/TimeseriesChart.php
Labels: bug, Category:Metric Explorer

#1956 Adding resource_organization_id, person_organization_id, piperson_organization_id to cloudfact tables
  configuration/etl/etl_action_defs.d/cloud_common/cloud_metrics_aggregation.json
  configuration/etl/etl_action_defs.d/cloud_common/cloud_metrics_aggregation_by_day.json
  configuration/etl/etl_action_defs.d/cloud_common/session_records.json
  configuration/etl/etl_tables.d/cloud_common/cloudfact_by_.json
  configuration/etl/etl_tables.d/cloud_common/cloudfact_by_day.json
  configuration/etl/etl_tables.d/cloud_common/session_records.json
Labels: Category:Cloud

#1921 Fix unified hoverlabels including data from different points
  classes/DataWarehouse/Visualization/AggregateChart.php
Labels: bug

#1958 Adding resource_organization_id, person_organization_id, piperson_organization_id to cloudfact tables
  configuration/etl/etl_action_defs.d/cloud_common/cloud_metrics_aggregation.json
  configuration/etl/etl_action_defs.d/cloud_common/cloud_metrics_aggregation_by_day.json
  configuration/etl/etl_action_defs.d/cloud_common/session_records.json
  configuration/etl/etl_tables.d/cloud_common/cloudfact_by_.json
  configuration/etl/etl_tables.d/cloud_common/cloudfact_by_day.json
  configuration/etl/etl_tables.d/cloud_common/session_records.json
Labels: Category:Cloud

#1947 Fix various bugs found when testing strict SQL modes
  classes/DataWarehouse/Access/ReportGenerator.php
  classes/OpenXdmod/Setup/AdminUserSetup.php
  classes/XDUser.php
  configuration/etl/etl_action_defs.d/storage/xdw/storagefact.aggregation.json
  tests/integration/lib/TestHarness/UserHelper.php
Labels: bug

#1935 More documentation updates
  docs/index.md
Labels: documentation
