Repository ubccr/xdmod, pull requests merged in 2024-05, with the labels that each got.

#1822 Highcharts conversion to Plotly JS
  .gitignore
  CHANGELOG.md
  NOTICE
  background_scripts/chrome-helper/chrome-helper.js
  classes/DataWarehouse/Access/Common.php
  classes/DataWarehouse/Access/MetricExplorer.php
  classes/DataWarehouse/Access/Usage.php
  classes/DataWarehouse/Data/SimpleTimeseriesData.php
  classes/DataWarehouse/Query/Query.php
  classes/DataWarehouse/Visualization/AggregateChart.php
  classes/DataWarehouse/Visualization/ColorGenerator.php
  classes/DataWarehouse/Visualization/HighChart2.php
  classes/DataWarehouse/Visualization/HighChartTimeseries2.php
  classes/DataWarehouse/Visualization/TimeseriesChart.php
  classes/Realm/GroupBy.php
  classes/Rest/Controllers/WarehouseControllerProvider.php
  composer.json
  composer.lock
  docs/index.md
  docs/notices.md
  docs/upgrade.md
  docs/xdmod-rest-schema.json
  html/.eslintrc.json
  html/about/release_notes/xdmod.html
  html/gui/js/AddDataPanel.js
  html/gui/js/CCR.js
  html/gui/js/DurationToolbar.js
  html/gui/js/HighChartPanel.js
  html/gui/js/HighChartWrapper.js
  html/gui/js/PlotlyChartWrapper.js
  html/gui/js/PlotlyPanel.js
  html/gui/js/libraries/PlotlyUtilities.js
  html/gui/js/modules/Summary.js
  html/gui/js/modules/Usage.js
  html/gui/js/modules/dashboard/ChartComponent.js
  html/gui/js/modules/dashboard/ReportThumbnailsComponent.js
  html/gui/js/modules/job_viewer/ChartPanel.js
  html/gui/js/modules/metric_explorer/MetricExplorer.js
  html/gui/lib/highchartsChartClicks.src.js
  html/gui/lib/highchartsDateformats.src.js
  html/gui/lib/highchartsDottedLineNullPlot.src.js
  html/highchart_template.html
  html/index.php
  html/internal_dashboard/index.php
  html/plotly_template.html
  libraries/charting.php
  open_xdmod/modules/xdmod/build.json
  tests/artifacts/xdmod/regression/images/expected-rocky8.5.json
  tests/artifacts/xdmod/ui/output/metricExplorer.json
  tests/component/lib/Query/AggregateQueryTest.php
  tests/component/lib/Query/TimeseriesQueryTest.php
  tests/integration/lib/Controllers/MetricExplorerTest.php
  tests/integration/lib/Controllers/UsageExplorerTest.php
  tests/regression/lib/Controllers/MetricExplorerChartsTest.php
  tests/ui/test/specs/xdmod/metricExplorer.js
  tests/ui/test/specs/xdmod/metricExplorer.page.js
  tests/ui/test/specs/xdmod/usageTab.js
  tests/ui/test/specs/xdmod/usageTab.page.js
  tests/ui/webdriverHelpers/waitUntilChartLoadsBySeries.js
Labels: Category:Metric Explorer, javascript, php

#1762 Fix zoom resetting to incorrect initial range values
  html/gui/js/modules/job_viewer/GanttChart.js
Labels: bug, Category:Job Viewer, javascript

#1760 Remove HighCharts error handling for ChartTab component
  html/gui/js/modules/job_viewer/ChartTab.js
Labels: Category:Job Viewer, javascript

#1840 Fix timing error in internal dashboard UI test
  tests/ui/.eslintrc.json
  tests/ui/test/specs/xdmod/internalDashboard.js
  tests/ui/test/specs/xdmod/internalDashboard.page.js
Labels: qa / testing, autodoc:ignore

#1837 Change resource specs aggregation to better handle joins to modw.resource_allocated table
  configuration/etl/etl_action_defs.d/resource_specifications/resource_specs_aggregation.json
  configuration/etl/etl_action_defs.d/resource_specifications/resource_specs_aggregation_by_day.json
  configuration/etl/etl_macros.d/resource_specs_time_diff.sql
Labels: Category:ETL, autodoc:ignore

#1834 Adding data analytics paper
  html/about/publications.html
Labels: Category:General, autodoc:ignore

#1845 Update user manual content for the Allocations Tab
  user_manual_builder/Allocations_Tab.rst
  user_manual_builder/media/allocations_active.png
  user_manual_builder/media/allocations_expired.png
  user_manual_builder/media/allocations_search.png
  user_manual_builder/media/allocations_summary.png
  user_manual_builder/media/allocations_tab.png
  user_manual_builder/media/allocations_user_info.png
Labels: documentation, Category:Allocations

#1847 Update CHANGELOG for user manual
  CHANGELOG.md
Labels: documentation, release prep

#1849 Increase size of ResourceSpecs su aggregate columns
  configuration/etl/etl_tables.d/resource_specifications/resourcespecsfact_by_.json
  configuration/etl/etl_tables.d/resource_specifications/resourcespecsfact_by_day.json
Labels: Category:General, autodoc:ignore

#1756 Remove jQuery dependency
  NOTICE
  composer.json
  composer.lock
  docs/notices.md
  html/.eslintrc.json
  html/gui/js/AddDataPanel.js
  html/gui/js/CCR.js
  html/gui/js/PlotlyChartWrapper.js
  html/gui/js/PlotlyPanel.js
  html/gui/js/modules/Summary.js
  html/gui/js/modules/Usage.js
  html/gui/js/modules/dashboard/ChartComponent.js
  html/gui/js/modules/job_viewer/ChartTab.js
  html/gui/js/modules/metric_explorer/MetricExplorer.js
  html/index.php
  html/internal_dashboard/index.php
  html/password_reset.php
  html/plotly_template.html
Labels: maintenance / code quality, dependencies

#1853 Remove `jquery-base64` from NOTICE
  NOTICE
Labels: documentation

#1787 Add extra explaination about anonymised fields for the Data Export tab
  html/gui/js/modules/DataExport.js
Labels: enhancement

#1824 Parse request method, URL, and protocol separately in web server logs.
  .gitignore
  classes/ETL/DataEndpoint/WebServerLogFile.php
  tests/artifacts/xdmod/etlv2/dataendpoint/input/webserverlogfile/test.log
  tests/unit/lib/ETL/DataEndpoint/WebServerLogFileTest.php
Labels: enhancement, Open OnDemand

#1854 Allow double JSON pointers in configuration files.
  classes/Configuration/Configuration.php
  tests/artifacts/xdmod/etlv2/configuration/input/sample_config_with_double_reference.json
  tests/artifacts/xdmod/etlv2/configuration/input/sample_config_with_transformer_keys.json
  tests/artifacts/xdmod/etlv2/configuration/output/sample_config_with_transformer_keys.expected
  tests/unit/lib/ETL/Configuration/ConfigurationTest.php
Labels: bug

#1745 Add copy to clipboard when getting shareable link
  html/gui/js/modules/job_viewer/SearchHistoryPanel.js
Labels: enhancement, Category:Job Viewer

#1858 Change warehouse raw data endpoint to respond with JSON text sequence.
  classes/Rest/Controllers/WarehouseControllerProvider.php
  docs/xdmod-rest-schema.json
  tests/artifacts/xdmod/regression/current/expected/reference/raw-data/cloud-fields-and-filters.json
  tests/artifacts/xdmod/regression/current/expected/reference/raw-data/cloud.json
  tests/artifacts/xdmod/regression/current/expected/reference/raw-data/jobs-fields-and-filters.json
  tests/artifacts/xdmod/regression/current/expected/reference/raw-data/jobs-fresh_install.json
  tests/artifacts/xdmod/regression/current/expected/reference/raw-data/jobs-upgrade.json
  tests/artifacts/xdmod/regression/current/expected/reference/raw-data/resourcespecifications-fields-and-filters.json
  tests/artifacts/xdmod/regression/current/expected/reference/raw-data/resourcespecifications.json
  tests/regression/lib/TestHarness/RegressionTestHelper.php
Labels: Category: Data Analytics Framework, php

#1850 Plotly conversion bug fixes
  classes/DataWarehouse/Access/Usage.php
  classes/DataWarehouse/Visualization/AggregateChart.php
  classes/DataWarehouse/Visualization/TimeseriesChart.php
  html/gui/js/PlotlyChartWrapper.js
  html/plotly_template.html
  tests/artifacts/xdmod/regression/images/expected-rocky8.5.json
Labels: bug

#1859 Add Metric Explorer copy to clipboard
  CHANGELOG.md
  html/about/release_notes/xdmod.html
  html/gui/js/modules/metric_explorer/MetricExplorer.js
Labels: enhancement, documentation, Category:Metric Explorer

#1856 Update description of Job Size: Normalized statistic
  configuration/datawarehouse.d/ref/Jobs-statistics.json
Labels: documentation, autodoc:ignore

#1860 Update `.gitignore`
  .gitignore
Labels: maintenance / code quality
