Repository ubccr/xdmod, pull requests merged in 2024-09, with the labels that each got.

#1912 Various doc fixes.
  docs/install-rpm.md
  docs/install-source.md
  docs/notices.md
  docs/upgrade.md
Labels: documentation

#1910 Backport docs changes from 11.0 to 10.5.
  docs/install-rpm.md
  docs/openidc.md
  docs/simpleSAMLphp-ldap.md
  docs/simpleSAMLphp.md
  docs/upgrade.md
  docs/xdmod-rest-schema.json
Labels: documentation

#1879 Add additional information for 11.0 upgrade
  docs/upgrade.md
Labels: Category:General, autodoc:ignore

#1892 Add resource specifications documentation
  docs/_data/toc.yml
  docs/configuration.md
  docs/ingestor.md
  docs/resource-specifications.md
Labels: documentation

#1915 adding upgrade information for resource specs
  docs/upgrade.md
Labels: documentation, autodoc:ignore

#1917 Update `build.json` and `spec` file for 11.0.0 release
  open_xdmod/modules/xdmod/build.json
  open_xdmod/modules/xdmod/xdmod.spec.in
Labels: release prep
