Repository ubccr/xdmod, pull requests merged in 2024-02, with the labels that each got.

#1817 Fix API token expiration message.
  html/gui/js/profile_editor/ProfileApiToken.js
Labels: bug, javascript, Category: Data Analytics Framework

#1812 Update list of supported versions on website.
  docs/support.md
Labels: documentation

#1793 Add slightly less confusing error message.
  html/index.php
Labels: bug

#1819 Fix syntax error in regression test
  tests/regression/lib/Controllers/UsageChartsTest.php
Labels: bug

#1814 Escape double quotes when migrating portal settings.
  classes/OpenXdmod/Migration/ConfigFilesMigration.php
Labels: bug

#1816 Allow `@` in remote user format string when parsing web server log files.
  classes/ETL/DataEndpoint/WebServerLogFile.php
  composer.json
Labels: enhancement

#1792 Change warehouse raw data endpoint to stream response.
  classes/Rest/Controllers/WarehouseControllerProvider.php
  configuration/portal_settings.ini
  docs/data-analytics-framework.md
  docs/xdmod-rest-schema.json
  templates/portal_settings.template
  tests/artifacts/xdmod/regression/current/expected/reference/raw-data/jobs-fields-and-filters.json
  tests/artifacts/xdmod/regression/current/expected/reference/raw-data/jobs-fresh_install.json
  tests/artifacts/xdmod/regression/current/expected/reference/raw-data/jobs-upgrade.json
  tests/integration/lib/Rest/WarehouseControllerProviderTest.php
  tests/regression/lib/Rest/WarehouseRawDataTest.php
Labels: enhancement, Category:Data Warehouse Export, Category: Data Analytics Framework, php
