Repository ubccr/xdmod, pull requests merged in 2025-05, with the labels that each got.

#2034 Removing incorrect migration file and merging contents into correct migration file
  configuration/etl/etl.d/xdmod-migration-11_0_0-11_5_0.json
  configuration/etl/etl.d/xdmod-migration_11_0_0-11_5_0.json
Labels: bug

#2028 Remove Data Analytics Framework token authentication via GET/POST params.
  classes/Models/Services/Tokens.php
  classes/Rest/Controllers/BaseControllerProvider.php
  docs/data-analytics-framework.md
  docs/xdmod-rest-schema.json
  html/controllers/metric_explorer/get_dimension.php
  html/controllers/metric_explorer/get_dw_descripter.php
  html/controllers/user_interface/get_charts.php
  tests/integration/lib/TokenAuthTest.php
  user_manual_builder/About.rst
Labels: maintenance / code quality, Category: Data Analytics Framework, php

#2039 Moved 11.5 etl migration actions into migration etl file instead of referencing them
  configuration/etl/etl.d/xdmod-migration-11_0_0-11_5_0.json
Labels: Category:ETL, autodoc:ignore

#2036 Dependabot Fixes
  classes/Rest/Controllers/BaseControllerProvider.php
  classes/Rest/XdmodApplicationFactory.php
  composer.json
  composer.lock
  open_xdmod/modules/xdmod/assets/simplesamlPHP-CVE-2020-5301.patch
  open_xdmod/modules/xdmod/assets/simplesamlphp-CVE-2020-5225.patch
  open_xdmod/modules/xdmod/assets/simplesamlphp-SSPSA_201907-01_HTTP.patch
  open_xdmod/modules/xdmod/assets/simplesamlphp-SSPSA_201907-01_postredirect.patch
  open_xdmod/modules/xdmod/assets/symfony_http-foundation_CVE-2019-10913.patch
  open_xdmod/modules/xdmod/build.json
Labels: Category:Infrastructure, security

#2042 Dependabot Fixes
  classes/Rest/Controllers/BaseControllerProvider.php
  classes/Rest/XdmodApplicationFactory.php
  composer.json
  composer.lock
  open_xdmod/modules/xdmod/assets/simplesamlPHP-CVE-2020-5301.patch
  open_xdmod/modules/xdmod/assets/simplesamlphp-CVE-2020-5225.patch
  open_xdmod/modules/xdmod/assets/simplesamlphp-SSPSA_201907-01_HTTP.patch
  open_xdmod/modules/xdmod/assets/simplesamlphp-SSPSA_201907-01_postredirect.patch
  open_xdmod/modules/xdmod/assets/symfony_http-foundation_CVE-2019-10913.patch
  open_xdmod/modules/xdmod/build.json
Labels: Category:Infrastructure, security
