Repository ubccr/xdmod, pull requests merged in 2025-04, with the labels that each got.

#2015 Update gh-pages site for 11.0.1 and 10.5.1.
  10.5/dev-code-organization.md
  10.5/docs-conventions.md
  10.5/install-rpm.md
  10.5/install-source.md
  10.5/upgrade.md
  11.0/configuration.md
  11.0/dev-code-organization.md
  11.0/docs-conventions.md
  11.0/index.md
  11.0/install-rpm.md
  11.0/install-source.md
  11.0/install.md
  11.0/upgrade.md
  _config.yml
  sitemap.xml
Labels: documentation

#2018 Add ingestion by date range for Storage realm
  bin/xdmod-ingestor
  classes/OpenXdmod/DataWarehouseInitializer.php
  configuration/etl/etl.d/hpcdb.json
  configuration/etl/etl_action_defs.d/storage/hpcdb/usage-to-ingest-date-range.json
  configuration/etl/etl_action_defs.d/storage/hpcdb/usage-to-ingest-new-usage.json
  configuration/etl/etl_action_defs.d/storage/xdw/storagefact.json
  configuration/etl/etl_tables.d/storage/hpcdb/usage-to-ingest.json
Labels: Category:ETL, Category:Storage

#1973 Adding ability to save Regression Test UsageChart images
  tests/regression/lib/Controllers/UsageChartsTest.php
Labels: qa / testing, autodoc:ignore, Category:Infrastructure

#2029 Updating playwright docker image version
  tests/playwright/Docker/docker-compose.yml
  tests/playwright/package-lock.json
  tests/playwright/package.json
  tests/playwright/runtests.sh
Labels: autodoc:ignore, Category:Infrastructure

#2031 Plotly JS charts now consider timezones
  html/gui/js/PlotlyChartWrapper.js
Labels: bug, Category:Metric Explorer

#2025 Increase robustnification.
  tests/playwright/lib/metricExplorer.page.ts
  tests/playwright/tests/metricExplorer/metricExplorer.spec.ts
Labels: maintenance / code quality

#2019 Update tacc_stats Package Name
  html/about/supremm.html
Labels: documentation

#1965 Removing organization join in jobs ingestion to improve performance
  configuration/etl/etl_action_defs.d/jobs/xdw/job-records-job-tasks.json
Labels: enhancement, Category:ETL
