Repository ubccr/xdmod, pull requests merged in 2025-03, with the labels that each got.

#1995 Specify php mongodb driver (1.18.1)
  .circleci/config.yml
  docs/software-requirements.md
  docs/upgrade.md
Labels: qa / testing

#1996 Fix regression introduced in efbd9ce0d2dbe5e1f214d72fe0cf0cc1523ea487
  classes/DataWarehouse/Visualization/AggregateChart.php
Labels: bug, autodoc:ignore

#1992 Refactor timeseries ticklabels
  classes/DataWarehouse/Access/Usage.php
  classes/DataWarehouse/Visualization/TimeseriesChart.php
  html/.eslintrc.json
  html/gui/js/PlotlyChartWrapper.js
  html/gui/js/PlotlyPanel.js
  html/gui/js/libraries/PlotlyUtilities.js
  html/gui/js/modules/Usage.js
  html/gui/js/modules/metric_explorer/MetricExplorer.js
  html/plotly_template.html
Labels: bug, Category:Metric Explorer

#1997 Use xdmod10.5 logic for enabling markers
  classes/DataWarehouse/Visualization/AggregateChart.php
  classes/DataWarehouse/Visualization/TimeseriesChart.php
Labels: bug, Category:Metric Explorer

#1998 Refactor timeseries ticklabels
  classes/DataWarehouse/Access/Usage.php
  classes/DataWarehouse/Visualization/TimeseriesChart.php
  html/.eslintrc.json
  html/gui/js/PlotlyChartWrapper.js
  html/gui/js/PlotlyPanel.js
  html/gui/js/libraries/PlotlyUtilities.js
  html/gui/js/modules/Usage.js
  html/gui/js/modules/metric_explorer/MetricExplorer.js
  html/plotly_template.html
Labels: bug, Category:Metric Explorer

#2002 Prepare for 11.0.1-rc.3 release candidate.
  open_xdmod/modules/xdmod/build.json
Labels: release prep

#1950 Prep changelog and release notes for 11.0.1.
  CHANGELOG.md
  docs/upgrade.md
  html/about/release_notes/xdmod.html
  open_xdmod/modules/xdmod/build.json
  open_xdmod/modules/xdmod/xdmod.spec.in
Labels: release prep

#2004 Update changelog and release notes for 11.0.1.
  CHANGELOG.md
  html/about/release_notes/xdmod.html
  open_xdmod/modules/xdmod/build.json
  open_xdmod/modules/xdmod/xdmod.spec.in
Labels: release prep

#2008 Update upgrade docs.
  docs/_config.yml
  docs/install-rpm.md
  docs/install.md
  docs/upgrade.md
Labels: documentation

#2009 Update upgrade docs.
  docs/_config.yml
  docs/install-rpm.md
  docs/install.md
  docs/upgrade.md
Labels: documentation

#2010 Remove unused databases migration.
  classes/OpenXdmod/Migration/Version1050To1051/DatabasesMigration.php
Labels: release prep

#2006 Added Xdebug Support to Circle CI for Code Coverage
  .circleci/config.yml
  tools/dev/code_coverage/codeCoverageProcess.sh
  tools/dev/code_coverage/codeCoverageSetup.sh
  tools/dev/code_coverage/combine_xdebug.php
  tools/dev/code_coverage/start_xdebug.php
Labels: qa / testing, Category:General

#2005 Change destination and source config used for 11.5 migration pipeline
  configuration/etl/etl.d/xdmod-migration_11_0_0-11_5_0.json
Labels: Category:ETL

#2013 Remove unused code.
  html/gui/css/common_ie8.css
  html/gui/css/common_ie9.css
  html/gui/js/TreeCheckbox.js
  html/gui/js/report_builder/Reporting.js
  html/gui/js/report_builder/ReportsOverview.js
  html/gui/lib/MessageWindow.js
  html/gui/lib/internet-explorer-polyfills.js
  html/index.php
  html/internal_dashboard/index.php
Labels: maintenance / code quality, autodoc:ignore

#2014 Update docs.
  docs/_config.yml
  docs/dev-code-organization.md
  docs/docs-conventions.md
  docs/install-rpm.md
  docs/install-source.md
  docs/upgrade.md
Labels: documentation

#2017 Update RPM install/upgrade instructions.
  docs/install-rpm.md
  docs/upgrade.md
Labels: documentation

#2020 Update docs.
  docs/_config.yml
  docs/dev-code-organization.md
  docs/docs-conventions.md
  docs/install-rpm.md
  docs/install-source.md
  docs/upgrade.md
Labels: documentation

#2021 Update docs.
  docs/_config.yml
  docs/dev-code-organization.md
  docs/docs-conventions.md
  docs/install-rpm.md
  docs/install-source.md
  docs/upgrade.md
Labels: documentation
